# Módulo 03: Carregamento de Dados, Armazenamento e Formatos de Arquivos
>
> [Universidade Federal do Ceará (UFC)](https://www.ufc.br/)\
> [Departamento de Computação (DC)](https://dc.ufc.br/pt/)\
> [Capacitação Técnica e Empreendedora em IA (CTE-IA)](https://www.cteia.dc.ufc.br/)\
> Fase I: Capacitação Teórica de IA\
> Disciplina: Programação para Ciência de Dados (60h)\
> Professor: [Lincoln S. Rocha](http://lattes.cnpq.br/0656977742590515)\
> E-mail: <lincoln@dc.ufc.br>
>

Ler dados e torná-los acessíveis (carregamento de dados) é um primeiro passo necessário para usar a maioria das ferramentas de análise de dados estudadas neste curso. O principal objetivo deste módulo é apresentar os conceitos fundamentais de entrada e saída de dados usando o Pandas. Este módulo cobrirá o seguinte conteúdo:

1. Leitura e Escrita de Dados Textuais
2. Formatos de Dados Binários
3. Interagindo com APIs da Web
4. Interagindo com Bancos de Dados

## 1. Leitura e Escrita de Dados Textuais

O Pandas apresenta diversas funções para leitura de dados tabulares como um objeto `DataFrame`. A tabela abaixo resume algumas delas; `pandas.read_csv` é uma das mais usadas neste curso.

| Função | Descrição |
|---------|------------|
| `read_csv` | Carrega dados delimitados de um arquivo, URL ou objeto semelhante a arquivo (`file-like`); usa vírgula como delimitador padrão. |
| `read_fwf` | Lê dados em formato de colunas de largura fixa (ou seja, sem delimitadores). |
| `read_clipboard` | Variação de `read_csv` que lê dados diretamente da área de transferência; útil para converter tabelas copiadas de páginas da web. |
| `read_excel` | Lê dados tabulares de um arquivo Excel nos formatos XLS ou XLSX. |
| `read_hdf` | Lê arquivos HDF5 gravados pelo pandas. |
| `read_html` | Lê todas as tabelas encontradas em um documento HTML fornecido. |
| `read_json` | Lê dados de uma string, arquivo, URL ou objeto semelhante a arquivo no formato JSON (JavaScript Object Notation). |
| `read_feather` | Lê arquivos no formato binário Feather. |
| `read_orc` | Lê arquivos no formato binário Apache ORC. |
| `read_parquet` | Lê arquivos no formato binário Apache Parquet. |
| `read_pickle` | Lê um objeto armazenado pelo pandas usando o formato Python pickle. |
| `read_sas` | Lê um conjunto de dados SAS armazenado em um dos formatos personalizados do sistema SAS. |
| `read_spss` | Lê um arquivo de dados criado pelo SPSS. |
| `read_sql` | Lê os resultados de uma consulta SQL (usando SQLAlchemy). |
| `read_sql_table` | Lê uma tabela SQL completa (usando SQLAlchemy); equivalente a executar uma consulta que seleciona todos os dados dessa tabela usando `read_sql`. |
| `read_stata` | Lê um conjunto de dados do formato de arquivo Stata. |
| `read_xml` | Lê uma tabela de dados a partir de um arquivo XML. |

### 1.1. Visão Geral

Apresentaremos uma visão geral da mecânica dessas funções, que visam converter dados de texto em um `DataFrame`. Os argumentos opcionais para essas funções podem se enquadrar em algumas categorias:

- *Indexação*. Pode tratar uma ou mais colunas como o `DataFrame` retornado e determinar se deseja obter
nomes de colunas do arquivo, argumentos fornecidos por você ou não.

- *Inferência de tipos e conversão de dados*. Inclui as conversões de valores definidas pelo usuário e uma lista personalizada de marcadores de valores ausentes.

- *Análise de data e hora*. Inclui um recurso de combinação, incluindo a combinação de informações de data e hora distribuídas por várias colunas em uma única coluna no resultado.

- *Iteração*. Suporte para iteração em partes de arquivos muito grandes.

- *Problemas com dados sujos*. Inclui pular linhas ou um rodapé, comentários ou outras coisas menores, como dados numéricos com milhares separados por vírgulas.

Devido à confusão de dados no mundo real, algumas das funções de carregamento de dados (especialmente `pandas.read_csv`) acumularam uma longa lista de argumentos opcionais ao longo do tempo. É normal se sentir sobrecarregado com o número de parâmetros diferentes (`pandas.read_csv` tem cerca de 50). A [documentação online do Pandas](https://pandas.pydata.org/docs/) tem muitos exemplos sobre como cada um deles funciona, então se você estiver com dificuldades para ler um arquivo específico, pode haver um exemplo semelhante o suficiente para ajudá-lo a encontrar os parâmetros corretos.

Algumas dessas funções realizam inferência de tipos, pois os tipos de dados das colunas não fazem parte do formato dos dados. Isso significa que você não precisa necessariamente especificar quais colunas são numéricas, inteiras, booleanas ou strings. Outros formatos de dados, como `HDF5`, `ORC` e `​​Parquet`, possuem as informações do tipo de dados incorporadas ao formato.

Manipular datas e outros tipos personalizados pode exigir um esforço extra.

Vamos começar com um pequeno arquivo de texto com valores separados por vírgula (CSV): `ex1.csv`

Como ele é delimitado por vírgulas, podemos usar `pandas.read_csv` para lê-lo em um `DataFrame`:

In [4]:
import pandas as pd

df = pd.read_csv('./examples/ex1.csv')
df

   1   2   3   4  hello
0  5   6   7   8  world
1  9  10  11  12    foo

Um arquivo nem sempre terá uma linha de cabeçalho. Considere este arquivo: `ex2.csv`

Para ler este arquivo, você tem algumas opções. Você pode permitir que o Pandas atribua nomes de coluna padrão ou pode especificar os nomes você mesmo:

In [5]:
pd.read_csv('./examples/ex2.csv', header=None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [6]:
pd.read_csv('./examples/ex2.csv', names=['a', 'b', 'c', 'd', 'message'])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

Suponha que você queira que a coluna de mensagem seja o índice do `DataFrame` retornado. Você pode indicar que deseja a coluna no índice `4` ou com o nome `"message"` usando o argumento `index_col`:

In [7]:
names = ['a', 'b', 'c', 'd', 'message']

pd.read_csv('./examples/ex2.csv', names=names, index_col='message')

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

Se você quiser formar um índice hierárquico de várias colunas, passe uma lista de números ou nomes de colunas, veja `csv_mindex.csv`

In [9]:
parsed = pd.read_csv('./examples/csv_mindex.csv', index_col=['key1', 'key2'])
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

Em alguns casos, uma tabela pode não ter um delimitador fixo, usando espaços em branco ou algum outro padrão para separar os campos. Considere um arquivo de texto como `ex3.txt`

Embora você possa fazer algumas manipulações manualmente, os campos aqui são separados por uma quantidade variável de espaços em branco. Nesses casos, você pode passar uma expressão regular como delimitador para `pandas.read_csv`. Isso pode ser expresso pela expressão regular `\s+`, então temos:

In [10]:
res = pd.read_csv('./examples/ex3.txt', sep=r'\s+')
res

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

Como havia um nome de coluna a menos que o número de linhas de dados, `pandas.read_csv` infere que a primeira coluna deve ser o índice do DataFrame neste caso especial.

As funções de análise de arquivos têm muitos argumentos adicionais para ajudar você a lidar com a ampla variedade de formatos de arquivo de exceção que ocorrem. Por exemplo, você pode pular a primeira, a terceira e a quarta linhas de um arquivo com `skiprows` em `ex4.csv`

In [11]:
pd.read_csv('./examples/ex4.csv', skiprows=[0, 2, 3])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

O tratamento de valores ausentes é uma parte importante e frequentemente complexa do processo de leitura de arquivos. Dados ausentes geralmente não estão presentes (string vazia) ou são marcados por algum valor sentinela (espaço reservado). Por padrão, o Pandas usa um conjunto de sentinelas comuns, como `NA` e `NULL` (`ex5.csv`)

In [12]:
res = pd.read_csv('./examples/ex5.csv')
res

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

Lembre-se de que o Pandas gera valores ausentes como `NaN`, então temos dois valores nulos ou ausentes no resultado:

In [13]:
pd.isna(res)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

A opção `na_values` ​​aceita uma sequência de strings para adicionar à lista padrão de strings reconhecidas como ausentes:

In [14]:
res = pd.read_csv('./examples/ex5.csv', na_values='NULL')
res

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

`pandas.read_csv` tem uma lista de muitas representações de valores `NA` padrão, mas esses padrões podem ser desabilitados com a opção `keep_default_na`:

In [15]:
res_2 = pd.read_csv('./examples/ex5.csv', keep_default_na=False)
res_2

  something  a   b   c   d message
0       one  1   2   3   4      NA
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [16]:
res_2.isna()

   something      a      b      c      d  message
0      False  False  False  False  False    False
1      False  False  False  False  False    False
2      False  False  False  False  False    False

In [17]:
res_3 = pd.read_csv('./examples/ex5.csv', keep_default_na=False, na_values="NA")
res_3

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [18]:
res_3.isna()

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False  False  False    False
2      False  False  False  False  False    False

Diferentes sentinelas `NA` podem ser especificadas para cada coluna em um dicionário:

In [19]:
sentinels = {'message': ['foo', 'NA'], 'something': ['two']}

pd.read_csv('./examples/ex5.csv', na_values=sentinels, keep_default_na=False)

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       NaN  5   6       8   world
2     three  9  10  11  12     NaN

A tabela abaixo lista algumas opções usadas com frequência em ` pandas.read_csv`.



| Argumento | Descrição |
|------------|------------|
| `path` | String que indica o local do sistema de arquivos, URL ou objeto semelhante a arquivo (`file-like object`). |
| `sep` ou `delimiter` | Sequência de caracteres ou expressão regular usada para dividir os campos em cada linha. |
| `header` | Número da linha a ser usada como nomes das colunas; o padrão é `0` (primeira linha), mas deve ser `None` se não houver linha de cabeçalho. |
| `index_col` | Números ou nomes das colunas a serem usados como índice de linha no resultado; pode ser um único nome/número ou uma lista deles para um índice hierárquico. |
| `names` | Lista de nomes de colunas para o resultado. |
| `skiprows` | Número de linhas no início do arquivo a serem ignoradas, ou lista de números de linha (começando em 0) a serem puladas. |
| `na_values` | Sequência de valores a serem substituídos por `NA`. Eles são adicionados à lista padrão, a menos que `keep_default_na=False` seja definido. |
| `keep_default_na` | Define se a lista padrão de valores `NA` deve ser usada (`True` por padrão). |
| `comment` | Caracter(es) usados para separar comentários no final das linhas. |
| `parse_dates` | Tenta converter dados para o formato `datetime`; o padrão é `False`. Se `True`, tenta converter todas as colunas. Também é possível especificar uma lista de números ou nomes de colunas a serem convertidas. Se o elemento da lista for uma tupla ou lista, combina múltiplas colunas e as interpreta como uma única data. |
| `keep_date_col` | Se colunas forem combinadas para formar uma data, mantém as colunas originais; o padrão é `False`. |
| `converters` | Dicionário contendo o número ou nome da coluna mapeado para funções (por exemplo, `{"foo": f}` aplicará a função `f` a todos os valores da coluna `"foo"`). |
| `dayfirst` | Ao interpretar datas potencialmente ambíguas, trata-as como formato internacional (por exemplo, `7/6/2012 → 7 de junho de 2012`); o padrão é `False`. |
| `date_parser` | Função a ser usada para analisar (converter) datas. |
| `nrows` | Número de linhas a serem lidas desde o início do arquivo (sem contar o cabeçalho). |
| `iterator` | Retorna um objeto `TextFileReader` para leitura incremental do arquivo. Pode ser usado com a instrução `with`. |
| `chunksize` | Tamanho do bloco de linhas lido por iteração. |
| `skip_footer` | Número de linhas a serem ignoradas no final do arquivo. |
| `verbose` | Exibe informações detalhadas sobre o processo de análise, como o tempo gasto em cada etapa e o uso de memória. |
| `encoding` | Codificação do texto (por exemplo, `"utf-8"` para arquivos em UTF-8). O padrão é `"utf-8"` se `None`. |
| `squeeze` | Se os dados analisados contiverem apenas uma coluna, retorna uma `Series` em vez de um `DataFrame`. |
| `thousands` | Separador de milhares (por exemplo, `","` ou `"."`); o padrão é `None`. |
| `decimal` | Separador decimal em números (por exemplo, `"."` ou `","`); o padrão é `"."`. |
| `engine` | Mecanismo de análise de CSV e conversão a ser usado; pode ser `"c"`, `"python"` ou `"pyarrow"`. O padrão é `"c"`, mas o `"pyarrow"` pode ser mais rápido, e o `"python"` é mais flexível, porém mais lento. |

### 1.2. Lendo Arquivos de Texto em Partes

Ao processar arquivos muito grandes ou descobrir o conjunto correto de argumentos para processar corretamente um arquivo grande, você pode querer ler apenas uma pequena parte do arquivo ou iterar por partes menores.

Antes de analisarmos um arquivo grande, tornamos as configurações de exibição do Pandas mais compactas:

In [20]:
pd.options.display.max_rows = 10

In [21]:
result = pd.read_csv('./examples/ex6.csv')
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

As reticências `...` indicam que as linhas no meio do `DataFrame` foram omitidas.

Se você quiser ler apenas um pequeno número de linhas (evitando ler o arquivo inteiro), especifique isso com `nrows`:

In [ ]:
pd.read_csv('./examples/ex6.csv', nrows=5)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

Para ler um arquivo em partes, especifique um `chunksize` como um número de linhas:

In [24]:
chunker = pd.read_csv('./examples/ex6.csv', chunksize=1000)

type(chunker)

pandas.io.parsers.readers.TextFileReader

O objeto `TextFileReader` retornado por `pandas.read_csv` permite iterar sobre as partes do arquivo de acordo com o `chunksize`. Por exemplo, podemos iterar sobre `ex6.csv`, agregando as contagens de valores na coluna "key", assim:

In [26]:
chunker = pd.read_csv("examples/ex6.csv", chunksize=1000)

tot = pd.Series([], dtype='int64')
for piece in chunker:
    tot = tot.add(piece['key'].value_counts(), fill_value=0)

tot = tot.sort_values(ascending=False)
tot[:5]

key
E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
dtype: float64

`TextFileReader` também é equipado com um método `get_chunk` que permite ler pedaços de tamanho arbitrário.

### 1.3. Escrevendo Dados em Formato de Texto

Os dados também podem ser exportados para um formato delimitado. Vamos considerar um dos arquivos CSV lidos anteriormente:

In [28]:
data = pd.read_csv('./examples/ex5.csv')
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

Usando o método `to_csv` do `DataFrame`, podemos gravar os dados em um arquivo separado por vírgulas:

In [30]:
data.to_csv('./examples/out.csv')

Outros delimitadores podem ser usados, é claro (escrevendo em `sys.stdout` para que ele imprima o resultado em texto no console em vez de em um arquivo):

In [32]:
import sys

data.to_csv(sys.stdout, sep='|')

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

Valores ausentes aparecem como strings vazias na saída. Você pode querer denotá-los por algum outro valor sentinela:

In [33]:
data.to_csv(sys.stdout, na_rep='NULL')

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

Sem outras opções especificadas, os rótulos de linha e coluna são gravados. Ambos podem ser desabilitados:

In [34]:
data.to_csv(sys.stdout, index=False, header=False)

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo

Você também pode escrever apenas um subconjunto das colunas e na ordem que você escolher:

In [35]:
data.to_csv(sys.stdout, index=False, columns=['a', 'b', 'c'])

a,b,c
1,2,3.0
5,6,
9,10,11.0

### 1.4. Trabalhando com Outros Formatos Delimitados

É possível carregar a maioria dos formatos de dados tabulares do disco usando funções como `pandas.read_csv`. Em alguns casos, no entanto, pode ser necessário algum processamento manual. Não é incomum receber um arquivo com uma ou mais linhas malformadas que fazem com que o `pandas.read_csv` falhe. Para ilustrar as ferramentas básicas, considere um pequeno arquivo CSV (`ex7.csv`)

Para qualquer arquivo com um delimitador de caractere único, você pode usar o módulo `csv` integrado do Python. Para usá-lo, passe qualquer arquivo aberto ou objeto semelhante a um arquivo para `csv.reader`:

In [1]:
import csv

file = open('./examples/ex7.csv')
reader = csv.reader(file)

A iteração pelo leitor como um arquivo produz listas de valores com quaisquer caracteres de aspas removidos:

In [2]:
for line in reader:
    print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

A partir daí, cabe a você fazer o trabalho necessário para colocar os dados no formato desejado. Vamos passo a passo. Primeiro, lemos o arquivo em uma lista de linhas:

In [4]:
with open('./examples/ex7.csv') as file:
    lines = list(csv.reader(file))

lines

[['a', 'b', 'c'], ['1', '2', '3'], ['1', '2', '3']]

Em seguida, dividimos as linhas em linha de cabeçalho e linhas de dados:

In [5]:
header, values = lines[0], lines[1:]

Então podemos criar um dicionário de colunas de dados usando uma compreensão de dicionário e a expressão `zip(*values)` (cuidado, pois isso usará muita memória em arquivos grandes), que transpõe linhas para colunas:

In [6]:
data_dict = {h: v for h, v in zip(header, zip(*values))}
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

Os arquivos CSV estão disponíveis em diversos formatos. Para definir um novo formato com um delimitador, convenção de aspas de string ou terminador de linha diferente, poderíamos definir uma subclasse simples de `csv.Dialect`:

In [11]:
file = open('./examples/ex7.csv')

class MyDialect(csv.Dialect):
    lineterminator = '\n'
    delimiter = ';'
    quotechar = '"'
    quoting = csv.QUOTE_MINIMAL

reader = csv.reader(file, dialect=MyDialect)

Também poderíamos fornecer parâmetros de dialeto CSV individuais como palavras-chave para `csv.reader` sem precisar definir uma subclasse:

In [12]:
reader = csv.reader(file, delimiter="|")

As opções possíveis (atributos de csv.Dialect) e o que elas fazem podem ser encontradas na tabela abaixo

| Argumento | Descrição |
|------------|------------|
| `delimiter` | Cadeia de caracteres de um único caractere usada para separar campos; o padrão é `","`. |
| `lineterminator` | Terminador de linha para escrita; o padrão é `"\r\n"`. O leitor ignora isso e reconhece terminadores de linha compatíveis entre plataformas. |
| `quotechar` | Caractere de aspas usado para campos com caracteres especiais (como o delimitador); o padrão é `"'"`. |
| `quoting` | Convenção de aspas. As opções incluem: `csv.QUOTE_ALL` (aspas em todos os campos), `csv.QUOTE_MINIMAL` (somente em campos com caracteres especiais, como o delimitador), `csv.QUOTE_NONNUMERIC` e `csv.QUOTE_NONE` (sem aspas). O padrão é `QUOTE_MINIMAL`. |
| `skipinitialspace` | Ignora espaços em branco após cada delimitador; o padrão é `False`. |
| `doublequote` | Define como lidar com caracteres de aspas dentro de um campo; se `True`, o caractere de aspas é duplicado (veja a documentação online para mais detalhes). |
| `escapechar` | Caractere usado para escapar o delimitador se `quoting` estiver definido como `csv.QUOTE_NONE`; desativado por padrão. |

Para gravar arquivos delimitados manualmente, você pode usar csv.writer. Ele aceita um objeto de arquivo aberto e gravável e as mesmas opções de dialeto e formato que `csv.reader`:

In [13]:
with open('mydata.csv', 'w') as f:
    writer = csv.writer(f, dialect=MyDialect)
    writer.writerow(('one', 'two', 'three'))
    writer.writerow(('1', '2', '3'))
    writer.writerow(('4', '5', '6'))
    writer.writerow(('7', '8', '9'))

### 1.5. Dados no Formato JSON

JSON (abreviação de *JavaScript Object Notation*) tornou-se um dos formatos padrão para envio de dados por solicitação HTTP entre navegadores da web e outros aplicativos. É um formato de dados muito mais livre do que um formato de texto tabular como CSV. Aqui está um exemplo:

In [14]:
obj ="""
{"name": "Wes",
"pet": null,
"cities_lived": ["Akron", "Nashville", "New York", "San Francisco"],
"siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]},
{"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]
}
"""

JSON é um código Python quase válido, com exceção de seu valor nulo, `null`, e algumas outras nuances (como a proibição de vírgulas finais no final de listas). Os tipos básicos são objetos (dicionários), arrays (listas), strings, números, booleanos e nulos. Todas as chaves em um objeto devem ser strings. Existem várias bibliotecas Python para ler e escrever dados JSON. Usaremos `json`, pois ela é integrada à biblioteca padrão do Python. Para converter uma string JSON para o formato Python, use `json.loads`:

In [15]:
import json

result = json.loads(obj)
result

{'name': 'Wes',
 'pet': None,
 'cities_lived': ['Akron', 'Nashville', 'New York', 'San Francisco'],
 'siblings': [{'name': 'Scott', 'age': 34, 'hobbies': ['guitars', 'soccer']},
  {'name': 'Katie', 'age': 42, 'hobbies': ['diving', 'art']}]}

`json.dumps`, por outro lado, converte um objeto Python de volta para JSON:

In [16]:
as_json = json.dumps(result)
as_json

'{"name": "Wes", "pet": null, "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"], "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]}, {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]}'

A maneira de converter um objeto JSON ou uma lista de objetos em um `DataFrame` ou alguma outra estrutura de dados para análise dependerá de você. Convenientemente, você pode passar uma lista de dicionários (que anteriormente eram objetos JSON) para o construtor do `DataFrame` e selecionar um subconjunto dos campos de dados:

In [19]:
siblings = pd.DataFrame(result['siblings'], columns=['name', 'age'])
siblings

    name  age
0  Scott   34
1  Katie   42

O `pandas.read_json` pode converter automaticamente conjuntos de dados JSON em arranjos específicos em uma `Series` ou `DataFrame`. Por exemplo:

As opções padrão para `pandas.read_json` assumem que cada objeto no array JSON é uma linha na tabela:

In [20]:
data = pd.read_json('./examples/example.json')
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

Se você precisar exportar dados do pandas para JSON, uma maneira é usar os métodos `to_json` em `Series` e `DataFrame`:

In [ ]:
data.to_json(sys.stdout)

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}

In [23]:
data.to_json(sys.stdout, orient='records')

[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

### 1.6. XML e HTML: Web Scraping

O Python possui diversas bibliotecas para leitura e gravação de dados nos onipresentes formatos HTML e XML. Exemplos incluem `lxml`, `Beautiful Soup` e `html5lib`. Embora o `lxml` seja comparativamente muito mais rápido em geral, as outras bibliotecas lidam melhor com arquivos HTML ou XML malformados.

O Pandas possui uma função integrada, `pandas.read_html`, que utiliza todas essas bibliotecas para analisar automaticamente tabelas de arquivos HTML como objetos `DataFrame`. Para mostrar como isso funciona, baixei um arquivo HTML (usado na documentação do pandas) do [FDIC dos EUA mostrando falências bancárias](https://www.fdic.gov/bank-failures/failed-bank-list). Primeiro, você precisa instalar algumas bibliotecas adicionais usadas pelo `read_html`: `uv pip install lxml`, `uv pip install beatifulsoup4` e `uv pip install html5lib`

A função `pandas.read_html` tem várias opções, mas, por padrão, ela busca e tenta analisar todos os dados tabulares contidos nas tags `<table>`. O resultado é uma lista de objetos `DataFrame`:

In [24]:
tables = pd.read_html('./examples/fdic_failed_bank_list.html')

len(tables)

1

In [25]:
failures = tables[0]

failures.head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"

Como você aprenderá nos próximos módulos, a partir daqui poderemos prosseguir com alguma limpeza e análise de dados, como calcular o número de falências bancárias por ano:

In [26]:
close_timestamps = pd.to_datetime(failures['Closing Date'])
close_timestamps.dt.year.value_counts(ascending=False)[0:5]

Closing Date
2010    157
2009    140
2011     92
2012     51
2008     25
Name: count, dtype: int64

XML (*Extensible Markup Language*) é outro formato comum de dados estruturados que suporta dados hierárquicos e aninhados com metadados.

Vimos que a função `pandas.read_html` usa `lxml` ou `Beautiful Soup` para analisar dados de HTML. XML e HTML são estruturalmente semelhantes, mas XML é mais genérico. Assim, mostraremos um exemplo de como usar `lxml` para analisar dados de um formato XML mais genérico.

Por muitos anos, a Autoridade de Transporte Metropolitano de Nova York (MTA) publicou uma série de dados sobre seus serviços de ônibus e trens em formato XML. Aqui, veremos os dados de desempenho, que estão contidos em um conjunto de arquivos XML. Cada serviço de trem ou ônibus tem um arquivo diferente (como *Performance_MNR.xml* para a Ferrovia Metro-North) contendo dados mensais como uma série de registros XML semelhantes a este:

```xml
<INDICATOR>
<INDICATOR_SEQ>373889</INDICATOR_SEQ>
<PARENT_SEQ></PARENT_SEQ>
<AGENCY_NAME>Metro-North Railroad</AGENCY_NAME>
<INDICATOR_NAME>Escalator Availability</INDICATOR_NAME>
<DESCRIPTION>Percent of the time that escalators are operational
systemwide. The availability rate is based on physical observations performed
the morning of regular business days only. This is a new indicator the agency
began reporting in 2009.</DESCRIPTION>
<PERIOD_YEAR>2011</PERIOD_YEAR>
<PERIOD_MONTH>12</PERIOD_MONTH>
<CATEGORY>Service Indicators</CATEGORY>
<FREQUENCY>M</FREQUENCY>
<DESIRED_CHANGE>U</DESIRED_CHANGE>
<INDICATOR_UNIT>%</INDICATOR_UNIT>
<DECIMAL_PLACES>1</DECIMAL_PLACES>
<YTD_TARGET>97.00</YTD_TARGET>
<YTD_ACTUAL></YTD_ACTUAL>
<MONTHLY_TARGET>97.00</MONTHLY_TARGET>
<MONTHLY_ACTUAL></MONTHLY_ACTUAL>
</INDICATOR>
```

Usando `lxml.objectify`, analisamos o arquivo e obtemos uma referência ao nó raiz do arquivo XML com `getroot`:

In [27]:
from lxml import objectify

path = './datasets/Performance_MNR.xml'
with open(path) as f:
    parsed = objectify.parse(f)

root = parsed.getroot()

`root.INDICATOR` retorna um gerador que gera cada elemento XML `<INDICATOR>`. Para cada registro, podemos preencher um dicionário de nomes de tags (como `YTD_ACTUAL`) com valores de dados (excluindo algumas tags) executando o seguinte código:

In [28]:
data = []
skip_fields = ['PARENT_SEQ', 'INDICATOR_SEQ', 'DESIRED_CHANGE', 'DECIMAL_PLACES']

for elt in root.INDICATOR:
    el_data = {}
    for child in elt.getchildren():
        if child.tag in skip_fields:
            continue
        el_data[child.tag] = child.pyval
    data.append(el_data)

Por fim, converta esta lista de dicionários em um `DataFrame`:

In [29]:
perf = pd.DataFrame(data)

perf.head()

,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,INDICATOR_UNIT,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,1,Service Indicators,M,%,95.0,96.9,95.0,96.9
1,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,2,Service Indicators,M,%,95.0,96.0,95.0,95.0
2,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,3,Service Indicators,M,%,95.0,96.3,95.0,96.9
3,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,4,Service Indicators,M,%,95.0,96.8,95.0,98.3
4,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,5,Service Indicators,M,%,95.0,96.6,95.0,95.8

A função `pandas.read_xml` do Pandas transforma esse processo em uma expressão de uma linha:

In [30]:
perf_2 = pd.read_xml(path)

perf_2.head()

,INDICATOR_SEQ,PARENT_SEQ,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,DESIRED_CHANGE,INDICATOR_UNIT,DECIMAL_PLACES,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,1,Service Indicators,M,U,%,1,95.00,96.90,95.00,96.90
1,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,2,Service Indicators,M,U,%,1,95.00,96.00,95.00,95.00
2,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,3,Service Indicators,M,U,%,1,95.00,96.30,95.00,96.90
3,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,4,Service Indicators,M,U,%,1,95.00,96.80,95.00,98.30
4,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,5,Service Indicators,M,U,%,1,95.00,96.60,95.00,95.80

Para documentos XML mais complexos, consulte a docstring para [pandas.read_xml](https://pandas.pydata.org/docs/reference/api/pandas.read_xml.html), que descreve como fazer seleções e filtros para extrair uma tabela específica de interesse.

## 2. Formatos de Dados Binários

### 2.1. Visão Geral

Uma maneira simples de armazenar (ou serializar) dados em formato binário é usar o módulo `pickle` integrado do Python. Todos os objetos Pandas têm um método `to_pickle` que grava os dados no disco no formato `pickle`:

In [31]:
frame = pd.read_csv('./examples/ex1.csv')
frame

   1   2   3   4  hello
0  5   6   7   8  world
1  9  10  11  12    foo

In [32]:
frame.to_pickle('./examples/frame_pickle')

Arquivos Pickle geralmente são legíveis apenas em Python. Você pode ler qualquer objeto `"pickled"` armazenado em um arquivo usando o `pickle` integrado diretamente ou, ainda mais convenientemente, usando `pandas.read_pickle`:

In [33]:
pd.read_pickle('./examples/frame_pickle')

   1   2   3   4  hello
0  5   6   7   8  world
1  9  10  11  12    foo

O Pandas possui suporte integrado para vários outros formatos de dados binários de código aberto, como HDF5, ORC e ​​Apache Parquet. Por exemplo, se você instalar o pacote `pyarrow` (`uv pip install pyarrow`), poderá ler arquivos Parquet com pandas.`read_parquet`:

In [ ]:
fec = pd.read_parquet('./datasets/fec.parquet')

fec.head()

,cmte_id,cand_id,cand_nm,contbr_nm,contbr_city,contbr_st,contbr_zip,contbr_employer,contbr_occupation,contb_receipt_amt,contb_receipt_dt,receipt_desc,memo_cd,memo_text,form_tp,file_num
0,C00410118,P20002978,"Bachmann, Michelle","HARVEY, WILLIAM",MOBILE,AL,366010290,RETIRED,RETIRED,250.0,20-JUN-11,NaN,NaN,NaN,SA17A,736166
1,C00410118,P20002978,"Bachmann, Michelle","HARVEY, WILLIAM",MOBILE,AL,366010290,RETIRED,RETIRED,50.0,23-JUN-11,NaN,NaN,NaN,SA17A,736166
2,C00410118,P20002978,"Bachmann, Michelle","SMITH, LANIER",LANETT,AL,368633403,INFORMATION REQUESTED,INFORMATION REQUESTED,250.0,05-JUL-11,NaN,NaN,NaN,SA17A,749073
3,C00410118,P20002978,"Bachmann, Michelle","BLEVINS, DARONDA",PIGGOTT,AR,724548253,NONE,RETIRED,250.0,01-AUG-11,NaN,NaN,NaN,SA17A,749073
4,C00410118,P20002978,"Bachmann, Michelle","WARDENBURG, HAROLD",HOT SPRINGS NATION,AR,719016467,NONE,RETIRED,300.0,20-JUN-11,NaN,NaN,NaN,SA17A,736166

Veremos alguns exemplos de HDF5 mais adiante. Recomendo que você explore diferentes formatos de arquivo para ver o quão rápidos eles são e como funcionam bem para sua análise.

### 2.2. Lendo Arquivos do Microsoft Excel

O Pandas também suporta a leitura de dados tabulares armazenados em arquivos do Excel 2003 (e versões posteriores) usando a classe `pandas.ExcelFile` ou a função `pandas.read_excel`. Internamente, essas ferramentas usam os pacotes complementares `xlrd` e o `openpyxl` para ler arquivos XLS antigos e XLSX mais recentes respectivamente. Eles devem ser instalados separadamente do pandas usando `uv pip install xlrd` e `uv pip install openpyxl`.

Para usar `pandas.ExcelFile`, crie uma instância passando um caminho para um arquivo `xls` ou `xlsx`:

In [1]:
import pandas as pd

xlsx = pd.ExcelFile('./examples/ex1.xlsx')
xlsx

Este objeto pode mostrar a lista de nomes de planilhas disponíveis no arquivo:

In [2]:
xlsx.sheet_names

['Sheet1']

Os dados armazenados em uma planilha podem então ser lidos no `DataFrame` com `parse`:

In [3]:
xlsx.parse(sheet_name='Sheet1')

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

Esta tabela do Excel tem uma coluna de índice, então podemos indicá-la com o argumento `index_col`:

In [4]:
xlsx.parse(sheet_name='Sheet1', index_col=0)

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

Se você estiver lendo várias planilhas em um arquivo, será mais rápido criar o `pandas.ExcelFile`, mas você também pode simplesmente passar o nome do arquivo para `pandas.read_excel`:

In [5]:
frame = pd.read_excel('./examples/ex1.xlsx', sheet_name='Sheet1', index_col=0)
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

Para salvar dados do Pandas no formato Excel, você deve primeiro criar um `ExcelWriter` e, em seguida, gravar dados nele usando o método `to_excel` do objeto Pandas:

In [6]:
writer = pd.ExcelWriter('./examples/ex2.xlsx')

frame.to_excel(writer, sheet_name='Sheet1')
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

Você também pode passar um caminho de arquivo para `to_excel` e evitar o `ExcelWriter`:

In [7]:
frame.to_excel('./examples/ex2.xlsx')
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

### 2.3. Usando o Formato HDF5

HDF5 (*Hierarchical Data Format version 5*) é um formato de arquivo respeitado, destinado ao armazenamento de grandes quantidades de dados científicos em arrays. Está disponível como uma biblioteca `C` e possui interfaces disponíveis em muitas outras linguagens, incluindo `Java`, `Julia`, `MATLAB` e `Python`. O `"HDF"` em `HDF5` significa formato de dados hierárquico. Cada arquivo HDF5 pode armazenar vários conjuntos de dados e metadados de suporte. Comparado a formatos mais simples, o HDF5 suporta compactação instantânea com uma variedade de modos de compactação, permitindo que dados com padrões repetidos sejam armazenados com mais eficiência. O HDF5 pode ser uma boa opção para trabalhar com conjuntos de dados que não cabem na memória, pois você pode ler e gravar com eficiência pequenas seções de arrays muito maiores.

Para começar a usar o HDF5 e o pandas, você deve primeiro instalar o `PyTables` instalando o pacote `tables` com `uv pip tables`.

Embora seja possível acessar arquivos HDF5 diretamente usando as bibliotecas `PyTables` ou `h5py`, o Pandas oferece uma interface de alto nível que simplifica o armazenamento de objetos `Series` e `DataFrame`. A classe `HDFStore` funciona como um dicionário e lida com os detalhes de baixo nível:

In [1]:
import numpy as np
import pandas as pd

frame = pd.DataFrame({'a': np.random.standard_normal(100)})
store = pd.HDFStore('./examples/mydata.h5')

store['obj1'] = frame
store['obj1_col'] = frame['a']
store

<class 'pandas.HDFStore'>
File path: ./examples/mydata.h5

Os objetos contidos no arquivo HDF5 podem então ser recuperados com a mesma API semelhante a um dicionário:

In [2]:
store['obj1'].head()

          a
0 -1.064343
1  1.496008
2  0.795088
3  0.204772
4 -1.250348

O HDFStore suporta dois esquemas de armazenamento: `"fixed"` e `"table"` (o padrão é `"fixed"`). Este último é geralmente mais lento, mas suporta operações de consulta usando uma sintaxe especial:

In [3]:
store.put('obj2', frame, format='table')
store.select('obj2', where=['index >= 10 and index <= 15'])

           a
10 -0.552433
11 -0.060335
12 -1.034612
13  0.968766
14  0.503962
15 -0.287423

In [4]:
store.close()

O put é uma versão explícita do método `store["obj2"] = frame`, mas nos permite definir outras opções, como o formato de armazenamento.

A função `pandas.read_hdf` fornece um atalho para estas ferramentas:

In [5]:
frame.to_hdf(path_or_buf='./examples/mydata.h5', key='obj3', format='table')

In [6]:
pd.read_hdf('./examples/mydata.h5', 'obj3', where=['index < 5'])

          a
0 -1.064343
1  1.496008
2  0.795088
3  0.204772
4 -1.250348

Se desejar, você pode excluir o arquivo HDF5 que você criou, assim:

In [7]:
import os

os.remove('./examples/mydata.h5')

Se você trabalha com grandes quantidades de dados localmente, recomendo que explore o `PyTables` e o `h5py` para ver como eles podem atender às suas necessidades. Como muitos problemas de análise de dados são limitados por I/O (em vez de CPU), usar uma ferramenta como o HDF5 pode acelerar significativamente seus aplicativos.

## 3. Interagindo com APIs Web

Muitos sites têm APIs públicas que fornecem feeds de dados via JSON ou algum outro formato. Há várias maneiras de acessar essas APIs em Python; um método recomendado é o pacote `requests`, que pode ser instalado com `uv pip requests`.

Para encontrar os últimos 30 `"issues"` do Pandas no [GitHub](https://github.com/pandas-dev/pandas/issues), podemos fazer uma solicitação GET HTTP usando a biblioteca de solicitações de complementos:

In [8]:
import requests
import pandas as pd

url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp.raise_for_status()
resp

É uma boa prática sempre chamar raise_for_status após usar `requests.get` para verificar se há erros de HTTP.

O método `json` do objeto de resposta retornará um objeto Python contendo os dados JSON analisados ​​como um dicionário ou lista (dependendo do JSON retornado):

In [9]:
data = resp.json()

data[0]['title']

'BUG: Fix pd.concat producing invalid index for Int64Dtype with NAs (#62903)'

Como os resultados obtidos são baseados em dados em tempo real, o que você verá ao executar este código quase certamente será diferente.

Cada elemento em data é um dicionário contendo todos os dados encontrados em uma página de issue do GitHub (exceto os comentários). Podemos passar os dados diretamente para `pandas.DataFrame` e extrair os campos de interesse.

In [10]:
issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
issues

,number,title,labels,state
0,68919,BUG: Fix pd.concat producing invalid index for...,[],open
1,68918,"DOC: note encoding_errors=""strict"" is the defa...",[],open
2,68916,[backport 3.0.x] BUG: full-slice setitem into ...,[],open
3,68915,Refactor write_version_info to return version ...,[],open
4,68866,Bump pypa/cibuildwheel from 4.2.0 to 4.2.1,"[{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...",open
5,68822,[backport 3.0.x] BUG: read_csv leaked the stri...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
6,68821,Draft/split test pandas array,[],open
7,68820,BUG: fix setting with bool column mask into 1-...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
8,68813,BUG: fix setting single column with nullable r...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
9,68716,BUG: BlockManager dtype caches could be left p...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
10,68706,BUG/DEPR: low_memory keyword in read_csv,"[{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...",open
11,68705,DEPR: cache_dates in read_csv,"[{'id': 47229171, 'node_id': 'MDU6TGFiZWw0NzIy...",open
12,68703,API: select_dtypes,"[{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...",open
13,68702,BUG: preserve line breaks in ODS cells in to_e...,"[{'id': 11527065930, 'node_id': 'LA_kwDOAA0YD8...",open
14,68700,DEPR: warn on ambiguous .loc MultiIndex tuple ...,[],open
15,68699,BUG: preserve dtype for empty DataFrame min/ma...,"[{'id': 11527065930, 'node_id': 'LA_kwDOAA0YD8...",open
16,68689,BUG: read_csv c engine ignored na_values on a ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
17,68643,BUG: iloc setitem wrote the wrong cells on a C...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
18,68641,BUG: DataFrame axis=1 reductions accumulated i...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
19,68638,BUG: ArrowExtensionArray silently truncated a ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
20,68637,BUG: ops with an iterator raised TypeError ins...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
21,68609,BUG avoid parallel read_csv with converters,"[{'id': 11527065930, 'node_id': 'LA_kwDOAA0YD8...",open
22,68593,BUG: Fix to_xml() export for bool dtype,"[{'id': 11527065930, 'node_id': 'LA_kwDOAA0YD8...",open
23,68592,TST: pin non-unitary anchored resample offset ...,"[{'id': 11527065930, 'node_id': 'LA_kwDOAA0YD8...",open
24,68587,BUG: read_csv silently wrapped out-of-range in...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
25,68584,"BUG: read_json(orient=""table"") could not read ...","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
26,68563,BUG: Index.replace raised instead of widening ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
27,68524,BUG: the logical ufuncs were not rejected agai...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
28,68521,BUG: iloc/loc setitem broadcast a 1-D value do...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
29,68510,DEPR: precise_float and double_precision in JS...,"[{'id': 49379259, 'node_id': 'MDU6TGFiZWw0OTM3...",open

Com um pouco de esforço, você pode criar algumas interfaces de alto nível para APIs da web comuns que retornam objetos `DataFrame` para uma análise mais conveniente.

## 4. Interagindo com Bancos de Dados

Em um ambiente empresarial, muitos dados podem não ser armazenados em arquivos de texto ou Excel. Bancos de dados relacionais baseados em SQL (como SQL Server, PostgreSQL e MySQL) são amplamente utilizados, e muitos bancos de dados alternativos se tornaram bastante populares. A escolha do banco de dados geralmente depende das necessidades de desempenho, integridade dos dados e escalabilidade de uma aplicação.

O Pandas possui algumas funções para simplificar o carregamento dos resultados de uma consulta SQL em um `DataFrame`. Como exemplo, criaremos um banco de dados `SQLite3` usando o driver `sqlite3` integrado do Python:

In [11]:
import sqlite3

query ="""
CREATE TABLE test
(a VARCHAR(20), b VARCHAR(20),
c REAL, d INTEGER
);"""

In [12]:
con = sqlite3.connect('mydata.sqlite')

In [13]:
con.execute(query)

In [14]:
con.commit()

Em seguida, insira algumas linhas de dados:

In [15]:
data = [("Atlanta", "Georgia", 1.25, 6), 
        ("Tallahassee", "Florida", 2.6, 3), 
        ("Sacramento", "California", 1.7, 5)]

stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"

con.executemany(stmt, data)

In [16]:
con.commit()

A maioria dos drivers Python SQL retorna uma lista de tuplas ao selecionar dados de uma tabela:

In [17]:
cursor = con.execute("SELECT * FROM test")

In [18]:
rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

Você pode passar a lista de tuplas para o construtor `DataFrame`, mas também precisa dos nomes das colunas, contidos no atributo description do cursor. Observe que, para o `SQLite3`, a descrição do cursor fornece apenas os nomes das colunas (os outros campos, que fazem parte da especificação da API de Banco de Dados do Python, são `None`), mas para alguns outros drivers de banco de dados, mais informações sobre as colunas são fornecidas:

In [19]:
cursor.description

(('a', None, None, None, None, None, None),
 ('b', None, None, None, None, None, None),
 ('c', None, None, None, None, None, None),
 ('d', None, None, None, None, None, None))

In [20]:
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

Está é uma `"confusão"` que você vai preferir não repetir sempre que consultar o banco de dados. O projeto `SQLAlchemy` é um popular kit de ferramentas SQL em Python que abstrai muitas das diferenças comuns entre bancos de dados SQL. O Pandas tem uma função `read_sql` que permite ler dados facilmente de uma conexão `SQLAlchemy` geral. Você pode instalar o `SQLAlchemy` com `uv pip install sqlalchemy`.

In [1]:
import sqlalchemy as sqla

db = sqla.create_engine('sqlite:///mydata.sqlite')

In [ ]:
pd.read_sql("SELECT * FROM test", db)

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

## 5. Exercícios

In [4]:
# Esta célula informa ao Jupyter para fornecer informações detalhadas de depuração
# quando ocorrer um erro de execução. Execute-o antes de trabalhar nos exercícios.

%xmode Verbose

Exception reporting mode: Verbose

### 5.1. Exercício

Leia o arquivo `examples/ex1.csv` com Pandas e mostre as 5 primeiras linhas.
- Dica: use `pandas.read_csv`

In [5]:
ex1 = pd.read_csv('./examples/ex1.csv')
ex1.head()

   1   2   3   4  hello
0  5   6   7   8  world
1  9  10  11  12    foo

### 5.2. Exercício

O arquivo `examples/ex1.csv` não possui header. Carregue-o atribuindo nomes de colunas `["a","b","c","d","message"]` e use `"message"` como índice.
- Dica: use `read_csv(header=None, names=..., index_col=...)`

In [6]:
columns = ['a', 'b', 'c', 'd', 'message']

ex2 = pd.read_csv('./examples/ex1.csv', header=None, names=columns, index_col='message')
ex2

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

### 5.3. Exercício

Leia `examples/ex3.txt` usando um separador baseado em expressão regular (espacos múltiplos).
- Dica: use `read_csv(sep=r"\s+")`

In [7]:
ex3 = pd.read_csv('./examples/ex3.txt', sep=r'\s+')
ex3

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

### 5.4. Exercício

Carregue `examples/ex5.csv` tratando `"NULL"` e `"NA"` como valores ausentes, mas desabilitando os `NA`s padrão. Em seguida, mostre quais células são `NaN`.
- Dica: use `read_csv(keep_default_na=False, na_values=...)`

In [ ]:
ex5 = pd.read_csv('./examples/ex5.csv', keep_default_na=False, na_values=['NULL', 'NA', ''])

positions = list(zip( *np.where(ex5.isna()) ))
print(positions)

positions_named = [(i, ex5.columns[j]) for i, j in zip( *np.where(ex5.isna()) )]
print(positions_named)

[(np.int64(0), np.int64(5)), (np.int64(1), np.int64(3))]
[(np.int64(0), 'message'), (np.int64(1), 'c')]

### 5.5. Exercício

Use `chunksize` para ler `examples/ex6.csv` em pedaços de `500` linhas e compute a contagem agregada dos 10 valores mais frequentes da coluna `"key"`.
- Dica: use `read_csv(chunksize=...)`, `Series.add` e `value_counts`

In [2]:
chunker = pd.read_csv('./examples/ex6.csv', chunksize=500)
tot = pd.Series([], dtype='int64')

for piece in chunker:
    tot = tot.add(piece['key'].value_counts(), fill_value=0)

tot = tot.sort_values(ascending=False)
tot[:5]

key
E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
dtype: float64

### 5.6. Exercício

Leia `examples/example.json` (ou outro JSON do diretório) e remova a coluna `b` do `DataFrame` e, em seguida, salve o `DataFrame` alterado em `examples/example_modified.json`.
- Dica: use `read_json(...)` e `to_json(...)`

In [ ]:
df = pd.read_json('./examples/example.json')
df.drop(columns='b', inplace=True)

df.to_json(sys.stdout, orient='records')

[{"a":1,"c":3},{"a":4,"c":6},{"a":7,"c":9}]

### 5.7. Exercício

Faça uma requisição à API pública de issues do GitHub para o repositório `pandas-dev/pandas`, converta a resposta JSON em `DataFrame` com colunas `["number","title","state","labels"]`, e salve os resultados em `examples/issues.parquet` (use `pyarrow`).
- Dica: use `requests`, `resp.json()`, `DataFrame` e `to_parquet`

In [5]:
import requests

url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp.raise_for_status()
resp

In [6]:
data = resp.json()
data

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68960',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68960/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68960/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68960/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/68960',
  'id': 5481978690,
  'node_id': 'PR_kwDOAA0YD88AAAABD27VLQ',
  'number': 68960,
  'title': 'Handle re.error in regex compilation and fix return',
  'user': {'login': 'MaddipatlaChetan24',
   'id': 193315028,
   'node_id': 'U_kgDOC4XA1A',
   'avatar_url': 'https://avatars.githubusercontent.com/u/193315028?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/MaddipatlaChetan24',
   'html_url': 'https://github.com/MaddipatlaChetan24',
   'followers_url': 'https://api.github.com/users/MaddipatlaChetan24/followers',
   'following_url': 'https://api.github.com/users/MaddipatlaChetan24/following{/other_user}',
   'gists_url': 'https://api.github.com/users/MaddipatlaChetan24/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/MaddipatlaChetan24/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/MaddipatlaChetan24/subscriptions',
   'organizations_url': 'https://api.github.com/users/MaddipatlaChetan24/orgs',
   'repos_url': 'https://api.github.com/users/MaddipatlaChetan24/repos',
   'events_url': 'https://api.github.com/users/MaddipatlaChetan24/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/MaddipatlaChetan24/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2026-09-17T02:12:55Z',
  'updated_at': '2026-09-17T02:13:15Z',
  'closed_at': None,
  'assignee': None,
  'author_association': 'NONE',
  'issue_field_values': [],
  'type': None,
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/68960',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/68960',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/68960.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/68960.patch',
   'merged_at': None},
  'body': 'Fixes `is_re_compilable` silently crashing on syntactically invalid regex strings in `pandas/core/dtypes/inference.py`.\r\n\r\n## Description\r\n\r\n`is_re_compilable`\'s docstring explicitly states: "attempts to compile\r\n`obj` as a regular expression using `re.compile` and returns whether\r\nthe compilation succeeds." The implementation only caught `TypeError`\r\n(wrong argument type, e.g. passing an int), not `re.error` (raised when\r\n`obj` is a string but not a syntactically valid regex pattern). So a\r\ncall like `is_re_compilable("(unclosed")` raised an uncaught `re.error`\r\ninstead of returning `False`, contradicting the documented contract for\r\nexactly the use case the function name and docstring advertise —\r\nchecking whether an ordinary, user-supplied string can be compiled.\r\n\r\nReproduced directly:\r\n\r\nis_re_compilable("(unclosed")\r\nre.error: missing ), unterminated subpattern at position 0 # before fix\r\nFalse # after fix\r\n\r\nVerified the fix against four cases (valid regex, wrong type, and two\r\nsyntactically-invalid-but-string inputs) — all now return the correct\r\nboolean instead of raising.\r\n\r\nFix: `except TypeError:` → `except (TypeError, re.error):`. No other\r\nchanges.\r\n\r\n- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)\r\n- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n- [x] I have reviewed and followed all the [contribution guidelines](https://pandas.pydata.org/docs/dev/development/contributing.html)\r\n\r\nCheck exactly one of the following, per the [automated contributions policy](https://pandas.pydata.org/docs/dev/development/contributing.html#automated-contributions-policy):\r\n\r\n- [x] I did **not** use AI to develop this pull request.',
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68960/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68960/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68959',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68959/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68959/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68959/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/68959',
  'id': 5481619113,
  'node_id': 'PR_kwDOAA0YD88AAAABD2pOFg',
  'number': 68959,
  'title': 'API: Add reduction methods to base `ExtensionArray`',
  'user': {'login': 'Julian-Harbeck',
   'id': 159573770,
   'node_id': 'U_kgDOCYLnCg',
   'avatar_url': 'https://avatars.githubusercontent.com/u/159573770?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Julian-Harbeck',
   'html_url': 'https://github.com/Julian-Harbeck',
   'followers_url': 'https://api.github.com/users/Julian-Harbeck/followers',
   'following_url': 'https://api.github.com/users/Julian-Harbeck/following{/other_user}',
   'gists_url': 'https://api.github.com/users/Julian-Harbeck/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/Julian-Harbeck/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/Julian-Harbeck/subscriptions',
   'organizations_url': 'https://api.github.com/users/Julian-Harbeck/orgs',
   'repos_url': 'https://api.github.com/users/Julian-Harbeck/repos',
   'events_url': 'https://api.github.com/users/Julian-Harbeck/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/Julian-Harbeck/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [{'id': 11527065930,
    'node_id': 'LA_kwDOAA0YD88AAAACrxERSg',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Awaiting%20Review',
    'name': 'Awaiting Review',
    'color': '0E8A16',
    'default': False,
    'description': "PR in the maintainers' court; exempt from staleness",
    'archived_at': None,
    'archived_by': None}],
  'state': 'open',
  'locked': False,
  'assignees': [],
  'milestone': None,
  'comments': 1,
  'created_at': '2026-09-17T01:14:19Z',
  'updated_at': '2026-09-17T01:42:09Z',
  'closed_at': None,
  'assignee': None,
  'author_association': 'CONTRIBUTOR',
  'issue_field_values': [],
  'type': None,
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/68959',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/68959',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/68959.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/68959.patch',
   'merged_at': None},
  'body': "- [x] closes #67928 (at least partly, requires follow-up for removing `_reduce`)\r\n- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n- [x] I have reviewed and followed all the [contribution guidelines](https://pandas.pydata.org/docs/dev/development/contributing.html)\r\n\r\nCheck exactly one of the following, per the [automated contributions policy](https://pandas.pydata.org/docs/dev/development/contributing.html#automated-contributions-policy):\r\n\r\n- [x] I did **not** use AI to develop this pull request.\r\n- [ ] I used AI to develop this pull request. I prompted it to follow `AGENTS.md`, I have reviewed and understood every change, and I have described above how I used it and exactly which tool, model version, and effort setting — e.g. `claude opus 4.8 (xhigh)`, not just `claude`.\r\n\r\nFollow-up to #63512 to add the reduction methods also to the base `ExtensionArray` class to specify desired API for external EA developers. As discussed in the issue #67928 as a first step this PR will just add the reduction methods, but they are not yet used. This fixes the issue of external EA developers being confronted with a failing `BaseReduceTests::test_reduce_array`.\r\n\r\nAs all EAs now specify the reduction methods I removed the check if they exist from the base `_reduce` method, the `TypeError` error message is now raised in the new methods.\r\n\r\nIt should be discussed if the new API is finalized or if it should include different kwargs. At the moment `_reduce` also specifies `keepdims`, @rhshadrach is there a reason why you left it out of the method signature in the original PR? The `nv.validate_stat_ddof_func` checks that it is `False` if passed in kwargs if I understand it correctly? On the other hand the new methods have the new kwargs `min_count` with default `0` and `axis` with default `0`. Also matching with the existing implementation of our internal EAs the methods `sem`, `std` and `var` specify `ddof` with default `1` (xref #68391).\r\n\r\n\r\nOther possible discussion points:\r\n1. Should the functions raise `TypeError` as before or rather `NotImplementedError` as for example `_accumulate` does?\r\n2. I opted for alphanumerical sorting of the methods in the base `ExtensionArray` class and placed them after the `_reduce` method, our internal arrays are not consistend on the order.\r\n3. There is already a whatsnew from @rhshadrach's PR, as that is unreleased I would just change that one to include all EAs, but without default forwarding to `_reduce`.",
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68959/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68959/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68947',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68947/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68947/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68947/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/68947',
  'id': 5481118524,
  'node_id': 'PR_kwDOAA0YD88AAAABD2QTTQ',
  'number': 68947,
  'title': 'BUG: read_csv(engine="python") applied skipfooter by row, not by line (GH#36827)',
  'user': {'login': 'jbrockmendel',
   'id': 8078968,
   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jbrockmendel',
   'html_url': 'https://github.com/jbrockmendel',
   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
   'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',
   'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',
   'repos_url': 'https://api.github.com/users/jbrockmendel/repos',
   'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None,
    'archived_at': None,
    'archived_by': None},
   {'id': 47229171,
    'node_id': 'MDU6TGFiZWw0NzIyOTE3MQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20CSV',
    'name': 'IO CSV',
    'color': '5319e7',
    'default': False,
    'description': 'read_csv, to_csv',
    'archived_at': None,
    'archived_by': None},
   {'id': 49254273,
    'node_id': 'MDU6TGFiZWw0OTI1NDI3Mw==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20Excel',
    'name': 'IO Excel',
    'color': 'bfe5bf',
    'default': False,
    'description': 'read_excel, to_excel',
    'archived_at': None,
    'archived_by': None}],
  'state': 'open',
  'locked': False,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2026-09-16T23:49:48Z',
  'updated_at': '2026-09-16T23:49:49Z',
  'closed_at': None,
  'assignee': None,
  'author_association': 'MEMBER',
  'issue_field_values': [],
  'type': None,
  'active_lock_reason': None,
  'draft': True,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/68947',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/68947',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/68947.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/68947.patch',
   'merged_at': None},
  'body': 'closes #36827\n\nThe python engine applied `skipfooter` as a slice on the assembled row list. That list omits every line the parser had already discarded — `skiprows` lines, and blank and comment lines consumed while inferring the header — so the trim cut too deep whenever the cutoff fell inside the header-inference region. The reported case came back as an empty `DataFrame`.\n\nThe parser now records the line number of each line pushed onto its pushback buffer and applies the cutoff by line number, which is what the documented "number of lines at bottom of file to skip" already promised. `read_fwf` and `read_excel` reach the same code and are fixed with it.\n\nFixing the cutoff also required `_next_line` to stop advancing its line counter past EOF: its `skiprows` loop incremented before consuming, so on an exhausted file the count overshot and `skipfooter` trimmed nothing. Its two sibling skip loops already guarded this.\n\nVerified against an oracle that physically deletes the last `k` lines of the file and reads it with `skipfooter=0`, swept over `skipfooter` magnitude, `skiprows` (int/list/callable), `header` (`None`/`0`/`n`/`[0, 1]`/`names`), `index_col`, `skip_blank_lines`, `comment`, all three separator paths (single-char, regex, `sep=None` sniffing), line endings, and the list-backed `read_excel` path: no divergence introduced, several hundred cases fixed.\n\nRelated pre-existing gaps found along the way and deliberately left alone: `on_bad_lines="skip"` lines are still not counted towards `skipfooter` (the same undercount drifts `skiprows` after a bad line), `read_fwf` infers colspecs from lines `skipfooter` is about to discard, and `skipfooter` can still be reached with an explicit row count via `reader.read(n)`/`get_chunk(n)` although it is rejected at construction. That last one is why the new trim only applies on a read to EOF — on that path the old positional behavior is preserved unchanged.\n\nAI disclosure: drafted with Claude Code (`claude opus 5 (high)`), which wrote the fix and tests and ran the differential sweeps; reviewed by me before opening.',
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68947/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68947/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68946',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68946/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68946/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68946/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/68946',
  'id': 5481115223,
  'node_id': 'PR_kwDOAA0YD88AAAABD2QIug',
  'number': 68946,
  'title': 'BUG: python-engine read_csv ignored on_bad_lines with index_col=False (GH#49279)',
  'user': {'login': 'jbrockmendel',
   'id': 8078968,
   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jbrockmendel',
   'html_url': 'https://github.com/jbrockmendel',
   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
   'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',
   'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',
   'repos_url': 'https://api.github.com/users/jbrockmendel/repos',
   'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None,
    'archived_at': None,
    'archived_by': None},
   {'id': 47229171,
    'node_id': 'MDU6TGFiZWw0NzIyOTE3MQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20CSV',
    'name': 'IO CSV',
    'color': '5319e7',
    'default': False,
    'description': 'read_csv, to_csv',
    'archived_at': None,
    'archived_by': None}],
  'state': 'open',
  'locked': False,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2026-09-16T23:49:13Z',
  'updated_at': '2026-09-16T23:49:14Z',
  'closed_at': None,
  'assignee': None,
  'author_association': 'MEMBER',
  'issue_field_values': [],
  'type': None,
  'active_lock_reason': None,
  'draft': True,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/68946',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/68946',

In [7]:
issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
issues

,number,title,labels,state
0,68960,Handle re.error in regex compilation and fix r...,[],open
1,68959,API: Add reduction methods to base `ExtensionA...,"[{'id': 11527065930, 'node_id': 'LA_kwDOAA0YD8...",open
2,68947,"BUG: read_csv(engine=""python"") applied skipfoo...","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
3,68946,BUG: python-engine read_csv ignored on_bad_lin...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
4,68945,BUG: to_datetime returned category dtype for c...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
5,68943,BUG: out-of-range scalar setitem into a numpy-...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
6,68942,BUG: Series.shift ignored the suffix argument ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
7,68941,BUG: read_csv/read_table ignoring an explicit ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
8,68940,BUG: read_csv losing integer precision with a ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
9,68939,DEPR: Timestamp.timestamp treating tz-naive as...,"[{'id': 60458168, 'node_id': 'MDU6TGFiZWw2MDQ1...",open
10,68938,"BUG: read_csv with engine=""pyarrow"" ignored sk...","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
11,68937,DEPR: rename Groupby classes to GroupBy (GH#49...,"[{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...",open
12,68936,"BUG: read_csv raising for sep=""\n"" with a cust...","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
13,68935,"DOC: Broken links in stable ""Debugging C exten...","[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open
14,68934,BUG: Rolling/Expanding skew and kurt wrong on ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
15,68933,BUG: DataFrame.agg with a list of funcs rounds...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
16,68932,BUG infer StringArray ufunc result dtype,"[{'id': 11527065930, 'node_id': 'LA_kwDOAA0YD8...",open
17,68931,BUG: groupby(observed=False) with dropped NA k...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
18,68930,BUG: DataFrame.isetitem with an out-of-order l...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
19,68929,BUG: DataFrame.clip with an extension-dtype ar...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
20,68928,BUG: Series.replace silently discarded a regex...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
21,68927,BUG: tm.assert_* raised TypeError for zerodim ...,[],open
22,68926,BUG: astype/construction from float to datetim...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
23,68925,BUG: melt returned object dtype for interval c...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
24,68923,BUG preserve missing values in MultiIndex leve...,"[{'id': 11527065930, 'node_id': 'LA_kwDOAA0YD8...",open
25,68922,BUG: MultiIndex reports the wrong problem for ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
26,68921,BUG: comma read as a decimal separator silentl...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
27,68920,BUG: to_datetime parsed a time-only string wit...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
28,68919,BUG: Fix pd.concat producing invalid index for...,"[{'id': 11527065930, 'node_id': 'LA_kwDOAA0YD8...",open
29,68918,"DOC: note encoding_errors=""strict"" is the defa...",[],open

In [8]:
issues.to_parquet('./examples/issues.parquet')