# Módulo 02: Introdução às Bibliotecas NumPy e Pandas
>
> [Universidade Federal do Ceará (UFC)](https://www.ufc.br/)\
> [Departamento de Computação (DC)](https://dc.ufc.br/pt/)\
> [Capacitação Técnica e Empreendedora em IA (CTE-IA)](https://www.cteia.dc.ufc.br/)\
> Fase I: Capacitação Teórica de IA\
> Disciplina: Programação para Ciência de Dados (60h)\
> Professor: [Lincoln S. Rocha](http://lattes.cnpq.br/0656977742590515)\
> E-mail: <lincoln@dc.ufc.br>
>

O principal objetivo deste módulo é apresentar os conceitos fundamentais das bibliotécas [NumPy](https://numpy.org/) e [Pandas](https://pandas.pydata.org/). Este módulo cobrirá o seguinte conteúdo:

1. A Biblioteca NumPy
2. A Biblioteca Pandas
3. Estudo de Caso

## 1. A Biblioteca NumPy

 NumPy (Numerical Python) é uma biblioteca Python de código aberto amplamente utilizada em ciência e engenharia. A biblioteca NumPy contém estruturas de dados de matriz multidimensional, como o `ndarray` homogêneo e N-dimensional, e uma grande biblioteca de funções que operam eficientemente nessas estruturas de dados.

### 1.1. Instalando NumPy

O método recomendado para instalar o NumPy depende do seu fluxo de trabalho preferido. Abaixo, dividimos os métodos de instalação nas seguintes categorias:

- Baseado em projeto (ex.: uv, pixi) (recomendado para novos usuários)
- Baseado em ambiente (ex.: pip, conda) (o fluxo de trabalho tradicional)
- Gerenciadores de pacotes do sistema (não recomendado para a maioria dos usuários)
- Compilação a partir do código-fonte (para usuários avançados e fins de desenvolvimento)

Escolha o método que melhor se adapta às suas necessidades. Se não tiver certeza, comece com o método baseado em ambiente usando `conda` ou `pip`. No nosso curso usaremos a instalação via `pip`:

In [1]:
pip install numpy

Requirement already satisfied: numpy in ./.venv/lib/python3.12/site-packages (2.3.4)

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

Se você já possuir o NumPy instalado, podes atualizá-lo da seguinte forma:

In [2]:
pip install --upgrade numpy

Requirement already satisfied: numpy in ./.venv/lib/python3.12/site-packages (2.3.4)

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

Após instalar o NumPy, verifique a instalação executando o seguinte em um shell ou script Python:

In [ ]:
import numpy as np
print(np.__version__)

### 1.2. O que é um *array*?

Em programação de computadores, um array é uma estrutura para armazenar e recuperar dados. Frequentemente falamos de um array como se fosse uma grade no
espaço, em que cada célula armazena um elemento dos dados. Por exemplo, se cada elemento dos dados fosse um número, poderíamos visualizar um array
"unidimensional" como uma lista:

| 1 | 5 | 2 | 0 |
|:-:|:-:|:-:|:-:|

Um array bidimensional seria como uma tabela:

| 1 | 5 | 2 | 0 |
|:-:|:-:|:-:|:-:|
| **8** | **3** | **6** | **1** |
| **1** | **7** | **2** | **9** |



Um array tridimensional seria como um conjunto de tabelas, talvez empilhadas como se estivessem impressas em páginas separadas. No NumPy, essa ideia é
generalizada para um número arbitrário de dimensões e, portanto, a classe fundamental do array é chamada `ndarray`: ela representa um "array n-dimensional".

A maioria dos arrays NumPy tem algumas restrições. Por exemplo:

- Todos os elementos do array devem ser do mesmo tipo de dados.

- Uma vez criado, o tamanho total do array não pode ser alterado.

- O formato deve ser **"retangular"**, não **"irregular"**; por exemplo, cada linha de um array bidimensional deve ter o mesmo número de colunas.

Quando essas condições são atendidas, o NumPy explora essas características para tornar o array mais rápido, mais eficiente em termos de memória e mais conveniente de usar do que estruturas de dados menos restritivas.

No restante deste documento, usaremos a palavra "array" para nos referirmos a uma instância de `ndarray`.

### 1.3. O que é NumPy?

NumPy é o pacote fundamental para computação científica em Python. É uma biblioteca Python que fornece um objeto array multidimensional, vários objetos derivados (como arrays e matrizes mascarados) e uma variedade de rotinas para operações rápidas em arrays, incluindo operações matemáticas, lógicas, manipulação de formas, ordenação, seleção, I/O, transformadas discretas de Fourier, álgebra linear básica, operações estatísticas básicas, simulação aleatória e muito mais.

No núcleo do pacote NumPy, está o objeto `ndarray`. Ele encapsula arrays n-dimensionais de tipos de dados homogêneos, com muitas operações sendo realizadas em código compilado para desempenho. Existem várias diferenças importantes entre arrays NumPy e as sequências padrão do Python:

- Arrays NumPy têm um tamanho fixo na criação, ao contrário das listas do Python (que podem crescer dinamicamente). Alterar o tamanho de um ndarray criará um novo array e excluirá o original.

- Os elementos em um array NumPy devem ser todos do mesmo tipo de dados e, portanto, terão o mesmo tamanho na memória. A exceção: é possível ter arrays de objetos (Python, incluindo NumPy), permitindo assim arrays com elementos de tamanhos diferentes.

- Arrays NumPy facilitam operações matemáticas avançadas e outros tipos de operações em grandes quantidades de dados. Normalmente, essas operações são executadas de forma mais eficiente e com menos código do que seria possível usando as sequências integradas do Python.

- Um número crescente de pacotes científicos e matemáticos baseados em Python estão usando arrays NumPy; Embora normalmente suportem entrada de sequência em Python, eles convertem essa entrada em matrizes NumPy antes do processamento e, frequentemente, geram matrizes NumPy. Em outras palavras, para usar com eficiência grande parte (talvez até a maioria) dos softwares científicos/matemáticos atuais baseados em Python, apenas saber como usar os tipos de sequência integrados do Python não é suficiente – também é preciso saber como usar matrizes NumPy.

Os pontos sobre tamanho e velocidade de sequência são particularmente importantes na computação científica. Como exemplo simples, considere o caso da multiplicação de cada elemento em uma sequência unidimensional pelo elemento correspondente em outra sequência de mesmo comprimento. Se os dados forem armazenados em duas listas Python, `a` e `b`, poderíamos iterar sobre cada elemento:

```python
c = []
for i in range(len(a)):
    c.append(a[i]*b[i])
```

Isso produz a resposta correta, mas se `a` e `b` contiverem milhões de números cada, pagaremos o preço pelas ineficiências do loop em Python. Poderíamos realizar a mesma tarefa muito mais rapidamente em `C` escrevendo (para maior clareza, negligenciamos declarações e inicializações de variáveis, alocação de memória, etc.):

```c
for (i = 0; i < rows; i++) {
  c[i] = a[i]*b[i];
}
```

Isso economiza toda a sobrecarga envolvida na interpretação do código Python e na manipulação de objetos Python, mas às custas dos benefícios obtidos com a codificação em Python. Além disso, o trabalho de codificação necessário aumenta com a dimensionalidade dos nossos dados. No caso de um array 2D, por exemplo, o código `C` (abreviado como antes) se expande para:

```c
for (i = 0; i < rows; i++) {
  for (j = 0; j < columns; j++) {
    c[i][j] = a[i][j]*b[i][j];
  }
}
```

O NumPy nos oferece o melhor dos dois mundos: operações elemento a elemento são o "modo padrão" quando se trata de um `ndarray`, mas a operação elemento a elemento é executada rapidamente por código `C` pré-compilado. No NumPy

```python
c = a * b
```

faz o que os exemplos anteriores fazem, em velocidades próximas à de `C`, mas com a simplicidade de código que esperamos de algo baseado em Python. De fato, a linguagem NumPy é ainda mais simples! Este último exemplo ilustra dois dos recursos do NumPy que são a base de grande parte de seu poder: **vetorização** e **transmissão**.

### 1.3. Por que usar NumPy?

Listas em Python são excelentes contêineres de uso geral. Elas podem ser "heterogêneas", o que significa que podem conter elementos de diversos tipos, e são bastante rápidas quando usadas para executar operações individuais em um pequeno número de elementos.

Dependendo das características dos dados e dos tipos de operações que precisam ser executadas, outros contêineres podem ser mais apropriados; explorando essas características, podemos melhorar a velocidade, reduzir o consumo de memória e oferecer uma sintaxe de alto nível para executar uma variedade de tarefas comuns de processamento. O NumPy se destaca quando há grandes quantidades de dados "homogêneos" (do mesmo tipo) a serem processados ​​na CPU.

### 1.4. Por que o NumPy é rápido?

A *vetorização* descreve a ausência de qualquer loop, indexação, etc. explícito no código – essas coisas acontecem, é claro, apenas `"nos bastidores"` em código `C` otimizado e pré-compilado. O código vetorizado tem muitas vantagens, entre elas:

- O código vetorizado é mais conciso e fácil de ler

- Menos linhas de código geralmente significam menos bugs

- O código se assemelha mais à notação matemática padrão (tornando mais fácil, normalmente, codificar corretamente construções matemáticas)

- A vetorização resulta em um código mais "Pythônico". Sem a vetorização, nosso código estaria repleto de loops `for` ineficientes e difíceis de ler.

A *transmissão* é o termo usado para descrever o comportamento implícito elemento a elemento das operações; de modo geral, no NumPy todas as operações, não apenas as aritméticas, mas também as lógicas, bit a bit, funcionais, etc., se comportam dessa forma implícita elemento a elemento, ou seja, elas transmitem. Além disso, no exemplo da seção passada, `a` e `b` podem ser matrizes multidimensionais do mesmo formato, ou um escalar e uma matriz, ou até mesmo duas matrizes com formatos diferentes, desde que a matriz menor seja `"expansível"` para o formato da maior de tal forma que a transmissão resultante seja inequívoca.

### 1.5. Fundamentos de Arrays no NumPy

O NumPy oferece suporte total a uma abordagem orientada a objetos, começando, mais uma vez, com `ndarray`. Por exemplo, `ndarray` é uma classe que possui diversos métodos e atributos. Muitos de seus métodos são espelhados por funções no `namespace` NumPy mais externo, permitindo ao programador codificar em qualquer paradigma de sua preferência. Essa flexibilidade permitiu que o dialeto de arrays NumPy e a classe `ndarray` NumPy se tornassem a linguagem de fato para intercâmbio de dados multidimensionais usada em Python.

O objeto principal do NumPy é o array multidimensional homogêneo. É uma tabela de elementos (geralmente números), todos do mesmo tipo, indexados por uma tupla de inteiros não negativos. No NumPy, as dimensões são chamadas de **eixos**.

Por exemplo, o array para as coordenadas de um ponto no espaço tridimensional, `[1, 2, 1]`, possui um eixo. Esse eixo possui 3 elementos, portanto, dizemos que ele tem comprimento 3. No exemplo abaixo, o array possui 2 eixos. O primeiro eixo tem comprimento 2, o segundo eixo tem comprimento 3.

In [1]:
[[1., 0.],
 [0., 1., 2.]]

[[1.0, 0.0], [0.0, 1.0, 2.0]]

Após instalar o NumPy, ele pode ser importado para código Python como:

In [2]:
import numpy as np

Uma maneira de inicializar um array é usar uma sequência Python, como uma lista. Por exemplo:

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

Os elementos de um array podem ser acessados ​​de várias maneiras. Por exemplo, podemos acessar um elemento individual desse array como acessaríamos um elemento da lista original: usando o índice inteiro do elemento entre colchetes.

In [4]:
print(a[0])

1

Assim como a lista original, a matriz é mutável.

In [5]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

Assim como na lista original, a notação de fatias do Python pode ser usada para indexação.

In [6]:
a[:3]

array([10,  2,  3])

Uma grande diferença é que a indexação por fatias de uma lista copia os elementos para uma nova lista, mas fatiar um array retorna uma *visualização*: um objeto que se refere aos dados do array original. O array original pode ser modificado usando a visualização.

In [8]:
b = a[3:]
print(b)
b[0] = 40
print(a)
print(b)

[40  5  6]
[10  2  3 40  5  6]
[40  5  6]

Matrizes bidimensionais e de dimensões superiores podem ser inicializadas a partir de sequências Python aninhadas:

In [16]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Como dito anteriormente, no NumPy, a dimensão de um array é às vezes chamada de `"eixo"`. Essa terminologia pode ser útil para diferenciar a dimensionalidade de um array da dimensionalidade dos dados representados pelo array. Por exemplo, o array `a` poderia representar três pontos, cada um dentro de um espaço quadridimensional, mas a possui apenas dois `"eixos"`.

Outra diferença entre um array e uma lista de listas é que um elemento do array pode ser acessado especificando o índice ao longo de cada eixo dentro de um único conjunto de colchetes, separados por vírgulas. Por exemplo, o elemento `8` está na linha `1` e na coluna `3`:

In [17]:
print(a[1, 3])

8

Observe que `numpy.array` não é o mesmo que a classe `array.array` da biblioteca padrão do Python, que lida apenas com arrays unidimensionais e oferece menos funcionalidades. Os atributos mais importantes de um objeto `ndarray` são:

- **ndarray.ndim**: o número de eixos (dimensões) do array.

In [18]:
a.ndim

2

- **ndarray.shape**: as dimensões do array. Esta é uma tupla de inteiros que indica o tamanho do array em cada dimensão. Para uma matriz com n linhas e m colunas, a forma será `(n,m)`. O comprimento da tupla da forma é, portanto, o número de eixos, `ndim`.

In [19]:
a.shape

(3, 4)

- **ndarray.size**: o número total de elementos do array. Este é igual ao produto dos elementos da forma.

In [20]:
a.size

12

- **ndarray.dtype**: um objeto que descreve o tipo dos elementos no array. É possível criar ou especificar dtypes usando tipos padrão do Python. Além disso, o NumPy fornece seus próprios tipos. `numpy.int32`, `numpy.int16` e `numpy.float64` são alguns exemplos.

In [21]:
a.dtype

dtype('int64')

- **ndarray.itemsize**: o tamanho em bytes de cada elemento do array. Por exemplo, um array de elementos do tipo `float64` tem tamanho de item `8` (`=64/8`), enquanto um do tipo `complex32` tem tamanho de item `4` (`=32/8`). É equivalente a `ndarray.dtype.itemsize`.

In [22]:
a.itemsize

8

- **ndarray.data**: o buffer que contém os elementos reais do array. Normalmente, não precisamos usar este atributo porque acessaremos os elementos em um array usando recursos de indexação.

In [23]:
a.data

### 1.6. Como criar Arrays Básicos

Esta seção abrange `np.zeros()`, `np.ones()`, `np.empty()`, `np.arange()` e `np.linspace()`.

Além de criar um array a partir de uma sequência de elementos, você pode facilmente criar um array preenchido com `0`s:

In [24]:
np.zeros(2)

array([0., 0.])

Ou um array preenchido com `1`s:

In [25]:
np.ones(2)

array([1., 1.])

Ou até mesmo um array vazio! A função `empty` cria um array cujo conteúdo inicial é aleatório e depende do estado da memória. O motivo para usar `empty` em vez de `zeros` (ou algo semelhante) é a velocidade — apenas certifique-se de preencher todos os elementos depois!

In [26]:
np.empty(2)

array([1., 1.])

Você pode criar um array com um intervalo de elementos:

In [27]:
np.arange(4)

array([0, 1, 2, 3])

E até mesmo uma matriz que contém um intervalo de intervalos uniformemente espaçados. Para fazer isso, você especificará o **primeiro número**, o **último número** e o **tamanho do passo**.

In [28]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

Você também pode usar `np.linspace()` para criar um array com valores espaçados linearmente em um intervalo especificado:

In [29]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Embora o tipo de dados padrão seja ponto flutuante (`np.float64`), você pode especificar explicitamente qual tipo de dados deseja usando a palavra-chave `dtype`.

In [30]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

### 1.7. Adicionar, Remover e Ordenar Elementos

Esta seção abrange `np.sort()` e `np.concatenate()`.

Ordenar um array é simples com `np.sort()`. Você pode especificar o eixo, o tipo e a ordem ao chamar a função.

Se você começar com este array:

In [31]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

Você pode ordenar rapidamente os números em ordem crescente com:

In [32]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

Além de `sort`, que retorna uma cópia ordenada de um array, você pode usar:

- `argsort`, que é uma ordenação indireta ao longo de um eixo especificado,

- `lexsort`, que é uma ordenação indireta estável em múltiplas chaves,

- `searchsorted`, que encontrará elementos em um array ordenado, e

- `partition`, que é uma ordenação parcial.

Para ler mais sobre ordenação de um array, consulte a [documentação oficial](https://numpy.org/doc/stable/reference/routines.sort.html).

Se você começar com estes arrays:

In [33]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

Você pode concatená-los com `np.concatenate()`.

In [34]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

Ou, se você começar com esses arrays:

In [35]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

Você pode concatená-los com:

In [36]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

Para remover elementos de um array, é simples usar a indexação para selecionar os elementos que você deseja manter.

Para ler mais sobre concatenação de arrays, consulte a [documentação oficial](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html#numpy.concatenate).

### 1.8. Remodelando Arrays

Usar `np.reshape()` dará um novo formato a um array sem alterar os dados. Lembre-se de que, ao usar o método reshape, o array que você deseja produzir precisa ter o mesmo número de elementos que o array original. Se você começar com um array com `12` elementos, precisará garantir que o novo array também tenha um total de `12` elementos.

Se você começar com este array:

In [37]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]

Você pode usar `reshape()` para remodelar seu array. Por exemplo, você pode remodelar este array para um array com três linhas e duas colunas:

In [38]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]

Com `np.reshape`, você pode especificar alguns parâmetros opcionais:

In [39]:
np.reshape(a, shape=(1,6), order='C')

array([[0, 1, 2, 3, 4, 5]])

- `a` é o array a ser remodelado. 

- `shape` é o novo formato desejado. Você pode especificar um inteiro ou uma tupla de inteiros. Se você especificar um inteiro, o resultado será um array com esse tamanho. O formato deve ser compatível com o formato original.

- `order`: `C` significa ler/escrever os elementos usando uma ordem de índice semelhante à da linguagem de programação `C`, `F` significa ler/escrever os elementos usando uma ordem de índice semelhante à da linguagem de programação `Fortran`, `A` significa ler/escrever os elementos em uma ordem de índice semelhante à de `Fortran` se `a` for uma área de memória contígua Fortran, ou em uma ordem semelhante à de C caso contrário. (Este é um parâmetro opcional e não precisa ser especificado.)

Se você quiser aprender mais sobre a ordem em C e Fortran, pode ler mais sobre a organização interna de arrays NumPy [na documentação oficial](https://numpy.org/doc/stable/dev/internals.html#numpy-internals).

### 1.9. Convertendo Arrays 1D para 2D

Você pode usar `np.newaxis` e `np.expand_dims` para aumentar as dimensões do seu array existente.

Usar `np.newaxis` aumentará as dimensões do seu array em uma dimensão quando usado uma vez. Isso significa que um array 1D se tornará um array 2D, um array 2D se tornará um array 3D e assim por diante.

Por exemplo, se você começar com este array:

In [40]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

Você pode usar `np.newaxis` para adicionar um novo eixo:

In [43]:
a2 = a[np.newaxis, :]
print(a2.shape)
a2

(1, 6)

array([[1, 2, 3, 4, 5, 6]])

Você pode converter explicitamente um array 1D em um vetor linha ou coluna usando `np.newaxis`. Por exemplo, você pode converter um array 1D em um vetor linha inserindo um eixo ao longo da primeira dimensão:

In [44]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]

Ou, para um vetor de coluna, você pode inserir um eixo ao longo da segunda dimensão:

In [45]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

Você também pode expandir um array inserindo um novo eixo em uma posição especificada com `np.expand_dims`.

Por exemplo, se você começar com este array:

In [46]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

Você pode usar `np.expand_dims` para adicionar um eixo na posição de índice `1` com:

In [47]:
b = np.expand_dims(a, axis=1)
print(b.shape)
print(b)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

Você pode adicionar um eixo na posição de índice `0` com:

In [48]:
c = np.expand_dims(a, axis=0)
print(c.shape)
print(c)

(1, 6)
[[1 2 3 4 5 6]]

### 1.10. Indexação e Fatiamento

Como mencionado anteriormente, você pode indexar e fatiar arrays NumPy da mesma forma que pode fatiar listas Python.

In [49]:
data = np.array([1, 2, 3])

In [50]:
print(data[0])

1

In [51]:
print(data[1])

2

In [52]:
data[0:2]

array([1, 2])

In [53]:
data[1:]

array([2, 3])

In [54]:
data[-2:]

array([2, 3])

Você pode visualizar desta forma:

<img alt="NumPy Indexing" src="./img/np_indexing.png">

Talvez você queira usar uma seção do seu array ou elementos específicos do array para análises posteriores ou operações adicionais. Para isso, você precisará subdividir, fatiar e/ou indexar seus arrays.

Se você quiser selecionar valores do seu array que atendam a determinadas condições, isso é simples com o NumPy.

Por exemplo, se você começar com este array:

In [55]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

Você pode imprimir facilmente todos os valores um array que são menores que `5`.

In [56]:
print(a[a < 5])

[1 2 3 4]

Você também pode selecionar, por exemplo, números iguais ou maiores que `5` e usar essa condição para indexar um array.

In [57]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]

Você pode selecionar elementos que são divisíveis por `2`:

In [59]:
divisible_by_2 = a[a % 2 == 0]
print(divisible_by_2)

[ 2  4  6  8 10 12]

Ou você pode selecionar elementos que satisfaçam duas condições usando os operadores `&` e `|`:

In [60]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]

Você também pode usar os operadores lógicos `&` e `|` para retornar valores booleanos que especificam se os valores em uma matriz atendem ou não a uma determinada condição. Isso pode ser útil com matrizes que contêm nomes ou outros valores categóricos.

In [61]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]

Você também pode usar `np.nonzero()` para selecionar elementos ou índices de um array.

Começando com este array:

In [62]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

Você pode usar `np.nonzero()` para imprimir os índices de elementos que são, por exemplo, menores que `5`:

In [63]:
b = np.nonzero(a < 5)
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

Neste exemplo, uma tupla de arrays foi retornada: uma para cada dimensão. O primeiro array representa os índices de linha onde esses valores são encontrados, e o segundo array representa os índices de coluna onde os valores são encontrados.

Se você quiser gerar uma lista de coordenadas onde os elementos existem, você pode compactar os arrays, iterar sobre a lista de coordenadas e imprimi-las. Por exemplo:

In [64]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))

In [65]:
print(a[0, 0], a[0, 1], a[0, 2], a[0, 3])

1 2 3 4

Você também pode usar `np.nonzero()` para imprimir os elementos em um array que são menores que `5` com:

In [66]:
print(a[b])

[1 2 3 4]

Se o elemento que você procura não existir no array, o array de índices retornado estará vazio. Por exemplo:

In [67]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))

### 1.11. Operações Básicas com Arrays

Depois de criar seus arrays, você pode começar a trabalhar com eles. Digamos, por exemplo, que você criou dois arrays, um chamado `"data"` e outro chamado `"ones"`.

<img alt="NumPy data and ones" src="./img/np_array_dataones.png">

Você pode somar os arrays com o sinal de mais.

In [68]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

<img alt="NumPy data and ones" src="./img/np_data_plus_ones.png">

É claro que você pode fazer mais do que apenas somar!

In [69]:
data - ones

array([0, 1])

In [70]:
data * data

array([1, 4])

In [71]:
data / data

array([1., 1.])

<img alt="NumPy data and ones" src="./img/np_sub_mult_divide.png">

As operações básicas são simples com o NumPy. Se você quiser encontrar a soma dos elementos de um array, use `sum()`. Isso funciona para arrays 1D, 2D e em dimensões maiores.

In [72]:
a = np.array([1, 2, 3, 4])
print(a.sum())

10

Para adicionar linhas ou colunas em um array 2D (matriz), você deve especificar o eixo.

Se você começar com esta matriz:

In [73]:
b = np.array([[1, 1], [2, 2]])

Você pode somar sobre o eixo das linhas com:

In [74]:
b.sum(axis=0)

array([3, 3])

Você pode somar sobre o eixo das colunas com:

In [75]:
b.sum(axis=1)

array([2, 4])

<img alt="Sum em array 2D" src="./img/np_sum_2d.png">

Há momentos em que você pode querer realizar uma operação entre um array e um único número (também chamada de operação entre um vetor e um escalar) ou entre arrays de dois tamanhos diferentes. Por exemplo, sua matriz (vamos chamá-la de `"data"`) pode conter informações sobre distância em milhas, mas você deseja converter as informações para quilômetros. Você pode realizar esta operação com:

In [76]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

<img alt="Broadcasting" src="./img/np_multiply_broadcasting.png">

O NumPy entende que a multiplicação deve ocorrer com cada célula. Esse conceito é chamado de *transmissão*. As dimensões da sua matriz devem ser compatíveis, por exemplo, quando as dimensões de ambas as matrizes são iguais ou quando uma delas é `1`. Se as dimensões não forem compatíveis, você receberá um `ValueError`.

O NumPy também executa funções de agregação. Além de `min`, `max` e `sum`, você pode facilmente executar `mean` para obter a média, `prod` para obter o resultado da multiplicação dos elementos, `std` para obter o desvio padrão e muito mais.

In [77]:
data = np.array([1, 2, 3])
print(data.max())
print(data.min())
print(data.sum())

3
1
6

<img alt="Agregação" src="./img/np_aggregation.png">

In [78]:
print(data.mean())
print(data.std())
print(data.prod())

2.0
0.816496580927726
6

Considere o array 2D (uma matriz) como descrito abaixo:

In [79]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

<img alt="Agregação em Matrizes" src="./img/np_create_matrix.png">

As operações de indexação e fatiamento são úteis quando você está manipulando matrizes:

In [80]:
data[0, 1]

np.int64(2)

In [81]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [82]:
data[0:2, 0]

array([1, 3])

<img alt="Indexação em Matrizes" src="./img/np_matrix_indexing.png">

Você pode agregar matrizes da mesma forma que agregou vetores:

In [83]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21

<img alt="Agregação de Matrizes" src="./img/np_matrix_aggregation.png">

Você pode agregar todos os valores em uma matriz e agregá-los em colunas ou linhas usando o parâmetro `axis`. Para ilustrar esse ponto, vejamos um conjunto de dados ligeiramente modificado:

In [84]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [85]:
data.max(axis=0)

array([5, 6])

In [86]:
data.max(axis=1)

array([2, 5, 6])

<img alt="Agregação de Matrizes por Linha" src="./img/np_matrix_aggregation_row.png">

É comum precisar transpor matrizes. Os arrays NumPy têm a propriedade `T` que permite transpor uma matriz.

In [87]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [88]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

<img alt="Transposição" src="./img/np_transposing_reshaping.png">

Você também pode precisar trocar as dimensões de uma matriz. Isso pode acontecer quando, por exemplo, você tem um modelo que espera uma determinada forma de entrada diferente do seu conjunto de dados. É aqui que o método `reshape` pode ser útil. Você só precisa passar as novas dimensões desejadas para a matriz.

In [89]:
data = np.array([1, 2, 3, 4, 5, 6])
data

array([1, 2, 3, 4, 5, 6])

In [90]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

<img alt="Transposição" src="./img/np_reshape.png">

Você também pode usar `.transpose()` para inverter ou alterar os eixos de um array de acordo com os valores especificados.

Se você começar com este array:

In [92]:
a = np.arange(6).reshape((2, 3))
a

array([[0, 1, 2],
       [3, 4, 5]])

Você pode transpor seu array com `a.transpose()` (é similar a `a.T`).

In [93]:
a.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

A função `np.flip()` do NumPy permite inverter o conteúdo de um array ao longo de um eixo. Ao usar `np.flip()`, especifique o array que deseja inverter e o eixo. Se você não especificar o eixo, o NumPy inverterá o conteúdo ao longo de todos os eixos do seu array de entrada.

Se você começar com um array 1D como este:

In [94]:
one_d = np.array([1, 2, 3, 4, 5, 6, 7, 8])

Você pode reverter isso com:

In [95]:
one_d_flipped = np.flip(one_d)
print(one_d_flipped)

[8 7 6 5 4 3 2 1]

Um array 2D funciona da mesma maneira.

Se você começar com esta matriz:

In [96]:
two_d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

Você pode reverter o conteúdo em todas as linhas e todas as colunas com:

In [97]:
two_d_flipped = np.flip(two_d)
print(two_d_flipped)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]

Você pode facilmente inverter apenas as linhas com:

In [98]:
two_d_flipped_rows = np.flip(two_d, axis=0)
print(two_d)
print()
print(two_d_flipped_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]

Ou inverta apenas as colunas com:

In [99]:
two_d_flipped_columns = np.flip(two_d, axis=1)
print(two_d)
print()
print(two_d_flipped_columns)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]

Você também pode inverter o conteúdo de apenas uma coluna ou linha. Por exemplo, você pode inverter o conteúdo da linha na posição de índice `1` (a segunda linha):

In [100]:
two_d[1] = np.flip(two_d[1])
print(two_d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]

### 1.12. Trabalhando com Fórmulas

A facilidade de implementação de fórmulas matemáticas que funcionam em matrizes é um dos fatores que tornam o NumPy tão amplamente utilizado na comunidade científica do Python.

Por exemplo, esta é a fórmula do erro quadrático médio (uma fórmula central usada em modelos de aprendizado de máquina supervisionado que lidam com regressão):

$\text{MSE}(y, \hat{y}) = \frac{1}{N} \sum_{i=1}^{N} (y_i - \hat{y}_i)^2$

onde:
- $\text{MSE}$: Isso renderiza "MSE" como texto simples dentro da equação. 

- $y$: Representa os valores reais ou verdadeiros.

- $\hat{y}$: Representa os valores previstos (pronuncia-se "y-hat").

- $N$: Representa o número total de pontos de dados ou observações.

- $\sum_{i=1}^{N}$: Esta é a notação de soma, indicando que você soma as diferenças ao quadrado para cada ponto de dados de $i=1$ a $N$.

- $(y_i - \hat{y}_i)^2$: Esta é a diferença ao quadrado entre o valor real ($y_{i}$) e o valor previsto ($\hat{y}_{i}$) para o $i$-ésimo ponto de dados.

- $\frac{1}{N}$: Divide a soma das diferenças ao quadrado pelo número de pontos de dados, calculando a média.

Implementar esta fórmula é simples e direto no NumPy:

In [101]:
predictions = np.array([1, 1, 1])
labels = np.array([1, 2, 3])
n = 3
error = (1/n) * np.sum(np.square(predictions - labels))
print(error)

1.6666666666666665

O que torna isso tão eficaz é que as `predictions` e os `labels` podem conter um ou mil valores. Eles só precisam ter o mesmo tamanho.

Você pode visualizar desta forma:

<img alt="Transposição" src="./img/np_mse_viz1.png">

Neste exemplo, tanto os vetores de `prediction` quanto os de `labels` contêm três valores, o que significa que `n` tem valor três. Após realizarmos as subtrações, os valores no vetor são elevados ao quadrado. Em seguida, o NumPy soma os valores, e o resultado é o valor do erro para essa predição e uma pontuação para a qualidade do modelo.

<img alt="Transposição" src="./img/np_mse_viz2.png">

<img alt="Transposição" src="./img/np_mse_viz3.png">

A tabela abaixo traz uma lista de algumas [funções universais](https://numpy.org/doc/stable/reference/ufuncs.html) disponíveis no NumPy:

| Função | Descrição |
|--------|------------|
| `np.add(x1, x2)` | Soma elemento a elemento entre dois arrays. |
| `np.subtract(x1, x2)` | Subtrai elemento a elemento entre dois arrays. |
| `np.multiply(x1, x2)` | Multiplica elemento a elemento entre dois arrays. |
| `np.divide(x1, x2)` | Divide elemento a elemento entre dois arrays. |
| `np.power(x1, x2)` | Eleva cada elemento de `x1` à potência correspondente de `x2`. |
| `np.sqrt(x)` | Calcula a raiz quadrada de cada elemento do array. |
| `np.exp(x)` | Calcula o exponencial (e^x) de cada elemento. |
| `np.log(x)` | Calcula o logaritmo natural (base e). |
| `np.log10(x)` | Calcula o logaritmo de base 10. |
| `np.log2(x)` | Calcula o logaritmo de base 2. |
| `np.sin(x)` | Calcula o seno (em radianos) de cada elemento. |
| `np.cos(x)` | Calcula o cosseno (em radianos) de cada elemento. |
| `np.tan(x)` | Calcula a tangente (em radianos) de cada elemento. |
| `np.arcsin(x)` | Calcula o arco-seno (em radianos) de cada elemento. |
| `np.arccos(x)` | Calcula o arco-cosseno (em radianos) de cada elemento. |
| `np.arctan(x)` | Calcula o arco-tangente (em radianos) de cada elemento. |
| `np.deg2rad(x)` | Converte graus em radianos. |
| `np.rad2deg(x)` | Converte radianos em graus. |
| `np.abs(x)` | Retorna o valor absoluto (módulo) de cada elemento. |
| `np.sign(x)` | Retorna o sinal de cada elemento (-1, 0, 1). |
| `np.floor(x)` | Arredonda cada elemento para baixo (menor inteiro). |
| `np.ceil(x)` | Arredonda cada elemento para cima (maior inteiro). |
| `np.round(x, n)` | Arredonda para `n` casas decimais. |
| `np.sum(x)` | Soma todos os elementos do array. |
| `np.prod(x)` | Calcula o produto de todos os elementos. |
| `np.mean(x)` | Calcula a média dos elementos. |
| `np.median(x)` | Calcula a mediana dos elementos. |
| `np.std(x)` | Calcula o desvio padrão. |
| `np.var(x)` | Calcula a variância. |
| `np.min(x)` | Retorna o menor valor do array. |
| `np.max(x)` | Retorna o maior valor do array. |
| `np.clip(x, a_min, a_max)` | Limita os valores entre `a_min` e `a_max`. |
| `np.cumsum(x)` | Calcula a soma cumulativa. |
| `np.cumprod(x)` | Calcula o produto cumulativo. |
| `np.diff(x)` | Calcula as diferenças discretas entre elementos consecutivos. |
| `np.trunc(x)` | Trunca os valores para a parte inteira. |
| `np.mod(x1, x2)` | Calcula o resto da divisão elemento a elemento. |
| `np.remainder(x1, x2)` | Calcula o resto da divisão (semelhante a `mod`). |

**Nota.** *Uma função universal é uma função que opera em `ndarrays` de forma elemento por elemento, suportando transmissão de array, conversão de tipo e vários outros recursos padrão.*

### 1.13. Exercícios

In [102]:
# Esta célula informa ao Jupyter para fornecer informações detalhadas de depuração
# quando ocorrer um erro de execução. Execute-o antes de trabalhar nos exercícios.

%xmode Verbose

Exception reporting mode: Verbose

#### 1.13.1 Exercício

Crie um array NumPy com os números de 1 a 10 e mostre:
- o tipo de dado (`dtype`);
- a forma (`shape`);
- e o número de dimensões (`ndim`).

In [103]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"Tipo de dados de arr: {arr.dtype}")
print(f"Formato de arr: {arr.shape}")
print(f"Eixos em arr: {arr.ndim}")

Tipo de dados de arr: int64
Formato de arr: (10,)
Eixos em arr: 1

#### 1.13.2 Exercício

Crie um array de 12 elementos com `np.arange()` e reorganize-o em uma matriz `3x4` usando `reshape()`.
Em seguida, exiba a soma de cada linha e de cada coluna.

In [122]:
arr = np.arange(12)
arr = np.reshape(arr, (3, 4))
print(arr)
count = 1
for r in arr:
    print(f"Soma da linha {count}: {r.sum()}")
    count += 1
count = 1
for c in arr.T:
    print(f"Soma da coluna {count}: {c.sum()}")
    count += 1
#Alternativamente, posso armazenar cada soma em um array próprio em que cada índice é o índice da linha ou coluna
print()
row_sum = arr.sum(axis=1)
col_sum = arr.sum(axis=0)
print(row_sum)
print(col_sum)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Soma da linha 1: 6
Soma da linha 2: 22
Soma da linha 3: 38
Soma da coluna 1: 12
Soma da coluna 2: 15
Soma da coluna 3: 18
Soma da coluna 4: 21

[ 6 22 38]
[12 15 18 21]

#### 1.13.3 Exercício

Crie dois arrays com 5 elementos cada e realize as operações:
- soma,
- subtração,
- multiplicação, e 
- divisão.

Mostre que todas as operações são realizadas elemento a elemento.

In [134]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
print(f"Soma: {arr1 + arr2}")
print(f"Sub: {arr1 - arr2}")
print(f"Mult: {arr1 * arr2}")
print(f"Div: {arr1 / arr2}")

Soma: [ 7  9 11 13 15]
Sub: [-5 -5 -5 -5 -5]
Mult: [ 6 14 24 36 50]
Div: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]

#### 1.13.4 Exercício

Crie um array bidimensional 4x4 e:
- selecione a 2ª linha;
- selecione a 3ª coluna;
- extraia o subarray das duas últimas linhas e duas últimas colunas.

In [153]:
arr =np.array([np.arange(4), [4, 5, 6, 7], [8, 9, 0, 1], [2, 3, 4, 5]])
print(arr)
print(f"Segunda linha: {arr[1]}")
print(f"Terceira coluna: {arr[:, 2]}")
print(f"Subarray: {arr[2:, 2:]}")

[[0 1 2 3]
 [4 5 6 7]
 [8 9 0 1]
 [2 3 4 5]]
Segunda linha: [4 5 6 7]
Terceira coluna: [2 6 0 4]
Subarray: [[0 1]
 [4 5]]

#### 1.13.5 Exercício

Um pesquisador deseja calcular o **índice de crescimento ajustado** (ICA) de uma população de bactérias em diferentes condições de temperatura.
A fórmula para o cálculo é:

$ICA = \frac{(T_2 - T_1)}{T_1} \times 100$

onde:
- $T_{1}$ é o array com as medições iniciais de crescimento,
- $T_{2}$ é o array com as medições finais de crescimento,
- $ICA$ representa o percentual de variação do crescimento.

**Tarefa**

1. Crie dois arrays NumPy (`T1` e `T2`)
2. Implemente a fórmula acima para calcular o array ICA.
3.	Mostre:
    - O array resultante com os percentuais de variação.
    - O valor médio de crescimento (média de ICA).

In [158]:
T1, T2 = [1, 25, 13, 56, 14, 66, 14], [1, 26, 17, 68, 17, 69, 17]
ICA =  np.divide(np.subtract(T2, T1), T1) * 100
print(ICA)
print(f"Média de ICA: {ICA.mean()}")

[ 0.          4.         30.76923077 21.42857143 21.42857143  4.54545455
 21.42857143]
Média de ICA: 14.800057085771373

## 2. A Biblioteca Pandas

Pandas é uma biblioteca que contém estruturas de dados e ferramentas de manipulação de dados projetadas para tornar a limpeza e a análise de dados rápidas e convenientes em Python. Pandas é frequentemente usada em conjunto com ferramentas de computação numérica como NumPy e SciPy, bibliotecas analíticas como statsmodels e scikit-learn e bibliotecas de visualização de dados como matplotlib.

### 2.1. Instalando Pandas

A maneira mais fácil de instalar o Pandas é instalá-lo como parte da distribuição [Anaconda](https://www.anaconda.com/), uma distribuição multiplataforma para análise de dados e computação científica. O gerenciador de pacotes [Conda](https://docs.conda.io/) é o método de instalação recomendado para a maioria dos usuários.

Também é possível instalar Pandas a partir do código fonte, PyPI ou uma versão de desenvolvimento. No nosso curso usaremos a instalação via `pip`:

In [159]:
pip install pandas

Requirement already satisfied: pandas in ./.venv/lib/python3.12/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in ./.venv/lib/python3.12/site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

Se você já possuir o Pandas instalado, podes atualizá-lo da seguinte forma:

In [160]:
pip install --upgrade pandas

Requirement already satisfied: pandas in ./.venv/lib/python3.12/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in ./.venv/lib/python3.12/site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

Após instalar o Pandas, verifique a instalação executando o seguinte em um shell ou script Python:

In [161]:
import pandas as pd
print(pd.__version__)

2.3.3

### 2.2. Introdução às Estruturas de Dados do Pandas

Para começar a usar o Pandas, você precisa se familiarizar com suas duas estruturas de dados mais utilizadas: `Series` e `DataFrame`. Embora não sejam uma solução universal para todos os problemas, elas fornecem uma base sólida para uma ampla variedade de tarefas de dados.

#### 2.2.1. Conceitos Básicos

Ao longo de todo este curso, nós usaremos a seguinte convensão de importação para a bibliotéca Pandas:

In [162]:
import pandas as pd

Portanto, sempre que você vir `pd.` no código, ele se refere a Pandas. Você também pode achar mais fácil importar `Series` e `DataFrame` para o namespace local, já que são usados ​​com muita frequência:

In [ ]:
from pandas import Series, DataFrame

#### 2.2.2. Series

Uma `Series` é um objeto unidimensional semelhante a um array que contém uma sequência de valores (de tipos semelhantes aos tipos NumPy) do mesmo tipo e um array associado de rótulos de dados, chamada de *index*. A `Series` mais simples é formada apenas por um array de dados:

In [163]:
obj_s = pd.Series([4, 7, -5, 3])
obj_s

0    4
1    7
2   -5
3    3
dtype: int64

A representação em string de uma `Series` exibida iterativamente mostra o índice à esquerda e os valores à direita. Como não especificamos um índice para os dados, um índice padrão composto pelos inteiros de `0` a `N - 1` (onde `N` é o comprimento dos dados) é criado. Você pode obter a representação em array e o objeto de índice da `Series` por meio de seus atributos `array` e `index`, respectivamente:

In [164]:
obj_s.array

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

O resultado do atributo `.array` possui como tipo base a classe `ExtensionArray` que geralmente encapsula um array NumPy, mas também pode conter tipos especiais extendidos de array que serão discutidos mais a frente.

In [165]:
obj_s.index

RangeIndex(start=0, stop=4, step=1)

O atributo `.index` possui como tipo base a classe `Index` usado para rotular e identificar cada elemento dos dados subjacentes. O `.index` pode ser considerado um conjunto ordenado imutável (tecnicamente um multiconjunto, pois pode conter rótulos duplicados) e é usado para indexar e alinhar dados no Pandas.

Muitas vezes, você desejará criar uma `Series` com um `index` identificando cada ponto de dados com um rótulo:

In [166]:
obj_s2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
obj_s2

d    4
b    7
a   -5
c    3
dtype: int64

In [167]:
obj_s2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

Em comparação com arrays NumPy, você pode usar rótulos no índice ao selecionar valores únicos ou um conjunto de valores:

In [168]:
print(obj_s2['a'])

-5

In [169]:
obj_s2['d'] = 6
print(obj_s2['d'])

6

In [170]:
obj_s2

d    6
b    7
a   -5
c    3
dtype: int64

In [171]:
obj_s2[['c', 'a', 'b']]

c    3
a   -5
b    7
dtype: int64

Aqui, `['c', 'a', 'b']` é interpretado como uma lista de índices, mesmo que contenha strings em vez de inteiros.

O uso de funções NumPy ou operações semelhantes a NumPy, como filtragem com um array booleano, multiplicação escalar ou aplicação de funções matemáticas, preservará o vínculo índice-valor:

In [172]:
print(obj_s2)
obj_s2[obj_s2 > 0]

d    6
b    7
a   -5
c    3
dtype: int64

d    6
b    7
c    3
dtype: int64

In [173]:
obj_s2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [174]:
import numpy as np

np.exp(obj_s2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

Outra maneira de pensar em uma `Series` é como um dicionário ordenado de comprimento fixo, pois é um mapeamento de valores de índice para valores de dados. Ela pode ser usada em muitos contextos em que você pode usar um dicionário:

In [175]:
'b' in obj_s2

True

In [176]:
'e' in obj_s2

False

Caso você tenha dados contidos em um dicionário Python, você pode criar uma `Series` a partir deles passando o dicionário:

In [177]:
data_dict = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

In [180]:
obj_s3 = pd.Series(data_dict)
obj_s3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

Uma série pode ser convertida novamente em um dicionário com seu método `to_dict`:

In [181]:
obj_s3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

Ao passar apenas um dicionário, o `index` na `Series` resultante respeitará a ordem das chaves de acordo com o método `keys` do dicionário, que depende da ordem de inserção das chaves. Você pode substituir isso passando um `index` com as chaves do dicionário na ordem em que deseja que elas apareçam na `Series` resultante:

In [182]:
states = ["California", "Ohio", "Oregon", "Texas"]
obj_s4 = pd.Series(data_dict, index=states)
obj_s4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

Aqui, três valores encontrados em `data_dict` foram colocados nos locais apropriados, mas como nenhum valor para `"California"` foi encontrado, ele aparece como `NaN` (*Not a Number* ou `Não é um Número`), o que é considerado no Pandas para marcar valores ausentes ou `NA`(*Not Available*). Como `"Utah"` não foi incluído em estados, ele é excluído do objeto resultante.

Usaremos os termos `"missing"`, `"NA"` ou `"null"` indistintamente para nos referirmos a dados ausentes/faltantes. As funções `isna` e `notna` no Pandas devem ser usadas para detectar dados ausentes:

In [183]:
pd.isna(obj_s4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [184]:
pd.notna(obj_s4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

A `Series` também tem estes como métodos de instância:

In [185]:
obj_s4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [186]:
obj_s4.notna()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

Discutiremos o trabalho com dados ausentes/faltantes com mais detalhes em outro módulo.

Um recurso útil da `Series` para muitas aplicações é que ela alinha automaticamente por rótulo de índice em operações aritméticas:

In [187]:
obj_s3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [188]:
obj_s4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [189]:
obj_s3 + obj_s4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

Os recursos de alinhamento de dados serão abordados com mais detalhes posteriormente. Se você tem experiência com bancos de dados, pode pensar nisso como algo semelhante a uma operação de junção (`join` do SQL).

Tanto o objeto `Series` quanto seu `index` possuem um atributo `name`, que se integra a outras áreas da funcionalidade do Pandas:

In [190]:
obj_s4.name = "population"
obj_s4.index.name = "states"
obj_s4

states
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

O `index` de uma série pode ser alterado no local por atribuição:

In [191]:
obj_s

0    4
1    7
2   -5
3    3
dtype: int64

In [192]:
obj_s.index = ["Bob", "Steve", "Jeff", "Ryan"]
obj_s

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

#### 2.2.3. DataFrame

Um `DataFrame` representa uma tabela retangular de dados e contém uma coleção ordenada e nomeada de colunas, cada uma das quais pode ser de um tipo de valor diferente (numérico, string, booleano, etc.). O `DataFrame` possui um índice de linha e de coluna; pode ser considerado um dicionário de `Series`, todas compartilhando o mesmo `index`.

Há muitas maneiras de construir um `DataFrame`, embora uma das mais comuns seja a partir de um dicionário de listas de comprimento igual ou arrays NumPy:

In [193]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data)

O `DataFrame` resultante terá seu índice atribuído automaticamente, como em `Series`, e as colunas serão colocadas de acordo com a ordem das chaves nos dados (que depende da ordem de inserção no dicionário):

In [194]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

Para `DataFrames` grandes, o método `head` seleciona apenas as cinco primeiras linhas:

In [195]:
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

Da mesma forma, `tail` retorna as últimas cinco linhas:

In [196]:
frame.tail()

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

Tanto `head` quanto `tail` aceitam parâmetros, modificando o limite de `5`elementos:

In [ ]:
frame.head(6)

In [ ]:
frame.tail(6)

Se você especificar uma sequência de colunas, as colunas do `DataFrame` serão organizadas nessa ordem:

In [197]:
pd.DataFrame(data, columns=["year", "state", "pop"])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

Se você passar uma coluna que não está contida no dicionário, ela aparecerá com valores ausentes no resultado:

In [198]:
frame_2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])
frame_2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [199]:
frame_2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

Uma coluna em um `DataFrame` pode ser recuperada como um objeto de `Series` por meio de notação semelhante a um dicionário ou usando a notação de atributo de ponto:

In [200]:
frame_2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [201]:
type(frame_2["state"])

pandas.core.series.Series

In [202]:
frame_2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

Observe que a `Series` retornada tem o mesmo `index` que o `DataFrame` se seu atributo `name` foi definido corretamente.

As linhas também podem ser recuperadas por posição ou nome com os atributos especiais `iloc` e `loc` (veremos mais detalhes no futuro).

In [203]:
frame_2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [204]:
frame_2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [205]:
frame_2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

As colunas podem ser modificadas por atribuição. Por exemplo, a coluna `"debt"` vazia pode receber um valor escalar ou um array de valores:

In [206]:
frame_2["debt"] = 16.5
frame_2

   year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [209]:
frame_2["debt"] = np.arange(6.0)
frame_2

   year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

Ao atribuir listas ou arrays a uma coluna, o comprimento do valor deve corresponder ao comprimento do `DataFrame`. Se você atribuir uma `Series`, seus rótulos serão realinhados exatamente ao `index` do `DataFrame`, inserindo valores ausentes em quaisquer valores de índice ausentes:

In [210]:
val = pd.Series([-1.2, -1.5, -1.7], index=[2, 4, 5])
frame_2["debt"] = val
frame_2

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6  -1.2
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9  -1.5
5  2003  Nevada  3.2  -1.7

Atribuir uma coluna que não existe criará uma nova coluna.

A palavra-chave `del` excluirá colunas como em um dicionário. Como exemplo, primeiro adiciono uma nova coluna de valores booleanos onde a coluna `state` é igual a `"Ohio"`:

In [211]:
frame_2["eastern"] = frame_2["state"] == "Ohio"
frame_2

   year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6  -1.2     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9  -1.5    False
5  2003  Nevada  3.2  -1.7    False

O método `del` pode então ser usado para remover esta coluna:

In [212]:
del frame_2["eastern"]

In [213]:
frame_2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [214]:
frame_2

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6  -1.2
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9  -1.5
5  2003  Nevada  3.2  -1.7

Outra forma comum de dados é um dicionário aninhado de dicionários:

In [215]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada": {2001: 2.4, 2002: 2.9}}

In [216]:
frame_3 = pd.DataFrame(populations)
frame_3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

Você pode transpor o `DataFrame` (trocar linhas e colunas) com sintaxe semelhante a um array NumPy:

In [217]:
frame_3.T

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

As chaves nos dicionários internos são combinadas para formar o `index` no resultado. Isso não acontece se um `index` explícito for especificado:

In [218]:
pd.DataFrame(populations, index=[2001, 2002, 2003])

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

Os dicionários de séries são tratados da mesma maneira:

In [219]:
frame_3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [220]:
pandas_data = {"Ohio": frame_3["Ohio"][:-1],
               "Nevada": frame_3["Nevada"][:2]}
pd.DataFrame(pandas_data)

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

A tabela abaixo traz uma lista de possíveis entradas de dados que você pode passar para o construtor do `DataFrame`:

| Tipo | Nota |
|--------|------------|
| 2D `ndarray` | Uma matriz de dados, passando rótulos opcionais de linha e coluna. |
| Dicionário de matrizes, listas ou tuplas | Cada sequência se torna uma coluna no DataFrame; todas as sequências devem ter o mesmo comprimento. |
| Matriz estruturada/de registros NumPy | Tratado como o caso do “dicionário de matrizes”. |
| Dicionário de `Series`| Cada valor se torna uma coluna; os índices de cada série são unidos para formar o índice da linha do resultado se nenhum índice explícito for passado. |
| Dicionário de dicionários | Cada dicionário interno se torna uma coluna; as chaves são unidas para formar o índice da linha como no caso do "dicionário de `Series`". |
| Lista de dicionários ou `Series`| Cada item se torna uma linha no `DataFrame`; uniões de chaves de dicionário ou índices de série se tornam rótulos de coluna do `DataFrame`|
| Lista de listas ou tuplas | Tratado como o caso "2D `ndarray`" |
| Outro `DataFrame`| Os índices do `DataFrame` são usados, a menos que outros diferentes sejam passados |
| NumPy `MaskedArray`| Como no caso do "2D `ndarray`", exceto que os valores mascarados estão faltando no resultado do `DataFrame` |

Se o índice e as colunas de um `DataFrame` tiverem seus atributos de `name` definidos, estes também serão exibidos:

In [221]:
frame_3.index.name = "year"

In [222]:
frame_3.columns.name = "state"

In [223]:
frame_3

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

Ao contrário de `Series`, o `DataFrame` não possui um atributo `name`. O método `to_numpy` do `DataFrame` retorna os dados contidos no `DataFrame` como um `ndarray` bidimensional:

In [224]:
frame_3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

Se as colunas do `DataFrame` forem tipos de dados diferentes, o tipo de dados do array retornado será escolhido para acomodar todas as colunas:

In [225]:
frame_2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, -1.2],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, -1.5],
       [2003, 'Nevada', 3.2, -1.7]], dtype=object)

#### 2.2.4. Objetos Index

Os objetos `Index` do Pandas são responsáveis ​​por armazenar os rótulos dos eixos (incluindo os nomes das colunas de um `DataFrame`) e outros metadados (como o(s) nome(s) dos eixos). Qualquer array ou outra sequência de rótulos que você usar ao construir uma `Series` ou `DataFrame` é internamente convertida em um `Index`:

In [226]:
obj = pd.Series(np.arange(3), index=["a", "b", "c"])
obj

a    0
b    1
c    2
dtype: int64

In [227]:
index = obj.index

In [228]:
index

Index(['a', 'b', 'c'], dtype='object')

In [229]:
index[1:]

Index(['b', 'c'], dtype='object')

Objetos de `Index` são imutáveis ​​e, portanto, não podem ser modificados pelo usuário. Se uma tentativa ocorrer o usuário receberá um `TypeError`:

In [ ]:
index[1] = "d"

A imutabilidade torna mais seguro compartilhar objetos de `Index` entre estruturas de dados:

In [230]:
labels = pd.Index(np.arange(3))
labels

Index([0, 1, 2], dtype='int64')

In [231]:
obj_2 = pd.Series([1.5, -2.5, 0], index=labels)
obj_2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [232]:
obj_2.index is labels

True

Além de ser semelhante a um array, um `Index` também se comporta como um conjunto de tamanho fixo:

In [233]:
frame_3

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [234]:
frame_3.columns

Index(['Ohio', 'Nevada'], dtype='object', name='state')

In [235]:
"Ohio" in frame_3.columns

True

In [236]:
2003 in frame_3.index

False

Ao contrário dos conjuntos Python, um `Index` Pandas pode conter rótulos duplicados:

In [237]:
pd.Index(["foo", "foo", "bar", "bar"])

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

Seleções com rótulos duplicados selecionarão todas as ocorrências desse rótulo.

Cada `Index` possui diversos métodos e propriedades para lógica de conjuntos, que respondem a outras perguntas comuns sobre os dados que ele contém. Alguns métodos úteis estão resumidos na tabela abaixo.


| Método/Atributo | Descrição |
|--------|------------|
| `append()` | Concatena com objetos de índice adicionais, produzindo um novo índice. |
| `difference()` | Calcula a diferença do conjunto como um índice |
| `intersection()` | Calcula a intersecção de conjuntos |
| `union()` | Computa a união de conjuntos |
| `isin()` | Calcula uma matriz booleana indicando se cada valor está contido na coleção passada |
| `delete()` | Calcular novo índice com elemento no índice `i` excluído. |
| `drop()` | Calcular novo índice excluindo valores passados |
| `insert()` | Calcular novo índice inserindo elemento no índice `i`|
| `is_monotonic` | Retorna `True` se cada elemento for maior ou igual ao elemento anterior |
| `is_unique` | Retorna `True` se o índice não tiver valores duplicados |
| `unique()` | Calcular a matriz de valores únicos no `Index` |

### 2.3. Funcionalidades Essenciais

Esta seção apresentará a mecânica fundamental da interação com os dados contidos em uma `Series` ou `DataFrame`.

#### 2.3.1. Reindexação

Um método importante em objetos Pandas é o `reindex`, que significa criar um novo objeto com os valores reorganizados para se alinharem ao novo índice. Veja um exemplo:

In [238]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

Chamar `reindex` nesta série reorganiza os dados de acordo com o novo índice, introduzindo valores ausentes se algum valor de índice ainda não estiver presente:

In [239]:
obj_2 = obj.reindex(["a", "b", "c", "d", "e"])
obj_2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [240]:
obj_3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
obj_3

0      blue
2    purple
4    yellow
dtype: object

In [241]:
obj_3.reindex(np.arange(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

Com o `DataFrame`, o `reindex` pode alterar o índice (da linha), as colunas ou ambos. Quando passado apenas uma sequência, ele reindexa as linhas no resultado:

In [243]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), 
                     index=["a", "c", "d"],
                     columns=["Ohio", "Texas", "California"])
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [244]:
frame_2 = frame.reindex(index=["a", "b", "c", "d"])
frame_2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

As colunas podem ser reindexadas com a palavra-chave `columns`:

In [245]:
states = ["Texas", "Utah", "California"]
frame.reindex(columns=states)

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

Para dados ordenados, como séries temporais, talvez você queira fazer alguma interpolação ou preenchimento de valores ao reindexar. A opção `method` nos permite fazer isso, usando um método como `ffill`, que preenche os valores para frente:

Como `"Utah"` não estava em `states`, os dados dessa coluna foram removidos do resultado.

Outra maneira de reindexar um eixo específico é passar os novos rótulos de eixo como um argumento posicional e então especificar o eixo a ser reindexado com a palavra-chave `axis`:

In [246]:
frame.reindex(states, axis="columns")

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

Veja na tabela abaixo mais informações sobre os argumentos para reindexação.

| Argumento | Descrição |
|------------|------------|
| `labels` | Nova sequência a ser usada como índice. Pode ser uma instância de `Index` ou qualquer outra estrutura de dados semelhante a sequência do Python. Um `Index` será usado exatamente como está, sem cópia. |
| `index` | Usa a sequência passada como novos rótulos de índice. |
| `columns` | Usa a sequência passada como novos rótulos de coluna. |
| `axis` | O eixo a ser reindexado, seja `"index"` (linhas) ou `"columns"` (colunas). O padrão é `"index"`. Alternativamente, pode-se usar `reindex(index=new_labels)` ou `reindex(columns=new_labels)`. |
| `method` | Método de interpolação (preenchimento). `"ffill"` preenche para frente, enquanto `"bfill"` preenche para trás. |
| `fill_value` | Valor substituto a ser usado ao introduzir dados ausentes durante a reindexação. Use `fill_value="missing"` (comportamento padrão) quando quiser que os rótulos ausentes tenham valores nulos no resultado. |
| `limit` | Ao preencher para frente ou para trás, define o tamanho máximo do intervalo (em número de elementos) a preencher. |
| `tolerance` | Ao preencher para frente ou para trás, define o tamanho máximo do intervalo (em distância numérica absoluta) para preencher correspondências inexatas. |
| `level` | Faz correspondência de um `Index` simples em um nível de um `MultiIndex`; caso contrário, seleciona um subconjunto. |
| `copy` | Se `True`, sempre copia os dados subjacentes mesmo que o novo índice seja equivalente ao índice antigo; se `False`, não copia os dados quando os índices são equivalentes. |

Como exploraremos mais adiante, você também pode reindexar usando o operador `loc`, e muitos usuários preferem sempre fazer dessa forma. Isso funciona apenas se todos os novos rótulos de índice já existirem no `DataFrame` (enquanto `reindex` inserirá dados ausentes para novos rótulos):

In [247]:
frame.loc[["a", "d", "c"], ["California", "Texas"]]

   California  Texas
a           2      1
d           8      7
c           5      4

#### 2.3.2. Removendo Entradas de um Eixo

Remover uma ou mais entradas de um eixo é simples se você já tiver uma lista ou array de índices sem essas entradas, pois pode usar o método `reindex` ou a indexação baseada em `.loc`. Como isso pode exigir um pouco de manipulação e lógica de conjuntos, o método `drop` retornará um novo objeto com o valor indicado ou valores excluídos de um eixo:

In [248]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [249]:
new_obj = obj.drop("c")
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [250]:
obj.drop(["d", "c"])

a    0.0
b    1.0
e    4.0
dtype: float64

Com o `DataFrame`, os valores de índice podem ser excluídos de qualquer eixo. Para ilustrar isso, primeiro criamos um `DataFrame` de exemplo:

In [251]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=["Ohio", "Colorado", "Utah", "New York"],
                   columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

Chamar `drop` com uma sequência de rótulos removerá valores dos rótulos da linha (eixo `0`):

In [252]:
data.drop(index=["Colorado", "Ohio"])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

Para remover rótulos das colunas, use a palavra-chave `columns`:

In [253]:
data.drop(columns=["two"])

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

Você também pode remover valores das colunas passando `axis=1` (que é como NumPy) ou `axis="columns"`:

In [254]:
data.drop("two", axis=1)

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [ ]:
data.drop(["two", "four"], axis="columns")

#### 2.3.3. Indexação, Seleção e Filtragem

A indexação de `Series` (`obj[...]`) funciona de forma análoga à indexação de arrays NumPy, exceto que você pode usar os valores de índice das `Series` em vez de apenas números inteiros. Aqui estão alguns exemplos disso:

In [255]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [256]:
print(obj["b"])
print()
print(obj[2:4])
print()
print(obj[["a", "b", "d"]])
print()
print(obj[obj < 2])

1.0

c    2.0
d    3.0
dtype: float64

a    0.0
b    1.0
d    3.0
dtype: float64

a    0.0
b    1.0
dtype: float64

Embora você possa selecionar dados por rótulo dessa maneira, a maneira preferida de selecionar valores de índice é com o operador loc especial:

In [257]:
obj.loc[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

A razão para preferir `loc` é o tratamento diferenciado de inteiros ao indexar com `[]`. A indexação regular baseada em `[]` tratará inteiros como rótulos se o índice contiver inteiros, portanto, o comportamento difere dependendo do tipo de dado do índice. Por exemplo:

In [258]:
obj_1 = pd.Series([1, 2, 3], index=[2, 0, 1])
obj_2 = pd.Series([1, 2, 3], index=["a", "b", "c"])

In [259]:
obj_1

2    1
0    2
1    3
dtype: int64

In [260]:
obj_2

a    1
b    2
c    3
dtype: int64

In [261]:
obj_1[[0, 1, 2]]

0    2
1    3
2    1
dtype: int64

In [262]:
obj_2[[0, 1, 2]]

/tmp/ipykernel_138684/1754097719.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj_2[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

Ao usar loc, a expressão `obj_2.loc[[0, 1, 2]]` falhará quando o índice não contiver números inteiros:

In [263]:
obj_2.loc[[0, 1]]

KeyError: "None of [Index([0, 1], dtype='int64')] are in the [index]"

Como o operador `loc` indexa exclusivamente com rótulos, também há um operador `iloc` que indexa exclusivamente com números inteiros para funcionar consistentemente, independentemente de o índice conter ou não números inteiros:

In [264]:
obj_1.iloc[[0, 1, 2]]

2    1
0    2
1    3
dtype: int64

In [265]:
obj_2.iloc[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

Atribuir valores usando esses métodos modifica a seção correspondente da `Series`:

In [266]:
obj_2.loc["b":"c"] = 5
obj_2

a    1
b    5
c    5
dtype: int64

A indexação em um `DataFrame` recupera uma ou mais colunas com um único valor ou sequência:

In [267]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [268]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [269]:
data[["three", "one"]]

          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

Indexar dessa forma tem alguns casos especiais. O primeiro é fatiar ou selecionar dados com um array booleano:

In [270]:
data[:2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [271]:
data[data["three"] > 5]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

A sintaxe de seleção de linha `data[:2]` é fornecida por conveniência. Passar um único elemento ou uma lista para o operador `[]` seleciona colunas.

Outro caso de uso é a indexação com um `DataFrame` booleano, como um produzido por uma comparação escalar. Considere um `DataFrame` com todos os valores booleanos produzidos pela comparação com um valor escalar:

In [272]:
data < 5

            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

Podemos usar este DataFrame para atribuir o valor `0` a cada local com o valor `True`, assim:

In [273]:
data[data < 5] = 0
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

Assim como `Series`, o `DataFrame` possui atributos especiais `loc` e `iloc` para indexação baseada em rótulos e números inteiros, respectivamente. Como o `DataFrame` é bidimensional, você pode selecionar um subconjunto de linhas e colunas com notação semelhante à NumPy usando rótulos de eixo (`loc`) ou números inteiros (`iloc`).

Como primeiro exemplo, vamos selecionar uma única linha por rótulo:

In [274]:
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [275]:
data.loc["Colorado"]

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

O resultado da seleção de uma única linha é uma `Series` com um índice que contém os rótulos das colunas do `DataFrame`. Para selecionar várias funções, criando um novo `DataFrame`, passe uma sequência de rótulos:

In [276]:
data.loc[["Colorado", "New York"]]

          one  two  three  four
Colorado    0    5      6     7
New York   12   13     14    15

Você pode combinar a seleção de linha e coluna em loc separando as seleções com uma vírgula:

In [277]:
data.loc["Colorado", ["two", "three"]]

two      5
three    6
Name: Colorado, dtype: int64

Em seguida, realizaremos algumas seleções semelhantes com inteiros usando `iloc`:

In [278]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [279]:
data.iloc[[2, 1]]

          one  two  three  four
Utah        8    9     10    11
Colorado    0    5      6     7

In [280]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [281]:
data.iloc[[1, 2], [3, 0, 1]]

          four  one  two
Colorado     7    0    5
Utah        11    8    9

Ambas as funções de indexação funcionam com fatias, além de rótulos únicos ou listas de rótulos:

In [282]:
data.loc[data.three >= 2]

          one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

Existem muitas maneiras de selecionar e reorganizar os dados contidos em um objeto Pandas. Para o `DataFrame`, a tabela abaixo fornece um breve resumo de muitas delas.

| Tipo                   | Notas |
|------------------------|-------|
| `df[column]` | Seleciona uma única coluna ou uma sequência de colunas do DataFrame. Também pode ser usado com: um array booleano (para filtrar linhas), um fatiamento (para selecionar linhas) ou um DataFrame booleano (para definir valores com base em um critério). |
| `df.loc[rows]` | Seleciona uma única linha ou um subconjunto de linhas do DataFrame pelo **rótulo**. |
| `df.loc[:, cols]` | Seleciona uma única coluna ou um subconjunto de colunas pelo **rótulo**. |
| `df.loc[rows, cols]` | Seleciona simultaneamente linha(s) e coluna(s) pelo **rótulo**. |
| `df.iloc[rows]` | Seleciona uma única linha ou um subconjunto de linhas do DataFrame pela **posição inteira**. |
| `df.iloc[:, cols]` | Seleciona uma única coluna ou um subconjunto de colunas pela **posição inteira**. |
| `df.iloc[rows, cols]` | Seleciona simultaneamente linha(s) e coluna(s) pela **posição inteira**. |
| `df.at[row, col]` | Seleciona um valor escalar único pelo **rótulo da linha e da coluna**. |
| `df.iat[row, col]` | Seleciona um valor escalar único pela **posição inteira da linha e da coluna**. |
| `reindex method` | Seleciona linhas ou colunas usando **novos rótulos**. |

#### 2.3.4. Aritmética e Alinhamento de Dados

O Pandas pode simplificar muito o trabalho com objetos que possuem índices diferentes. Por exemplo, ao adicionar objetos, se algum par de índices não for o mesmo, o índice correspondente no resultado será a união dos pares de índices. Vejamos um exemplo:

In [283]:
s_1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s_2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=["a", "c", "e", "f", "g"])

In [284]:
s_1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [285]:
s_2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

Somando as séries:

In [286]:
s_1 + s_2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

O alinhamento interno de dados introduz valores ausentes nos locais dos rótulos que não se sobrepõem. Os valores ausentes serão então propagados em cálculos aritméticos posteriores. No caso do `DataFrame`, o alinhamento é realizado tanto em linhas quanto em colunas:

In [287]:
df_1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), 
                    columns=list("bcd"), 
                    index=["Ohio", "Texas", "Colorado"])

df_2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), 
                    columns=list("bde"),
                    index=["Utah", "Ohio", "Texas", "Oregon"])

In [288]:
df_1

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [289]:
df_2

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

Adicionar isso retorna um `DataFrame` com índice e colunas que são as uniões daqueles em cada `DataFrame`:

In [290]:
df_1 + df_2

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

Como as colunas `"c"` e `"e"` não são encontradas em ambos os objetos `DataFrame`, elas aparecem como ausentes no resultado. O mesmo vale para as linhas com rótulos que não são comuns a ambos os objetos.

Se você adicionar objetos DataFrame sem rótulos de coluna ou linha em comum, o resultado conterá todos os valores nulos:

In [291]:
df_1 = pd.DataFrame({"A": [1, 2]})
df_1

   A
0  1
1  2

In [292]:
df_2 = pd.DataFrame({"B": [3, 4]})
df_2

   B
0  3
1  4

In [293]:
df_1 + df_2

    A   B
0 NaN NaN
1 NaN NaN

Em operações aritméticas entre objetos indexados de forma diferente, você pode querer preencher com um valor especial, como `0`, quando um rótulo de eixo é encontrado em um objeto, mas não no outro. Aqui está um exemplo em que definimos um valor específico como `NA` (nulo) atribuindo `np.nan` a ele:

In [294]:
df_1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list("abcd"))
df_1

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [295]:
df_2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list("abcde"))
df_2

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [296]:
df_2.loc[1, "b"] = np.nan
df_2

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

Adicionar esses resultados resulta em valores ausentes nos locais que não se sobrepõem:

In [297]:
df_1 + df_2

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

Usando o método `add` em `df_1`, passando `df_2` e um argumento para `fill_value`, que substitui o valor passado por quaisquer valores ausentes na operação:

In [298]:
df_1

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [299]:
df_2

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [300]:
df_1.add(df_2, fill_value=0)

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

| Método | Descrição |
|---------|------------|
| `add`, `radd` | Métodos para adição (`+`) |
| `sub`, `rsub` | Métodos para subtração (`-`) |
| `div`, `rdiv` | Métodos para divisão (`/`) |
| `floordiv`, `rfloordiv` | Métodos para divisão inteira (`//`) |
| `mul`, `rmul` | Métodos para multiplicação (`*`) |
| `pow`, `rpow` | Métodos para exponenciação (`**`) |


Consulte a tabela acima para obter uma lista de métodos `Series` e `DataFrame` para aritmética. Cada um tem uma contraparte, começando com a letra `r`, cujos argumentos são invertidos. Portanto, essas duas instruções são equivalentes:

In [301]:
1 / df_1

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [302]:
df_1.rdiv(1)

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

Da mesma forma, ao reindexar uma `Series` ou `DataFrame`, você também pode especificar um valor de preenchimento diferente:

In [303]:
df_1.reindex(columns=df_2.columns, fill_value=0)

     a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

Assim como acontece com arrays NumPy de diferentes dimensões, a aritmética entre `DataFrame` e `Series` também é definida. Primeiro, como exemplo motivador, considere a diferença entre uma matriz bidimensional e uma de suas linhas:

In [304]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [305]:
arr[0]

array([0., 1., 2., 3.])

In [306]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

Quando subtraímos `arr[0]` de `arr`, a subtração é realizada uma vez para cada linha via *broadcasting*. As operações entre um `DataFrame` e uma `Series` são semelhantes:

In [310]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), 
                    columns=list("bde"),
                    index=["Utah", "Ohio", "Texas", "Oregon"])

frame

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [308]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

Por padrão, a aritmética entre `DataFrame` e `Series` corresponde ao índice da `Series` nas colunas do `DataFrame`, transmitindo para as linhas:

In [311]:
series_2 = pd.Series(np.arange(3), index=["b", "e", "f"])
series_2

b    0
e    1
f    2
dtype: int64

In [312]:
frame

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [313]:
frame + series_2

          b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

Se, em vez disso, você quiser transmitir as colunas, correspondendo às linhas, precisará usar um dos métodos aritméticos e especificar a correspondência por índice. Por exemplo:

In [314]:
series_3 = frame["d"]

In [315]:
frame

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [316]:
series_3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [317]:
frame.sub(series_3, axis="index")

          b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

O eixo que você passa é o eixo para correspondência. Neste caso, queremos corresponder ao índice de linha do `DataFrame` (`axis="index"`) e transmitir para as colunas.

#### 2.3.5. Aplicação e Mapeamento de Funções

As funções universais (`ufuncs`) NumPy (métodos de array elemento a elemento) também funcionam com objetos Pandas:

In [318]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)), 
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
frame

               b         d         e
Utah   -1.097923  1.664573 -0.432982
Ohio    0.930528  1.386454  0.572619
Texas  -1.197191  0.483319 -0.805817
Oregon -0.561405 -0.125685 -0.363378

In [319]:
np.abs(frame)

               b         d         e
Utah    1.097923  1.664573  0.432982
Ohio    0.930528  1.386454  0.572619
Texas   1.197191  0.483319  0.805817
Oregon  0.561405  0.125685  0.363378

Outra operação frequente é aplicar uma função em arrays unidimensionais a cada coluna ou linha. O método `apply` do `DataFrame` faz exatamente isso:

In [320]:
def f1(x):
    return x.max() - x.min()

In [321]:
frame.apply(f1)

b    2.127718
d    1.790258
e    1.378435
dtype: float64

Aqui, a função `f1`, que calcula a diferença entre o máximo e o mínimo de uma série, é invocada uma vez em cada coluna do `frame`. O resultado é uma `Series` que tem as colunas do `frame` como índice.

Se você passar `axis="columns"` para `apply`, a função será invocada uma vez por linha. Uma maneira útil de pensar nisso é como `"aplicar em todas as colunas"`:

In [322]:
frame.apply(f1, axis="columns")

Utah      2.762496
Ohio      0.813835
Texas     1.680510
Oregon    0.435720
dtype: float64

Muitas das estatísticas de arrays mais comuns (como `sum` e `mean`) são métodos `DataFrame`, portanto, não é necessário usar `apply`.

A função passada para `apply` não precisa retornar um valor escalar; ela também pode retornar uma `Series` com vários valores:

In [323]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])

In [324]:
frame.apply(f2)

            b         d         e
min -1.197191 -0.125685 -0.805817
max  0.930528  1.664573  0.572619

Funções Python elementares também podem ser usadas. Suponha que você queira calcular uma string formatada a partir de cada valor de ponto flutuante do `frame`. Você pode fazer isso com  `map`:

In [325]:
def my_format(x):
    return f"{x:.2f}"

In [326]:
frame.map(my_format)

            b      d      e
Utah    -1.10   1.66  -0.43
Ohio     0.93   1.39   0.57
Texas   -1.20   0.48  -0.81
Oregon  -0.56  -0.13  -0.36

Você pode aplicar `map` à uma coluna específica do `frame`:

In [327]:
frame["e"].map(my_format)

Utah      -0.43
Ohio       0.57
Texas     -0.81
Oregon    -0.36
Name: e, dtype: object

#### 2.3.6. Ordenação e Ranqueamento

Classificar um conjunto de dados por algum critério é outra operação interna importante. Para classificar *lexicograficamente* por rótulo de linha ou coluna, use o método `sort_index`, que retorna um novo objeto classificado:

In [328]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [329]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

Com um `DataFrame`, você pode classificar por índice em qualquer eixo:

In [330]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), 
                     index=["three", "one"], 
                     columns=["d", "a", "b", "c"])
frame

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [331]:
frame.sort_index()

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [332]:
frame.sort_index(axis="columns") # equivalente a axis=1

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

Os dados são classificados em ordem crescente por padrão, mas também podem ser classificados em ordem decrescente:

In [333]:
frame.sort_index(axis="columns", ascending=False)

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

Para classificar uma série por seus valores, use seu método `sort_values`:

In [334]:
obj = pd.Series([4, 7, -3, 2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [335]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

Quaisquer valores ausentes são classificados no final da `Series` por padrão:

In [336]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [337]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

Os valores ausentes podem ser classificados desde o início usando a opção `na_position`:

In [338]:
obj.sort_values(na_position="first")

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

Ao classificar um `DataFrame`, você pode usar os dados de uma ou mais colunas como chaves de classificação. Para isso, passe um ou mais nomes de colunas para `sort_values`:

In [339]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})
frame

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [340]:
frame.sort_values("b")

   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

Para classificar por várias colunas, passe uma lista de nomes:

In [341]:
frame.sort_values(["a", "b"])

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1

O *ranqueamento* atribui classificações de um até o número de pontos de dados válidos em um array, começando pelo menor valor. Os métodos de ranqueamento para `Series` e `DataFrame` são os mais indicados; por padrão, o ranque desempata atribuindo a cada grupo o ranque médio:

In [ ]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

In [ ]:
obj.sort_values()

In [ ]:
obj.rank()

As ranques também podem ser atribuídos de acordo com a ordem em que são observadas nos
dados:

In [ ]:
obj.rank(method="first")

Aqui, em vez de usar ranque médio `6.5` ​​para as entradas `0` e `2`, elas foram definidas como `6` e `7` porque o rótulo `0` precede o rótulo `2` nos dados. 

Você também pode ranquear em ordem decrescente:

In [ ]:
obj.rank(ascending=False)

A tabela abaixo apresenta uma lista de métodos de desempate disponíveis.

| Método | Descrição |
|---------|------------|
| `"average"` | Padrão: atribui a média das posições (ranks) a cada elemento dentro do grupo de valores iguais. |
| `"min"` | Usa a menor posição (rank) para todo o grupo de valores iguais. |
| `"max"` | Usa a maior posição (rank) para todo o grupo de valores iguais. |
| `"first"` | Atribui as posições na ordem em que os valores aparecem nos dados. |
| `"dense"` | Similar a `method="min"`, mas as posições sempre aumentam de 1 entre os grupos, em vez de depender do número de elementos iguais em cada grupo. |

O `DataFrame` pode calcular ranques sobre as linhas ou colunas:

In [ ]:
frame = pd.DataFrame({"b": [4.3, 7, -3, 2], "a": [0, 1, 0, 1], "c": [-2, 5, 8, -2.5]})
frame

In [ ]:
frame.rank(axis="columns")

#### 2.3.7. Índices de Eixo com Rótulos Duplicados

Até agora, quase todos os exemplos que analisamos têm rótulos de eixo exclusivos (valores de índice). Embora muitas funções do Pandas (como `reindex`) exijam que os rótulos sejam exclusivos, isso não é obrigatório. Vamos considerar uma pequena `Series` com índices duplicados:

In [342]:
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

A propriedade `is_unique` do índice pode informar se seus rótulos são exclusivos ou não:

In [343]:
obj.index.is_unique

False

A seleção de dados é um dos principais fatores que se comportam de forma diferente com duplicatas. Indexar um rótulo (índice) com múltiplas entradas retorna uma `Series`, enquanto entradas únicas retornam um valor escalar:

In [344]:
obj["a"]

a    0
a    1
dtype: int64

In [345]:
obj["c"]

np.int64(4)

Isso pode tornar seu código mais complexo, pois o tipo de saída da indexação pode variar dependendo da repetição ou não de um rótulo.

A mesma lógica se aplica à indexação de linhas (ou colunas) em um `DataFrame`:

In [346]:
df = pd.DataFrame(np.random.standard_normal((5, 3)), index=["a", "a", "b", "b", "c"])
df

          0         1         2
a -0.241717  0.551348  0.108024
a  1.695031 -1.020038 -0.557317
b  0.174232  0.742459 -0.612827
b -0.908796 -0.649125  0.308537
c -0.108162  0.444057  0.990102

In [347]:
df.loc["b"]

          0         1         2
b  0.174232  0.742459 -0.612827
b -0.908796 -0.649125  0.308537

In [348]:
df.loc["c"]

0   -0.108162
1    0.444057
2    0.990102
Name: c, dtype: float64

### 2.4. Sumarizando e Calculando Estatísticas Descritivas

Objetos Pandas são equipados com um conjunto de métodos matemáticos e estatísticos comuns. A maioria deles se enquadra na categoria de reduções ou estatísticas de resumo, métodos que extraem um único valor (como a soma ou a média) de uma série, ou uma série de valores das linhas ou colunas de um `DataFrame`. Em comparação com métodos semelhantes encontrados em arrays NumPy, eles possuem tratamento integrado para dados ausentes.

#### 2.4.1 Visão Geral

Considere um pequeno `DataFrame`:

In [349]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], 
                  index=["a", "b", "c", "d"], 
                  columns=["one", "two"])
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

Chamar o método `sum` do `DataFrame` retorna uma série contendo somas de colunas:

In [350]:
df.sum()

one    9.25
two   -5.80
dtype: float64

Passando somas `axis="columns"` ou `axis=1` entre as colunas:

In [351]:
df.sum(axis="columns")

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

Quando uma linha ou coluna inteira contém todos os valores `NA`, a soma é `0`, enquanto se algum valor não for `NA`, o resultado será `NA`. Isso pode ser desabilitado com a opção `skipna`, caso em que qualquer valor `NA` em uma linha ou coluna nomeia o resultado correspondente `NA`:

In [ ]:
df.sum(axis="index", skipna=False)

In [ ]:
df.sum(axis="columns", skipna=False)

Algumas agregações, como mean, exigem pelo menos um valor não-`NA` para produzir um resultado de valor, então aqui temos:

In [352]:
df.mean(axis="columns")

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

A tabela abaixo traz uma lista de opções comuns para cada método de redução.

| Método | Descrição |
|---------|------------|
| `axis` | Eixo a ser reduzido; use `"index"` para linhas de um DataFrame e `"columns"` para colunas. |
| `skipna` | Exclui valores ausentes (`NaN`); o padrão é `True`. |
| `level` | Reduz agrupando por nível se o eixo for hierarquicamente indexado (`MultiIndex`). |

Alguns métodos, como `idxmin` e `idxmax`, retornam estatísticas indiretas, como o valor do índice onde os valores mínimos ou máximos são atingidos:

In [353]:
df.idxmax()

one    b
two    d
dtype: object

In [354]:
df.idxmin()

one    d
two    b
dtype: object

Outros métodos são acumulações:

In [355]:
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [356]:
df.cumsum()

    one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

Alguns métodos não são nem reduções nem acumulações. `describe` é um exemplo disso, produzindo múltiplas estatísticas de resumo de uma só vez:

In [ ]:
df.describe()

Em dados não numéricos, describe produz estatísticas de resumo alternativas:

In [357]:
obj = pd.Series(["a", "a", "b", "c"] * 4)
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [358]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object


A tabela abaixo apresenta uma lista completa de estatísticas resumidas e métodos relacionados.

| Método | Descrição |
|---------|------------|
| `count` | Conta o número de valores não nulos (`non-NA`). |
| `describe` | Calcula um conjunto de estatísticas descritivas resumidas. |
| `min, max` | Calcula os valores mínimo e máximo. |
| `argmin, argmax` | Retorna os índices (posições inteiras) onde o valor mínimo ou máximo é obtido, respectivamente (não disponível para objetos `DataFrame`). |
| `idxmin, idxmax` | Retorna os rótulos dos índices onde o valor mínimo ou máximo é obtido, respectivamente. |
| `quantile` | Calcula o quantil amostral, variando de 0 a 1 (padrão: 0,5). |
| `sum` | Calcula a soma dos valores. |
| `mean` | Calcula a média dos valores. |
| `median` | Calcula a mediana aritmética (quantil de 50%). |
| `mad` | Calcula o desvio absoluto médio em relação à média. |
| `prod` | Calcula o produto de todos os valores. |
| `var` | Calcula a variância amostral dos valores. |
| `std` | Calcula o desvio padrão amostral dos valores. |
| `skew` | Calcula a assimetria amostral (terceiro momento dos valores). |
| `kurt` | Calcula a curtose amostral (quarto momento dos valores). |
| `cumsum` | Calcula a soma cumulativa dos valores. |
| `cummin, cummax` | Calcula o mínimo ou máximo cumulativo dos valores, respectivamente. |
| `cumprod` | Calcula o produto cumulativo dos valores. |
| `diff` | Calcula a primeira diferença aritmética (útil em séries temporais). |
| `pct_change` | Calcula a variação percentual entre os valores. |

#### 2.4.2. Correlação e Covariância

Algumas estatísticas resumidas, como correlação e covariância, são calculadas a partir de pares de argumentos. Vamos considerar alguns DataFrames de preços e volumes de ações obtidos originalmente do **Yahoo! Finance** e disponíveis em arquivos Python Pickle:

In [ ]:
price = pd.read_pickle("./files/yahoo_price.pkl")

In [ ]:
volume = pd.read_pickle("./files/yahoo_volume.pkl")

Agora iremos calcular as variações percentuais dos preços, uma operação de séries temporais que será explorada mais detalhadamente no Módulo 7 deste curso:

In [ ]:
returns = price.pct_change()

In [ ]:
returns.tail()

O método `corr` de `Series` calcula a correlação dos valores sobrepostos, não `NA` e alinhados por índice em duas `Series`. Da mesma forma, `cov` calcula a covariância:

In [ ]:
returns["MSFT"].corr(returns["IBM"])

In [ ]:
returns["MSFT"].cov(returns["IBM"])

Como `MSFT` é um nome de variável Python válido, também podemos selecionar essas colunas usando uma sintaxe mais concisa:

In [ ]:
returns.MSFT.corr(returns.IBM)

Os métodos `corr` e `cov` do `DataFrame`, por outro lado, retornam uma matriz de correlação ou covariância completa como um `DataFrame`, respectivamente:

In [ ]:
returns.corr()

Usando o método `corrwith` do `DataFrame`, você pode calcular correlações em pares entre as colunas ou linhas de um `DataFrame` com outra `Serie` ou `DataFrame`. Passar uma `Serie` retorna uma `Serie` com o valor de correlação calculado para cada coluna:

In [ ]:
returns.corrwith(returns["IBM"])

A passagem de um `DataFrame` calcula as correlações entre os nomes de colunas correspondentes. Aqui, é feito o cálculo as correlações das variações percentuais com o volume:

In [ ]:
returns.corrwith(volume)

Passar `axis="columns"` faz as coisas linha por linha. Em todos os casos, os pontos de dados são alinhados por rótulo antes que a correlação seja calculada.

#### 2.4.3. Valores Únicos, Contagens de Valor e Associação

Outra classe de métodos relacionados extrai informações sobre os valores contidos em uma `Series` unidimensional. Para ilustrá-los, considere este exemplo:

In [ ]:
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])

A primeira função é única, o que fornece uma matriz de valores exclusivos em uma `Series`:

In [359]:
uniques = obj.unique()
uniques

array(['a', 'b', 'c'], dtype=object)

Os valores únicos não são necessariamente retornados na ordem em que aparecem pela primeira vez, nem em ordem de classificação, mas podem ser classificados posteriormente, se necessário (`uniques.sort()`). Da mesma forma, `value_counts` calcula uma série contendo frequências de valores:

In [360]:
obj.value_counts()

a    8
b    4
c    4
Name: count, dtype: int64

A `Series` é classificada por valor em ordem decrescente por conveniência. `value_counts` também está disponível como um método Pandas de nível superior que pode ser usado com arrays NumPy ou outras sequências Python:

In [361]:
pd.Series(obj.to_numpy()).value_counts()

a    8
b    4
c    4
Name: count, dtype: int64

`isin` executa uma verificação de associação de conjunto vetorizado e pode ser útil para filtrar um conjunto de dados para um subconjunto de valores em uma série ou coluna em um `DataFrame`:

In [362]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [363]:
mask = obj.isin(["b", "c"])
mask

0     False
1     False
2      True
3      True
4     False
5     False
6      True
7      True
8     False
9     False
10     True
11     True
12    False
13    False
14     True
15     True
dtype: bool

In [364]:
obj[mask]

2     b
3     c
6     b
7     c
10    b
11    c
14    b
15    c
dtype: object

Relacionado ao `isin` está o método `Index.get_indexer`, que fornece uma matriz de índices de um array de valores possivelmente não distintos para outro array de valores distintos:

In [365]:
to_match = pd.Series(["c", "a", "b", "b", "c", "a"])
to_match

0    c
1    a
2    b
3    b
4    c
5    a
dtype: object

In [366]:
unique_vals = pd.Series(["c", "b", "a"])
unique_vals

0    c
1    b
2    a
dtype: object

In [367]:
indices = pd.Index(unique_vals).get_indexer(to_match)
indices

array([0, 2, 1, 1, 0, 2])

Consulte a tabela abaixo para obter uma referência sobre esses métodos.

| Método | Descrição |
|---------|------------|
| `isin` | Calcula um array booleano indicando se cada valor de uma `Series` ou `DataFrame` está contido na sequência de valores passada. |
| `get_indexer` | Calcula índices inteiros para cada valor de um array dentro de outro array de valores distintos; útil para operações de alinhamento de dados e junções (`join`). |
| `unique` | Retorna um array com os valores únicos de uma `Series`, preservando a ordem em que aparecem. |
| `value_counts` | Retorna uma `Series` contendo os valores únicos como índice e suas frequências como valores, ordenadas em ordem decrescente de contagem. |


Em alguns casos, você pode querer calcular um histograma em várias colunas relacionadas em um `DataFrame`. Veja um exemplo:

In [368]:
data = pd.DataFrame({"Qu1": [1, 3, 4, 3, 4],
                     "Qu2": [2, 3, 1, 2, 3],
                     "Qu3": [1, 5, 2, 4, 4]})

data

   Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

Podemos calcular as contagens de valores para uma única coluna, assim:

In [369]:
data["Qu1"].value_counts().sort_index()

Qu1
1    1
3    2
4    2
Name: count, dtype: int64

Para calcular isso para todas as colunas, passe `pandas.Series.value_counts` para o método `apply` do `DataFrame`:

In [370]:
result = data.apply(pd.Series.value_counts).fillna(0)
result

   Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

Aqui, os rótulos das linhas no resultado são os valores distintos que ocorrem em todas as colunas. Os valores são as respectivas contagens desses valores em cada coluna.

Há também um método `DataFrame.value_counts`, mas ele calcula as contagens considerando cada linha do `DataFrame` como uma tupla para determinar o número de ocorrências de cada linha distinta:

In [371]:
data = pd.DataFrame({"a": [1, 1, 1, 2, 2], "b": [0, 0, 1, 0, 0]})
data

   a  b
0  1  0
1  1  0
2  1  1
3  2  0
4  2  0

In [372]:
data.value_counts()

a  b
1  0    2
2  0    2
1  1    1
Name: count, dtype: int64

Nesse caso, o resultado tem um índice que representa as linhas distintas como um índice hierárquico, um tópico que exploraremos com mais detalhes no Módulo 5.

### 2.5. Exercícios

In [1]:
# Esta célula informa ao Jupyter para fornecer informações detalhadas de depuração
# quando ocorrer um erro de execução. Execute-o antes de trabalhar nos exercícios.

%xmode Verbose

Exception reporting mode: Verbose

In [4]:
import numpy as np
import pandas as pd

#### 2.5.1. Exercício

Crie uma `Series` Pandas com os valores `[10, 20, 30, 40, 50]` e índices personalizados `['a', 'b', 'c', 'd', 'e']`. Mostre:
- O valor associado ao índice `'c'`
- O tipo de dados (`dtype`)
- O `Index` da série

In [8]:
s = pd.Series([10, 20, 30, 40, 50], index=['a', 'b', 'c', 'd', 'e'])
print(s)
print()
print(f"Coluna 'c': {s['c']}")
print(f"Tipo da Series: {s.dtype}")
print(f"Index da Series: {s.index}")

a    10
b    20
c    30
d    40
e    50
dtype: int64

Coluna 'c': 30
Tipo da Series: int64
Index da Series: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

#### 2.5.2 Exercício

Crie um `DataFrame` com os dados:
- `nome`: `['Ana', 'Bruno', 'Carlos', 'Diana']`
- `idade`: `[23, 35, 19, 42]`
- `cidade`: `['Fortaleza', 'São Paulo', 'Recife', 'Manaus']`

Exiba:
- As duas primeiras linhas usando `head()`
- A coluna `cidade` como uma `Series`
- A idade média dos participantes

In [10]:
data = {"name": ["Ana", "Bruno", "Carlos", "Diana"],
        "age": [23, 35, 19, 42],
        "city": ["Fortaleza", "São Paulo", "Recife", "Manaus"]}
df = pd.DataFrame(data)
df

     name  age       city
0     Ana   23  Fortaleza
1   Bruno   35  São Paulo
2  Carlos   19     Recife
3   Diana   42     Manaus

In [11]:
df.head(2)

    name  age       city
0    Ana   23  Fortaleza
1  Bruno   35  São Paulo

In [12]:
pd.Series(df['city'])

0    Fortaleza
1    São Paulo
2       Recife
3       Manaus
Name: city, dtype: object

In [13]:
np.mean(df['age'])

np.float64(29.75)

#### 2.5.3 Exercício

Utilize o método `sort_values` para ordenar o `DataFrame` do exercício anterior pela coluna `idade` em ordem decrescente. Mostre o resultado.

In [14]:
df.sort_values("age", ascending=False)

     name  age       city
3   Diana   42     Manaus
1   Bruno   35  São Paulo
0     Ana   23  Fortaleza
2  Carlos   19     Recife

#### 2.5.4 Exercício

Crie uma `Series` com valores repetidos e utilize os métodos `unique` e `value_counts` para mostrar:
- Os valores únicos
- A contagem de cada valor

In [17]:
s = pd.Series([1, 1, 2, 3, 4, 5, 5, 5, 5, 5, 8, 9, 5, 5, 2, 3, 4, 5, 6, 9, 7, 6, 6, 5, 1, 2, 3, 4, 4, 5, 5])
print(s.unique())
print(s.value_counts())

[1 2 3 4 5 8 9 6 7]
5    11
4     4
1     3
3     3
2     3
6     3
9     2
8     1
7     1
Name: count, dtype: int64

#### 2.5.5 Exercício

Utilize o arquivo `./files/yahoo_price.pkl` para ler um `DataFrame` de preços de ações. Em seguida:
- Exiba as 5 primeiras linhas.
- Filtre apenas as colunas que começam com a letra `"A"` (use `filter` ou seleção por coluna).
- Calcule a média dos preços para cada coluna filtrada.

Dica! A função `.filter()` pode receber como parâmentro uma expressão regular (`regex`) e o eixo que se deseja fazer a filtragem (`axis`). Por exemplo, `.filter(regex='e$', axis=1)` filtra colunas cujos nomes terminam e com a letra `e`. Veja
 a [documentação oficial de `filter`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.filter.html).

In [18]:
prices = pd.read_pickle("/home/samuelmalves/Documents/Dev/Python/CTE-IA/prog-ciencia-de-dados/aulas/files/yahoo_price.pkl")

prices.head()

                 AAPL        GOOG         IBM       MSFT
Date
2010-01-04  27.990226  313.062468  113.304536  25.884104
2010-01-05  28.038618  311.683844  111.935822  25.892466
2010-01-06  27.592626  303.826685  111.208683  25.733566
2010-01-07  27.541619  296.753749  110.823732  25.465944
2010-01-08  27.724725  300.709808  111.935822  25.641571

In [21]:
new_frame = prices.filter(regex="^A")
new_frame

                  AAPL
Date
2010-01-04   27.990226
2010-01-05   28.038618
2010-01-06   27.592626
2010-01-07   27.541619
2010-01-08   27.724725
...                ...
2016-10-17  117.550003
2016-10-18  117.470001
2016-10-19  117.120003
2016-10-20  117.059998
2016-10-21  116.599998

[1714 rows x 1 columns]

In [22]:
new_frame.mean()

AAPL    74.665633
dtype: float64

#### 2.5.6 Exercício

Carregue o arquivo `./files/yahoo_price.pkl` em um `DataFrame`. Faça o seguinte:
- Identifique todas as linhas que possuem valores ausentes (`NaN`) em qualquer coluna.
- Remova essas linhas do `DataFrame`.
- Mostre o número de linhas antes e depois da remoção.

In [43]:
prices = pd.read_pickle("/home/samuelmalves/Documents/Dev/Python/CTE-IA/prog-ciencia-de-dados/aulas/files/yahoo_price.pkl")
prices_before = len(prices)

mask = prices.isna().any(axis=1)
new_prices = prices[~mask]
prices_after = len(new_prices)

print(f"Prices before: {prices_before}, Prices after: {prices_after}")

Prices before: 1714, Prices after: 1714

#### 2.5.7 Exercício

Leia o arquivo `./files/yahoo_price.pkl` em um `DataFrame`. Suponha que alguns valores estejam ausentes (`NaN`). Realize:
- Preencha os valores ausentes com o valor anterior da mesma coluna (`method="ffill"`).
- Calcule o desvio padrão dos preços para cada coluna após o preenchimento.
- Exiba as 3 colunas com maior desvio padrão.

In [65]:
prices = pd.read_pickle("/home/samuelmalves/Documents/Dev/Python/CTE-IA/prog-ciencia-de-dados/aulas/files/yahoo_price.pkl")

stds = []
index = []
for col in prices.columns:
    index.append(col)
    stds.append(prices[col].std())

s = pd.Series(stds, index=index)
print(s.sort_values()[0:3])

MSFT    11.234714
IBM     22.746468
AAPL    28.544699
dtype: float64

## 3. Estudo de Caso

Nesta seção vamos realizar um estudo de caso explorando o conjunto de dados históricos sobre os Jogos Olímpicos modernos, incluindo todos os Jogos de Atenas 1896 até o Rio 2016. Você pode acessar o dicionário direto do [repositório do Kaggle](https://www.kaggle.com/datasets/heesoo37/120-years-of-olympic-history-athletes-and-results).

Veja os metadados:

| Campo    | Descrição                                 |
|:--------:|:-----------------------------------------:|
| ID       | Unique number for each athlete            |
| Name     | Athlete's name                            |
| Sex      | M or F                                    |
| Age      | Integer                                   |
| Height   | In centimeters                            |
| Weight   | In kilograms                              |
| Team     | Team name                                 |
| NOC      | National Olympic Committee 3-letter code  |
| Games    | Year and season                           |
| Year     | Integer                                   |
| Season   | Summer or Winter                          |
| City     | Host city                                 |
| Sport    | Sport                                     |
| Event    | Event                                     |
| Medal    | Gold, Silver, Bronze, or NA               |

### 3.1. Carregando dados de arquivo CSV em um DataFrame

In [67]:
import pandas as pd

df_atletas_eventos = pd.read_csv("/home/samuelmalves/Documents/Dev/Python/CTE-IA/prog-ciencia-de-dados/aulas/files/atletas_eventos_olimpiadas.csv")

In [68]:
df_atletas_eventos.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [69]:
df_atletas_eventos.describe()

,ID,Age,Height,Weight,Year
count,271116.000000,261642.000000,210945.000000,208241.000000,271116.000000
mean,68248.954396,25.556898,175.338970,70.702393,1978.378480
std,39022.286345,6.393561,10.518462,14.348020,29.877632
min,1.000000,10.000000,127.000000,25.000000,1896.000000
25%,34643.000000,21.000000,168.000000,60.000000,1960.000000
50%,68205.000000,24.000000,175.000000,70.000000,1988.000000
75%,102097.250000,28.000000,183.000000,79.000000,2002.000000
max,135571.000000,97.000000,226.000000,214.000000,2016.000000

### 3.2. Exemplos de Informações Extraídas dos Dados

#### 3.2.1. Exemplo 01

Qual a idade mais comum entre atletas em toda a história dos jogos?
- Seleção de coluna, cálculo da Moda

In [70]:
moda_idade = df_atletas_eventos['Age'].mode()
print(f"A idade mais comum dos atletas é: {moda_idade[0]}")

A idade mais comum dos atletas é: 23.0

#### 3.2.2. Exemplo 02

Quantas participações estão registradas no dataset? Quantos atletas distintos?
- Contagem total, seleção de coluna, contagem única

In [71]:
total_participacoes = len(df_atletas_eventos)
total_atletas = df_atletas_eventos['ID'].nunique()

print(f"Total de participações: {total_participacoes}")
print(f"Total de atletas únicos: {total_atletas}")
print(f"O dataset possui {total_participacoes} registros de participação, "
      f"enquanto há {total_atletas} atletas únicos.")

Total de participações: 271116
Total de atletas únicos: 135571
O dataset possui 271116 registros de participação, enquanto há 135571 atletas únicos.

#### 3.2.3. Exemplo 03

Qual a/o atleta com mais participações em esportes? Qual a/o atleta com mais participações em edições?
- Agregação simples, contagem total, contagem única

In [72]:
# Atleta com mais participações em eventos
# Agrupa por atleta e conta o número de eventos
participacoes_por_evento = df_atletas_eventos.groupby('Name')['Event'].count()

participacoes_por_evento

Name
  Gabrielle Marie "Gabby" Adcock (White-)    1
 Eleonora Margarida Josephina Scmitt         2
 Jean Hauptmanns                             1
 Luis ngel Fernando de los Santos Grossi     5
 Th Anh                                      1
                                            ..
zge Krdar emberci                            1
zlem Kaya                                    2
zman Graud                                   1
zzet Safer                                   1
zzet nce                                     2
Name: Event, Length: 134732, dtype: int64

In [73]:
# Encontra o atleta com mais participações em eventos
atleta_mais_eventos = participacoes_por_evento.idxmax()
max_eventos = participacoes_por_evento.max()
print(f"Atleta com mais participações em eventos: {atleta_mais_eventos} ({max_eventos} eventos)")

Atleta com mais participações em eventos: Robert Tait McKenzie (58 eventos)

In [74]:
# Atleta com mais participações em jogos

# Agrupa por atleta e conta o número de jogos
participacoes_por_jogo = df_atletas_eventos.groupby('Name')['Games'].nunique()

# Encontra o atleta com mais participações em jogos
atleta_mais_jogos = participacoes_por_jogo.idxmax()
max_jogos = participacoes_por_jogo.max()
print(f"Atleta com mais participações em jogos: {atleta_mais_jogos} ({max_jogos} jogos)")

Atleta com mais participações em jogos: Ian Millar (10 jogos)

### 3.3. Exercícios

In [75]:
# Esta célula informa ao Jupyter para fornecer informações detalhadas de depuração
# quando ocorrer um erro de execução. Execute-o antes de trabalhar nos exercícios.

%xmode Verbose

Exception reporting mode: Verbose

#### 3.3.1. Exercício

Qual é a média de idade dos atletas que participaram das Olimpíadas em cada edição (ano)?
- Dica: agregação simples, cálculo de Média

In [76]:
avg_age_by_year = df_atletas_eventos.groupby('Year')['Age'].mean()
print(avg_age_by_year)

Year
1896    23.580645
1900    29.034031
1904    26.698150
1906    27.125253
1908    26.970228
1912    27.538620
1920    29.290978
1924    28.373325
1928    29.112557
1932    32.582080
1936    27.530328
1948    28.783947
1952    26.161546
1956    25.926674
1960    25.168848
1964    24.944397
1968    24.248046
1972    24.308607
1976    23.841818
1980    23.694743
1984    23.898347
1988    24.079432
1992    24.318895
1994    24.422103
1996    24.915045
1998    25.163197
2000    25.422504
2002    25.916281
2004    25.639515
2006    25.959151
2008    25.734118
2010    26.124262
2012    25.961378
2014    25.987324
2016    26.207919
Name: Age, dtype: float64

In [77]:
avg_age_by_games = df_atletas_eventos.groupby('Games')['Age'].mean()
print(avg_age_by_games)

Games
1896 Summer    23.580645
1900 Summer    29.034031
1904 Summer    26.698150
1906 Summer    27.125253
1908 Summer    26.970228
1912 Summer    27.538620
1920 Summer    29.290978
1924 Summer    28.449373
1924 Winter    27.590571
1928 Summer    29.414907
1928 Winter    26.581301
1932 Summer    33.451540
1932 Winter    25.547112
1936 Summer    27.878331
1936 Winter    25.048643
1948 Summer    29.304796
1948 Winter    26.239029
1952 Summer    26.258851
1952 Winter    25.446691
1956 Summer    26.033673
1956 Winter    25.549922
1960 Summer    25.298760
1960 Winter    24.241877
1964 Summer    25.065283
1964 Winter    24.419830
1968 Summer    24.255154
1968 Winter    24.215812
1972 Summer    24.341103
1972 Winter    24.107748
1976 Summer    23.863837
1976 Winter    23.739459
1980 Summer    23.704354
1980 Winter    23.656160
1984 Summer    24.002811
1984 Winter    23.443241
1988 Summer    24.132177
1988 Winter    23.840607
1992 Summer    24.396165
1992 Winter    24.027948
1994 Winter    24.422103
1996 Summer    24.915045
1998 Winter    25.163197
2000 Summer    25.422504
2002 Winter    25.916281
2004 Summer    25.639515
2006 Winter    25.959151
2008 Summer    25.734118
2010 Winter    26.124262
2012 Summer    25.961378
2014 Winter    25.987324
2016 Summer    26.207919
Name: Age, dtype: float64

#### 3.3.2. Exercício

Qual é o time com a maior média de altura de atletas na história das Olimpíadas?
- Dica: Agregação simples, cálculo de média, função máxima

In [78]:
avg_height_by_team = df_atletas_eventos.groupby('Team')['Height'].mean()
print(f"Team with highest average height: {avg_height_by_team.idxmax()}")
print(f"Highest height average: {avg_height_by_team.max()}")

Team with highest average height: Puerto Rico-1
Highest height average: 196.0

#### 3.3.3. Exercício

Qual é a distribuição de medalhas (Ouro, Prata, Bronze) entre homens e mulheres?
- Dica: Agregação composta, contagem

In [80]:
df_medalists = df_atletas_eventos[df_atletas_eventos['Medal'].notna()]
df_medalists.groupby(['Sex', 'Medal']).size().unstack(fill_value=0)

Medal  Bronze  Gold  Silver
Sex
F        3771  3747    3735
M        9524  9625    9381

#### 3.3.4. Exercício

Qual foi a/o atleta mais velha/o a ganhar uma medalha em cada esporte?
- Dica: Agregação simples, filtro, função máxima

In [81]:
medalists = df_atletas_eventos[df_atletas_eventos['Medal'].notna()]
oldest_medalist_by_sport = medalists.loc[medalists.groupby('Sport')['Age'].idxmax()]
oldest_medalist_by_sport[['Sport', 'Name', 'Age', 'Medal']]

,Sport,Name,Age,Medal
214105,Aeronautics,Hermann Schreiber,26.0,Gold
159147,Alpine Skiing,Samuel Bode Miller,36.0,Bronze
30323,Alpinism,Charles Granville Bruce,57.0,Gold
60403,Archery,Samuel Harding Duvall,68.0,Silver
44584,Art Competitions,John (Herbert Crawford-) Copley (Williamson-),73.0,Silver
...,...,...,...,...
38049,Tug-Of-War,Walter Chaffe,42.0,Silver
64678,Volleyball,"Srgio ""Escadinha"" Dutra dos Santos",40.0,Gold
82960,Water Polo,Boris Abramovich Goykhman,41.0,Silver
212544,Weightlifting,"Norbert ""Norb"" Schemansky",40.0,Bronze
136197,Wrestling,Eino Aukusti Leino,41.0,Bronze

#### 3.3.5. Exercício

Qual edição das Olimpíadas teve a maior variabilidade nas idades dos atletas?
- Dica: Agregação simples, cálculo de desvio padrão

In [82]:
age_deviation = df_atletas_eventos.groupby('Games')['Age'].std()
print(age_deviation)
greater_deviation_edition = age_deviation.idxmax()
print(f"Edition with greatest deviation: {greater_deviation_edition}")

Games
1896 Summer     4.692803
1900 Summer     9.358352
1904 Summer     8.752523
1906 Summer     7.913107
1908 Summer     7.820216
1912 Summer     8.052353
1920 Summer     8.273074
1924 Summer     8.607151
1924 Winter     6.998124
1928 Summer    10.905817
1928 Winter     6.091587
1932 Summer    14.242745
1932 Winter     5.783576
1936 Summer     8.745486
1936 Winter     4.903475
1948 Summer     9.656474
1948 Winter     5.701189
1952 Summer     6.620537
1952 Winter     5.161148
1956 Summer     6.563921
1956 Winter     5.092072
1960 Summer     6.171145
1960 Winter     4.481133
1964 Summer     5.654653
1964 Winter     4.665689
1968 Summer     6.026385
1968 Winter     4.326519
1972 Summer     5.994177
1972 Winter     4.470566
1976 Summer     5.727315
1976 Winter     4.665815
1980 Summer     5.269584
1980 Winter     4.260826
1984 Summer     5.482592
1984 Winter     4.049407
1988 Summer     5.399098
1988 Winter     4.178762
1992 Summer     5.407225
1992 Winter     4.133521
1994 Winter     4.195656
1996 Summer     5.501187
1998 Winter     4.438738
2000 Summer     5.440812
2002 Winter     4.715602
2004 Summer     5.580091
2006 Winter     4.886329
2008 Summer     5.685902
2010 Winter     5.012074
2012 Summer     5.682124
2014 Winter     4.849456
2016 Summer     5.560367
Name: Age, dtype: float64
Edition with greatest deviation: 1932 Summer

#### 3.3.6. Exercício

Quais os 5 países com maior número de medalhas que nunca conquistaram um Ouro?

In [83]:
no_gold_medals = df_atletas_eventos[df_atletas_eventos["Medal"].isin(["Silver", "Bronze"])]
medal_count = no_gold_medals.groupby("Team")["Medal"].count()
countries_with_gold = df_atletas_eventos[df_atletas_eventos["Medal"].isin(["Gold"])]["Team"].unique()

no_gold_countries_count = medal_count[~medal_count.index.isin(countries_with_gold)]
no_gold_countries_count.sort_values(ascending=False).head()

Team
Soviet Union-2                        24
Phalainis ton Thorichtou "Hydra"-2    24
Ghana                                 23
Royal Club Nautique de Gand           21
Toronto Argonauts                     18
Name: Medal, dtype: int64