# Avaliação aulas 1 - 7 - Base Histórica Fictícia de Fórmula 1

## Objetivo

Você recebeu uma base histórica fictícia de Fórmula 1 com muitos anos de dados. Os nomes de pilotos, equipes e GPs são reais ou inspirados em nomes reais, mas os resultados, investimentos, patrocínios e métricas operacionais são fictícios.

A missão é transformar dados sujos em um relatório analítico confiável.

## Irão usar os métodos e funções que vimos nas aulas até então:

- **head()**, **tail()**, **info()**, **describe()**, **shape**, **columns**, **dtypes**, **isnull()**
- seleção de colunas, linhas, **loc**, **iloc**
- filtros, ordenação, criação/atualização de colunas, renomeação
- **isnull().sum()**, **dropna()**, **fillna()**, **duplicated()**, **drop_duplicates()**
- **astype()**, **replace()**, **str.lower()**, **str.strip()**, **str.upper()**
- **concat()**, **merge()**, **join()**
- **groupby** e agregações
- **MultiIndex**
- **pivot_table()** e **melt()**

---

In [1]:
import pandas as pd
import numpy as np

In [2]:
corridas_df = pd.read_csv('./data/f1/corridas.csv')
financeiro_df = pd.read_csv('./data/f1/financeiro.csv')
patrocinadores_df = pd.read_csv('./data/f1/patrocinadores.csv')
pilotos_df = pd.read_csv('./data/f1/pilotos.csv')
pitstops_df = pd.read_csv('./data/f1/pitstops.csv')
resultados_df = pd.read_csv('./data/f1/resultados.csv')

## 1 - Inspeção inicial

### head() e tail()

**Use **head()** e **tail()** em todas as bases. O que você percebe sobre a estrutura geral?**

In [3]:
corridas_df.head()

   id_corrida   ano  rodada                gp  pais_gp    clima  temperatura_c
0       10001  2014       1       BAHRAIN GP    Canadá  nublado           20.0
1       10002  2014       2  Saudi Arabian GP   México    chuva           15.0
2       10003  2014       3     Australian GP  Bélgica    misto           27.0
3       10004  2014       4       Japanese GP  Holanda    SECO            21.0
4       10005  2014       5        Chinese GP  Holanda     seco           31.0

In [4]:
corridas_df.tail()

,id_corrida,ano,rodada,gp,pais_gp,clima,temperatura_c
238,10239,2025,18,United States GP,Hungria,nublado,19.0
239,10240,2025,19,Mexican GP,Áustria,chuva,36.0
240,10241,2025,20,Brazilian GP,Singapura,misto,28.0
241,10242,2025,21,Las Vegas GP,Bélgica,nublado,24.0
242,10243,2025,22,Abu Dhabi GP,Espanha,seco,19.0

A coluna **corridas** possui uma coluna de identificação que pode resultar em possíveis inconsistências no momento de união com outras bases que necessitem destas. Também há inconsistência no título dos GPs e na descrição do clima. Não está explícito em relação ao país, mas é possível que haja problemas.

In [5]:
financeiro_df.head()

,ano,equipe,investimento_desenvolvimento_m USD,verba_patrocinadores_m USD,forca_carro_indice
0,2014,Mercedes,142.45,44.61,93.53
1,2014,Red Bull,284.27,108.17,95.81
2,2014,Ferrari,282.55,130.51,86.15
3,2014,McLaren,260.26,148.08,92.97
4,2014,williams,NaN,84.71,74.47

In [6]:
financeiro_df.tail()

,ano,equipe,investimento_desenvolvimento_m USD,verba_patrocinadores_m USD,forca_carro_indice
120,2016,Toro Rosso,172.36,89.53,61.28
121,2020,Racing Point,212.7,128.22,75.83
122,2024,sauber,183.16,81.54,62.50
123,2019,Ferrari,257.66,92.06,84.61
124,2020,Haas,177.67,123.79,63.44

Possíveis nomes problemáticos nas equipes e também título de colunas com nomes problemáticos (investimento_desenvolvimento_m USD e verba_patrocinadores_m USD)

In [7]:
patrocinadores_df.head()

    ano      equipe patrocinador categoria_patrocinio  valor_estimado_m USD
0  2014   MERCEDES      Petronas            logística                 27.20
1  2014    Mercedes        Ineos               master                 12.10
2  2014    Mercedes   TeamViewer          combustível                 52.69
3  2014    Red Bull       Oracle           tecnologia                 22.06
4  2014    Red Bull      Mobil 1            logística                 23.23

In [8]:
patrocinadores_df.tail()

      ano  equipe patrocinador categoria_patrocinio  valor_estimado_m USD
355  2025  Sauber   Alfa Romeo               master                 35.33
356  2025  Sauber        Claro          combustível                 43.20
357  2025    Haas    MoneyGram          combustível                 49.95
358  2025    Haas  Alpinestars          combustível                 25.01
359  2025    Haas      Pirelli          combustível                 12.63

Novamente, títulos de colunas com formato problemático e nomes inconsistentes para equipe explicitamente.

In [9]:
pilotos_df.head()

,ano,id_piloto,piloto,equipe,nacionalidade,idade,experiencia_anos
0,2014,1,Lewis Hamilton,Mercedes,Itália,37,3
1,2014,2,Nico Rosberg,Mercedes,Itália,39,6
2,2014,3,Sebastian Vettel,Red Bull,Espanha,30,6
3,2014,4,Daniel Ricciardo,red bull,Austrália,26,0
4,2014,5,fernando alonso,Ferrari,Brasil,37,0

In [10]:
pilotos_df.tail()

,ano,id_piloto,piloto,equipe,nacionalidade,idade,experiencia_anos
235,2025,51,Jack Doohan,Alpine,China,24,11
236,2025,12,Nico Hulkenberg,Sauber,China,27,15
237,2025,52,Gabriel Bortoleto,Sauber,FRANÇA,22,17
238,2025,30,Esteban Ocon,Haas,Alemanha,29,14
239,2025,53,OLIVER BEARMAN,Haas,Mônaco,34,16

Nomes inconsistentes para pilotos, nacionalidades e equipes.

In [11]:
pitstops_df.head()

,id_corrida,ano,id_piloto,piloto,equipe,numero_pit,tempo_pit_s
0,10001,2014,1,Lewis Hamilton,Mercedes,1,3.238
1,10001,2014,2,Nico Rosberg,Mercedes,1,2.768
2,10001,2014,2,Nico Rosberg,Mercedes,2,3.142
3,10001,2014,2,Nico Rosberg,Mercedes,3,2.913
4,10001,2014,3,Sebastian Vettel,Red Bull,1,2.664

In [12]:
pitstops_df.tail()

,id_corrida,ano,id_piloto,piloto,equipe,numero_pit,tempo_pit_s
8627,10049,2016,2,Nico Rosberg,Mercedes,2,2.497
8628,10158,2022,22,Carlos Sainz,Ferrari,2,2.691
8629,10179,2023,10,Valtteri Bottas,Alfa Romeo,1,3.185
8630,10230,2025,21,Max Verstappen,Red Bull,1,2.557
8631,10209,2024,12,Nico Hulkenberg,Haas,1,3.401

Os métodos head e tail não foram o suficiente para detectar inconsistências.

In [13]:
resultados_df.head()

,id_corrida,ano,gp,id_piloto,piloto,equipe,posicao_final,pontos,voltas_completadas,melhor_volta_s,tempo_total_min
0,10001,2014,Bahrain GP,1,Lewis Hamilton,Mercedes,1,25,50,92.446,97.289
1,10001,2014,Bahrain GP,2,Nico Rosberg,Mercedes,DNF,0,22,93.164,NaN
2,10001,2014,Bahrain GP,3,sebastian vettel,Red Bull,5,10,45,90.692,102.982
3,10001,2014,Bahrain GP,4,Daniel Ricciardo,Red Bull,10,1,44,86.723,94.113
4,10001,2014,Bahrain GP,5,Fernando Alonso,Ferrari,4,12,63,92.319,108.053

In [14]:
resultados_df.tail()

,id_corrida,ano,gp,id_piloto,piloto,equipe,posicao_final,pontos,voltas_completadas,melhor_volta_s,tempo_total_min
4880,10188,2023,Austrian GP,21,Max Verstappen,Red Bull,5,10,71,82.839,104.892
4881,10146,2021,Hungarian GP,1,Lewis Hamilton,MERCEDES,14,0,68,99.990,96.591
4882,10052,2016,Belgian GP,22,Carlos Sainz,Toro Rosso,16,0,48,91.453,106.329
4883,10180,2023,australian gp,29,Lance Stroll,ASTON MARTIN,8,4,65,91.378,112.983
4884,10029,2015,Spanish GP,2,Nico Rosberg,Mercedes,6,8,51,90.706,95.474

Nomes inconsistentes de equipes, pilotos e GPs

### info()

**Use **info()** em todas as bases. Liste colunas com tipos problemáticos.**

In [15]:
corridas_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_corrida     243 non-null    int64
 1   ano            243 non-null    int64
 2   rodada         243 non-null    int64
 3   gp             243 non-null    str
 4   pais_gp        243 non-null    str
 5   clima          243 non-null    str
 6   temperatura_c  240 non-null    float64
dtypes: float64(1), int64(3), str(3)
memory usage: 19.3 KB

In [16]:
financeiro_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 5 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ano                                 125 non-null    int64
 1   equipe                              125 non-null    str
 2   investimento_desenvolvimento_m USD  124 non-null    str
 3   verba_patrocinadores_m USD          125 non-null    float64
 4   forca_carro_indice                  125 non-null    float64
dtypes: float64(2), int64(1), str(2)
memory usage: 6.7 KB

**investimento_desenvolvimento_m USD** possui tipo problemático (str e deveria ser float64)

In [17]:
patrocinadores_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ano                   360 non-null    int64
 1   equipe                360 non-null    str
 2   patrocinador          360 non-null    str
 3   categoria_patrocinio  360 non-null    str
 4   valor_estimado_m USD  360 non-null    float64
dtypes: float64(1), int64(1), str(3)
memory usage: 22.5 KB

In [18]:
pilotos_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ano               240 non-null    int64
 1   id_piloto         240 non-null    int64
 2   piloto            240 non-null    str
 3   equipe            240 non-null    str
 4   nacionalidade     240 non-null    str
 5   idade             237 non-null    str
 6   experiencia_anos  240 non-null    int64
dtypes: int64(3), str(4)
memory usage: 20.7 KB

A coluna **idade** está problemática (como str quando deveria ser float64)

In [19]:
pitstops_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8632 entries, 0 to 8631
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_corrida   8632 non-null   int64
 1   ano          8632 non-null   int64
 2   id_piloto    8632 non-null   int64
 3   piloto       8632 non-null   str
 4   equipe       8632 non-null   str
 5   numero_pit   8632 non-null   int64
 6   tempo_pit_s  8545 non-null   float64
dtypes: float64(1), int64(4), str(2)
memory usage: 652.9 KB

In [20]:
resultados_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4885 entries, 0 to 4884
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_corrida          4885 non-null   int64
 1   ano                 4885 non-null   int64
 2   gp                  4885 non-null   str
 3   id_piloto           4885 non-null   int64
 4   piloto              4885 non-null   str
 5   equipe              4885 non-null   str
 6   posicao_final       4885 non-null   str
 7   pontos              4885 non-null   int64
 8   voltas_completadas  4885 non-null   int64
 9   melhor_volta_s      4885 non-null   float64
 10  tempo_total_min     4511 non-null   float64
dtypes: float64(2), int64(5), str(4)
memory usage: 586.3 KB

A coluna **posicao_final** possui valor problemático (str quando deveria ser int64)

### shape, columns e dtypes

**Use **shape**, **columns** e **dtypes** em **resultados**, **financeiro** e **pitstops**.**

In [21]:
print(f'Corridas: {corridas_df.shape[0]} linhas e {corridas_df.shape[1]} colunas')
print(f'Colunas de Corridas: {corridas_df.columns}')
corridas_df.dtypes

Corridas: 243 linhas e 7 colunas
Colunas de Corridas: Index(['id_corrida', 'ano', 'rodada', 'gp', 'pais_gp', 'clima',
       'temperatura_c'],
      dtype='str')

id_corrida         int64
ano                int64
rodada             int64
gp                   str
pais_gp              str
clima                str
temperatura_c    float64
dtype: object

In [22]:
print(f'Financeiro: {financeiro_df.shape[0]} linhas e {corridas_df.shape[1]} colunas')
print(f'Colunas de Financeiro: {financeiro_df.columns}')
financeiro_df.dtypes

Financeiro: 125 linhas e 7 colunas
Colunas de Financeiro: Index(['ano', 'equipe', 'investimento_desenvolvimento_m USD',
       'verba_patrocinadores_m USD', 'forca_carro_indice'],
      dtype='str')

ano                                     int64
equipe                                    str
investimento_desenvolvimento_m USD        str
verba_patrocinadores_m USD            float64
forca_carro_indice                    float64
dtype: object

In [23]:
print(f'Patrocinadores: {patrocinadores_df.shape[0]} linhas e {patrocinadores_df.shape[1]} colunas')
print(f'Colunas de Patrocinadores: {patrocinadores_df.columns}')
patrocinadores_df.dtypes

Patrocinadores: 360 linhas e 5 colunas
Colunas de Patrocinadores: Index(['ano', 'equipe', 'patrocinador', 'categoria_patrocinio',
       'valor_estimado_m USD'],
      dtype='str')

ano                       int64
equipe                      str
patrocinador                str
categoria_patrocinio        str
valor_estimado_m USD    float64
dtype: object

In [24]:
print(f'Pilotos: {pilotos_df.shape[0]} linhas e {pilotos_df.shape[1]} colunas')
print(f'Colunas de Pilotos: {pilotos_df.columns}')
pilotos_df.dtypes

Pilotos: 240 linhas e 7 colunas
Colunas de Pilotos: Index(['ano', 'id_piloto', 'piloto', 'equipe', 'nacionalidade', 'idade',
       'experiencia_anos'],
      dtype='str')

ano                 int64
id_piloto           int64
piloto                str
equipe                str
nacionalidade         str
idade                 str
experiencia_anos    int64
dtype: object

In [25]:
print(f'Pitstops: {pilotos_df.shape[0]} linhas e {pitstops_df.shape[1]} colunas')
print(f'Colunas de Pitstops: {pitstops_df.columns}')
pitstops_df.dtypes

Pitstops: 240 linhas e 7 colunas
Colunas de Pitstops: Index(['id_corrida', 'ano', 'id_piloto', 'piloto', 'equipe', 'numero_pit',
       'tempo_pit_s'],
      dtype='str')

id_corrida       int64
ano              int64
id_piloto        int64
piloto             str
equipe             str
numero_pit       int64
tempo_pit_s    float64
dtype: object

In [26]:
print(f'Resultados: {resultados_df.shape[0]} linhas e {resultados_df.shape[1]} colunas')
print(f'Colunas dos Resultados: {resultados_df.columns}')
resultados_df.dtypes

Resultados: 4885 linhas e 11 colunas
Colunas dos Resultados: Index(['id_corrida', 'ano', 'gp', 'id_piloto', 'piloto', 'equipe',
       'posicao_final', 'pontos', 'voltas_completadas', 'melhor_volta_s',
       'tempo_total_min'],
      dtype='str')

id_corrida              int64
ano                     int64
gp                        str
id_piloto               int64
piloto                    str
equipe                    str
posicao_final             str
pontos                  int64
voltas_completadas      int64
melhor_volta_s        float64
tempo_total_min       float64
dtype: object

### describe()

In [27]:
resultados_df.describe()

,id_corrida,ano,id_piloto,pontos,voltas_completadas,melhor_volta_s,tempo_total_min
count,4885.000000,4885.000000,4885.000000,4885.000000,4885.000000,4885.000000,4511.000000
mean,10121.981167,2019.715251,20.993859,4.815763,53.405527,91.695960,100.762848
std,70.122232,3.465192,14.449663,7.069362,12.320784,4.452067,6.857793
min,10001.000000,2014.000000,1.000000,0.000000,1.000000,76.115000,77.106000
25%,10061.000000,2017.000000,8.000000,0.000000,46.000000,88.690000,96.135000
50%,10122.000000,2020.000000,21.000000,0.000000,54.000000,91.670000,100.893000
75%,10183.000000,2023.000000,34.000000,8.000000,63.000000,94.679000,105.370000
max,10243.000000,2025.000000,53.000000,25.000000,71.000000,109.703000,124.307000

In [28]:
financeiro_df.describe()

              ano  verba_patrocinadores_m USD  forca_carro_indice
count   125.00000                  125.000000           125.00000
mean   2019.51200                  111.648720            76.97824
std       3.43515                   34.203022            12.31183
min    2014.00000                   31.140000            45.83000
25%    2017.00000                   87.180000            67.09000
50%    2020.00000                  109.030000            75.83000
75%    2022.00000                  132.090000            86.10000
max    2025.00000                  203.360000           100.07000

In [29]:
pitstops_df.describe()

         id_corrida          ano    id_piloto   numero_pit  tempo_pit_s
count   8632.000000  8632.000000  8632.000000  8632.000000  8545.000000
mean   10121.898285  2019.711770    21.085148     1.556302     2.765839
std       70.376404     3.477336    14.504940     0.722276     0.553352
min    10001.000000  2014.000000     1.000000     1.000000     0.409000
25%    10061.000000  2017.000000     8.000000     1.000000     2.393000
50%    10122.000000  2020.000000    21.000000     1.000000     2.770000
75%    10183.000000  2023.000000    35.000000     2.000000     3.139000
max    10243.000000  2025.000000    53.000000     4.000000     4.796000

### nulos

**Use **isnull()** e **isnull().sum()** em todas as bases. Explique por que isso ainda não detecta todos os problemas.**

In [30]:
corridas_df.isnull().sum()

id_corrida       0
ano              0
rodada           0
gp               0
pais_gp          0
clima            0
temperatura_c    3
dtype: int64

In [31]:
financeiro_df.isnull().sum()

ano                                   0
equipe                                0
investimento_desenvolvimento_m USD    1
verba_patrocinadores_m USD            0
forca_carro_indice                    0
dtype: int64

In [32]:
patrocinadores_df.isnull().sum()

ano                     0
equipe                  0
patrocinador            0
categoria_patrocinio    0
valor_estimado_m USD    0
dtype: int64

In [33]:
pilotos_df.isnull().sum()

ano                 0
id_piloto           0
piloto              0
equipe              0
nacionalidade       0
idade               3
experiencia_anos    0
dtype: int64

In [34]:
pitstops_df.isnull().sum()

id_corrida      0
ano             0
id_piloto       0
piloto          0
equipe          0
numero_pit      0
tempo_pit_s    87
dtype: int64

In [35]:
resultados_df.isnull().sum()

id_corrida              0
ano                     0
gp                      0
id_piloto               0
piloto                  0
equipe                  0
posicao_final           0
pontos                  0
voltas_completadas      0
melhor_volta_s          0
tempo_total_min       374
dtype: int64

A detecção de nulos não é capaz de ver valores em string vazios ou representação de strings vazias (como '-').

## 2 - Seleções, filtros e ordenação

**Selecione em **resultados** apenas: **ano**, **gp**, **piloto**, **equipe**, **posicao_final**, **pontos**.**

In [36]:
resultados_df[['ano', 'gp', 'piloto', 'equipe', 'posicao_final', 'pontos']].head(7)

    ano            gp            piloto     equipe posicao_final  pontos
0  2014    Bahrain GP    Lewis Hamilton   Mercedes             1      25
1  2014    Bahrain GP      Nico Rosberg   Mercedes           DNF       0
2  2014    Bahrain GP  sebastian vettel   Red Bull             5      10
3  2014    Bahrain GP  Daniel Ricciardo   Red Bull            10       1
4  2014    Bahrain GP   Fernando Alonso    Ferrari             4      12
5  2014    bahrain gp    Kimi Raikkonen   ferrari             11       0
6  2014   BAHRAIN GP      Jenson Button    McLaren             3      15

**Selecione linhas 10 até 30 e colunas **piloto**, **equipe**, **pontos** usando **loc**.**

In [37]:
resultados_df.loc[10 : 30, ['piloto', 'equipe', 'pontos']]

                piloto       equipe  pontos
10        Sergio Perez  Force India       0
11     Nico Hulkenberg  Force India       8
12    Jean-Eric Vergne   Toro Rosso       0
13        Daniil Kvyat   Toro Rosso       0
14    ROMAIN GROSJEAN         Lotus       0
15    Pastor Maldonado        Lotus       2
16        Adrian Sutil       Sauber       0
17   Esteban Gutierrez       Sauber       0
18      jules bianchi      Marussia       0
19         Max Chilton     Marussia       0
20      Lewis Hamilton     Mercedes       6
21        Nico Rosberg     Mercedes      12
22   sebastian vettel     RED BULL       10
23    daniel ricciardo     Red Bull      25
24     Fernando Alonso     FERRARI        2
25      Kimi Raikkonen      Ferrari      18
26      JENSON BUTTON       McLaren      15
27     Kevin Magnussen     MCLAREN        8
28        Felipe Massa     williams       1
29     Valtteri Bottas     Williams       0
30        Sergio Perez  Force India       0

**Selecione as primeiras 20 linhas e as 6 primeiras colunas usando **iloc**.**

In [38]:
resultados_df.iloc[ :20, :6]

    id_corrida   ano            gp  id_piloto             piloto       equipe
0        10001  2014    Bahrain GP          1     Lewis Hamilton     Mercedes
1        10001  2014    Bahrain GP          2       Nico Rosberg     Mercedes
2        10001  2014    Bahrain GP          3   sebastian vettel     Red Bull
3        10001  2014    Bahrain GP          4   Daniel Ricciardo     Red Bull
4        10001  2014    Bahrain GP          5    Fernando Alonso      Ferrari
5        10001  2014    bahrain gp          6     Kimi Raikkonen     ferrari
6        10001  2014   BAHRAIN GP           7      Jenson Button      McLaren
7        10001  2014    Bahrain GP          8    Kevin Magnussen      McLaren
8        10001  2014   BAHRAIN GP           9      FELIPE MASSA      Williams
9        10001  2014    Bahrain GP         10    Valtteri Bottas     Williams
10       10001  2014    Bahrain GP         11       Sergio Perez  Force India
11       10001  2014    Bahrain GP         12    Nico Hulkenberg  Force India
12       10001  2014    bahrain gp         13   Jean-Eric Vergne   Toro Rosso
13       10001  2014    Bahrain GP         14       Daniil Kvyat   Toro Rosso
14       10001  2014   bahrain gp          15   ROMAIN GROSJEAN         Lotus
15       10001  2014    Bahrain GP         16   Pastor Maldonado        Lotus
16       10001  2014    Bahrain GP         17       Adrian Sutil       Sauber
17       10001  2014    Bahrain GP         18  Esteban Gutierrez       Sauber
18       10001  2014    Bahrain GP         19     jules bianchi      Marussia
19       10001  2014    Bahrain GP         20        Max Chilton     Marussia

**Filtre resultados de **Ferrari** ou **Mercedes** com **pontos >= 15**. Atenção ao veneno textual.**

In [39]:
resultados_df['equipe'] = resultados_df['equipe'].str.strip().str.capitalize()

resultados_df['equipe'].value_counts()

equipe
Mercedes        490
Ferrari         490
Mclaren         489
Red bull        488
Williams        487
Haas            411
Sauber          279
Toro rosso      229
Aston martin    223
Alpine          221
Alfa romeo      208
Force india     191
Renault         190
Alphatauri      171
Rb               88
Racing point     78
Lotus            76
Marussia         38
Manor            38
Name: count, dtype: int64

In [40]:
filter = ((resultados_df['equipe'] == 'Ferrari') | (resultados_df['equipe'] == 'Mercedes')) & (resultados_df['pontos'] >= 15)

resultados_df[filter].head(7)

,id_corrida,ano,gp,id_piloto,piloto,equipe,posicao_final,pontos,voltas_completadas,melhor_volta_s,tempo_total_min
0,10001,2014,Bahrain GP,1,Lewis Hamilton,Mercedes,1,25,50,92.446,97.289
25,10002,2014,Saudi Arabian GP,6,Kimi Raikkonen,Ferrari,2,18,46,91.886,94.685
40,10003,2014,Australian GP,1,Lewis Hamilton,Mercedes,2,18,56,92.391,100.060
80,10005,2014,Chinese GP,1,Lewis Hamilton,Mercedes,3,15,52,86.453,87.737
160,10009,2014,Canadian GP,1,Lewis Hamilton,Mercedes,2,18,70,93.234,90.451
164,10009,2014,Canadian GP,5,Fernando Alonso,Ferrari,1,25,60,93.415,103.784
200,10011,2014,Austrian GP,1,Lewis Hamilton,Mercedes,2,18,43,85.374,85.442

**Ordene os resultados por **ano** crescente e **pontos** decrescente.**

In [41]:
res_ano_asc = resultados_df['ano'].sort_values().index

resultados_df.loc[res_ano_asc]

,id_corrida,ano,gp,id_piloto,piloto,equipe,posicao_final,pontos,voltas_completadas,melhor_volta_s,tempo_total_min
52,10003,2014,AUSTRALIAN GP,13,Jean-Eric Vergne,Toro rosso,15,0,52,94.798,96.328
75,10004,2014,Japanese GP,16,Pastor Maldonado,Lotus,17,0,43,94.888,93.175
74,10004,2014,Japanese GP,15,Romain Grosjean,Lotus,DNF,0,36,97.062,NaN
73,10004,2014,Japanese GP,14,Daniil Kvyat,Toro rosso,14,0,57,93.107,105.586
72,10004,2014,Japanese GP,13,Jean-Eric Vergne,Toro rosso,13,0,69,88.240,100.352
...,...,...,...,...,...,...,...,...,...,...,...
4823,10242,2025,Las Vegas GP,11,Sergio Perez,Red bull,13,0,52,100.084,107.394
4420,10222,2025,Bahrain GP,37,George Russell,Mercedes,3,15,54,93.522,106.926
4854,10243,2025,Abu Dhabi GP,33,Pierre Gasly,Alpine,11,0,59,93.107,102.136
4853,10243,2025,Abu Dhabi GP,50,Liam Lawson,Rb,17,0,46,91.097,102.285
4859,10243,2025,Abu Dhabi GP,53,Oliver Bearman,Haas,20,0,48,97.181,110.966

In [42]:
res_ano_desc = resultados_df['ano'].sort_values(ascending=False).index

resultados_df.loc[res_ano_desc]

,id_corrida,ano,gp,id_piloto,piloto,equipe,posicao_final,pontos,voltas_completadas,melhor_volta_s,tempo_total_min
4834,10242,2025,LAS VEGAS GP,33,Pierre Gasly,Alpine,10,1,58,100.711,96.752
4859,10243,2025,Abu Dhabi GP,53,Oliver Bearman,Haas,20,0,48,97.181,110.966
4858,10243,2025,Abu Dhabi GP,30,esteban ocon,Haas,DNF,0,7,98.922,NaN
4426,10222,2025,Bahrain GP,36,Lando Norris,Mclaren,5,10,69,88.887,101.372
4427,10222,2025,Bahrain GP,46,OSCAR PIASTRI,Mclaren,1,25,70,92.321,85.716
...,...,...,...,...,...,...,...,...,...,...,...
63,10004,2014,Japanese GP,4,Daniel Ricciardo,Red bull,1,25,49,87.970,93.557
62,10004,2014,Japanese GP,3,Sebastian Vettel,Red bull,2,18,65,89.696,101.178
22,10002,2014,saudi arabian gp,3,sebastian vettel,Red bull,5,10,56,88.605,94.234
21,10002,2014,Saudi Arabian GP,2,Nico Rosberg,Mercedes,4,12,63,85.302,102.648
20,10002,2014,Saudi Arabian GP,1,Lewis Hamilton,Mercedes,7,6,63,91.431,88.192

**Crie uma coluna **podio** em **resultados**, indicando **Sim** quando a posição final for 1, 2 ou 3.**

In [43]:
resultados_df['posicao_final'].value_counts()

posicao_final
DNF    280
9      237
2      236
5      235
6      235
11     234
3      234
7      234
8      233
4      231
14     231
10     230
13     230
12     230
1      229
16     229
18     227
20     225
15     224
17     221
19     220
Name: count, dtype: int64

In [44]:
resultados_df['podio'] = 'Nao'

dnf = resultados_df['posicao_final'] == 'DNF'
resultados_df.loc[dnf, ['posicao_final']] = '99'

resultados_df[dnf]

,id_corrida,ano,gp,id_piloto,piloto,equipe,posicao_final,pontos,voltas_completadas,melhor_volta_s,tempo_total_min,podio
1,10001,2014,Bahrain GP,2,Nico Rosberg,Mercedes,99,0,22,93.164,NaN,Nao
12,10001,2014,bahrain gp,13,Jean-Eric Vergne,Toro rosso,99,0,37,94.676,NaN,Nao
30,10002,2014,Saudi Arabian GP,11,Sergio Perez,Force india,99,0,15,93.694,NaN,Nao
48,10003,2014,Australian GP,9,Felipe Massa,Williams,99,0,21,96.773,NaN,Nao
74,10004,2014,Japanese GP,15,Romain Grosjean,Lotus,99,0,36,97.062,NaN,Nao
...,...,...,...,...,...,...,...,...,...,...,...,...
4802,10241,2025,brazilian gp,21,MAX VERSTAPPEN,Red bull,99,0,4,98.558,NaN,Nao
4839,10242,2025,Las Vegas GP,53,Oliver Bearman,Haas,99,0,16,95.607,NaN,Nao
4858,10243,2025,Abu Dhabi GP,30,esteban ocon,Haas,99,0,7,98.922,NaN,Nao
4864,10191,2023,Belgian GP,29,Lance Stroll,Aston martin,99,0,31,88.573,NaN,Nao
4867,10020,2015,Bahrain GP,7,Jenson Button,Mclaren,99,0,5,87.845,NaN,Nao

In [45]:
resultados_df['posicao_final'] = resultados_df['posicao_final'].astype(int)

podio = resultados_df['posicao_final'] <= 3
resultados_df[podio].head()

,id_corrida,ano,gp,id_piloto,piloto,equipe,posicao_final,pontos,voltas_completadas,melhor_volta_s,tempo_total_min,podio
0,10001,2014,Bahrain GP,1,Lewis Hamilton,Mercedes,1,25,50,92.446,97.289,Nao
6,10001,2014,BAHRAIN GP,7,Jenson Button,Mclaren,3,15,47,89.456,84.603,Nao
7,10001,2014,Bahrain GP,8,Kevin Magnussen,Mclaren,2,18,47,89.499,86.733,Nao
23,10002,2014,Saudi Arabian GP,4,daniel ricciardo,Red bull,1,25,62,87.266,94.133,Nao
25,10002,2014,Saudi Arabian GP,6,Kimi Raikkonen,Ferrari,2,18,46,91.886,94.685,Nao

In [46]:
resultados_df.loc[podio, 'podio'] = 'Sim'

resultados_df[podio].head()

,id_corrida,ano,gp,id_piloto,piloto,equipe,posicao_final,pontos,voltas_completadas,melhor_volta_s,tempo_total_min,podio
0,10001,2014,Bahrain GP,1,Lewis Hamilton,Mercedes,1,25,50,92.446,97.289,Sim
6,10001,2014,BAHRAIN GP,7,Jenson Button,Mclaren,3,15,47,89.456,84.603,Sim
7,10001,2014,Bahrain GP,8,Kevin Magnussen,Mclaren,2,18,47,89.499,86.733,Sim
23,10002,2014,Saudi Arabian GP,4,daniel ricciardo,Red bull,1,25,62,87.266,94.133,Sim
25,10002,2014,Saudi Arabian GP,6,Kimi Raikkonen,Ferrari,2,18,46,91.886,94.685,Sim

**Renomeie colunas financeiras para nomes mais fáceis: **investimento_desenvolvimento_m USD** → **investimento_musd**; **verba_patrocinadores_m USD** → **patrocinio_musd**.**

In [47]:
new_columns = {}
for col in financeiro_df.columns.values:
    new_columns[col] = col

new_columns

{'ano': 'ano',
 'equipe': 'equipe',
 'investimento_desenvolvimento_m USD': 'investimento_desenvolvimento_m USD',
 'verba_patrocinadores_m USD': 'verba_patrocinadores_m USD',
 'forca_carro_indice': 'forca_carro_indice'}

In [48]:
new_columns['investimento_desenvolvimento_m USD'] = 'investimento_musd'
new_columns['verba_patrocinadores_m USD'] = 'patrocinio_musd'

new_columns

{'ano': 'ano',
 'equipe': 'equipe',
 'investimento_desenvolvimento_m USD': 'investimento_musd',
 'verba_patrocinadores_m USD': 'patrocinio_musd',
 'forca_carro_indice': 'forca_carro_indice'}

In [49]:
financeiro_df.rename(columns=new_columns, inplace=True)
financeiro_df.head()

    ano    equipe investimento_musd  patrocinio_musd  forca_carro_indice
0  2014  Mercedes            142.45            44.61               93.53
1  2014  Red Bull            284.27           108.17               95.81
2  2014   Ferrari            282.55           130.51               86.15
3  2014   McLaren            260.26           148.08               92.97
4  2014  williams               NaN            84.71               74.47

In [50]:
patrocinadores_df.rename(columns={'valor_estimado_m USD': 'valor_estimado_musd'}, inplace=True)

patrocinadores_df.head()

    ano      equipe patrocinador categoria_patrocinio  valor_estimado_musd
0  2014   MERCEDES      Petronas            logística                27.20
1  2014    Mercedes        Ineos               master                12.10
2  2014    Mercedes   TeamViewer          combustível                52.69
3  2014    Red Bull       Oracle           tecnologia                22.06
4  2014    Red Bull      Mobil 1            logística                23.23

# 3 - Limpeza

#### **Substitua falsos nulos (**N/A**, espaço vazio e **nao informado**) por **np.nan** em todas as bases.**

In [51]:
corridas_df.replace(r'^\s*$', np.nan, regex=True, inplace=True).isna().sum()

id_corrida       0
ano              0
rodada           0
gp               0
pais_gp          0
clima            0
temperatura_c    3
dtype: int64

In [52]:
def replace_empty_str(df):
    df.replace(r'^\s*$', np.nan, regex=True, inplace=True)
    print(f'Valores nulos após substituição de strings vazias por NaN em:')
    display(df.isna().sum())

replace_empty_str(financeiro_df)

Valores nulos após substituição de strings vazias por NaN em:

ano                   0
equipe                0
investimento_musd     1
patrocinio_musd       0
forca_carro_indice    0
dtype: int64

In [53]:
replace_empty_str(patrocinadores_df)

Valores nulos após substituição de strings vazias por NaN em:

ano                     0
equipe                  0
patrocinador            6
categoria_patrocinio    0
valor_estimado_musd     0
dtype: int64

In [54]:
replace_empty_str(pilotos_df)

Valores nulos após substituição de strings vazias por NaN em:

ano                 0
id_piloto           0
piloto              2
equipe              0
nacionalidade       1
idade               3
experiencia_anos    0
dtype: int64

In [55]:
replace_empty_str(pitstops_df)

Valores nulos após substituição de strings vazias por NaN em:

id_corrida      0
ano             0
id_piloto       0
piloto          0
equipe          0
numero_pit      0
tempo_pit_s    87
dtype: int64

In [56]:
replace_empty_str(resultados_df)

Valores nulos após substituição de strings vazias por NaN em:

id_corrida              0
ano                     0
gp                      0
id_piloto               0
piloto                  0
equipe                  0
posicao_final           0
pontos                  0
voltas_completadas      0
melhor_volta_s          0
tempo_total_min       374
podio                   0
dtype: int64

#### **Aplique **str.strip()** e **str.upper()** nas chaves textuais importantes: **piloto**, **equipe**, **gp**, **clima**, **patrocinador**.**

In [57]:
pilotos_df.head()

,ano,id_piloto,piloto,equipe,nacionalidade,idade,experiencia_anos
0,2014,1,Lewis Hamilton,Mercedes,Itália,37,3
1,2014,2,Nico Rosberg,Mercedes,Itália,39,6
2,2014,3,Sebastian Vettel,Red Bull,Espanha,30,6
3,2014,4,Daniel Ricciardo,red bull,Austrália,26,0
4,2014,5,fernando alonso,Ferrari,Brasil,37,0

In [58]:
pilotos_df['piloto'] = pilotos_df['piloto'].str.strip().str.title()

pilotos_df['piloto'].value_counts()

piloto
Lewis Hamilton        12
Sergio Perez          12
Valtteri Bottas       11
Max Verstappen        11
Carlos Sainz          11
Daniel Ricciardo      10
Fernando Alonso       10
Sebastian Vettel       9
Kevin Magnussen        9
Nico Hulkenberg        9
Kimi Raikkonen         8
Lance Stroll           8
Esteban Ocon           8
Pierre Gasly           8
Charles Leclerc        8
Romain Grosjean        7
Lando Norris           7
George Russell         7
Daniil Kvyat           6
Alexander Albon        6
Yuki Tsunoda           5
Felipe Massa           4
Marcus Ericsson        4
Nico Rosberg           3
Jenson Button          3
Antonio Giovinazzi     3
Nicholas Latifi        3
Zhou Guanyu            3
Oscar Piastri          3
Pastor Maldonado       2
Esteban Gutierrez      2
Felipe Nasr            2
Jolyon Palmer          2
Stoffel Vandoorne      2
Mick Schumacher        2
Logan Sargeant         2
Jean-Eric Vergne       1
Adrian Sutil           1
Jules Bianchi          1
Will Stevens           1
Roberto Merhi          1
Pascal Wehrlein        1
Sergey Sirotkin        1
Brendon Hartley        1
Robert Kubica          1
Nikita Mazepin         1
Nyck De Vries          1
Kimi Antonelli         1
Liam Lawson            1
Jack Doohan            1
Gabriel Bortoleto      1
Oliver Bearman         1
Name: count, dtype: int64

In [59]:
pilotos_df['equipe'] = pilotos_df['equipe'].str.strip().str.upper()

pilotos_df['equipe'].value_counts()

equipe
MERCEDES         24
RED BULL         24
FERRARI          24
WILLIAMS         23
MCLAREN          22
HAAS             19
SAUBER           14
TORO ROSSO       12
FORCE INDIA      10
RENAULT          10
ALFA ROMEO       10
ASTON MARTIN     10
ALPINE           10
ALPHATAURI        8
NAO INFORMADO     5
LOTUS             4
RB                4
RACING POINT      3
MARUSSIA          2
MANOR             2
Name: count, dtype: int64

In [60]:
pilotos_df['nacionalidade'] = pilotos_df['nacionalidade'].str.strip().str.title()

pilotos_df['nacionalidade'].value_counts()

nacionalidade
Holanda        20
China          20
Reino Unido    20
Espanha        19
Austrália      19
Brasil         19
Canadá         19
Itália         18
México         17
Finlândia      17
França         15
Mônaco         14
Alemanha       12
Japão          10
Name: count, dtype: int64

In [61]:
corridas_df.head()

   id_corrida   ano  rodada                gp  pais_gp    clima  temperatura_c
0       10001  2014       1       BAHRAIN GP    Canadá  nublado           20.0
1       10002  2014       2  Saudi Arabian GP   México    chuva           15.0
2       10003  2014       3     Australian GP  Bélgica    misto           27.0
3       10004  2014       4       Japanese GP  Holanda    SECO            21.0
4       10005  2014       5        Chinese GP  Holanda     seco           31.0

In [62]:
def upper_column(df: pd.DataFrame, upp_col: list):
    for col in upp_col:
        df[col] = df[col].str.strip().str.upper()

up = ['gp', 'clima']

upper_column(corridas_df, up)
corridas_df['gp'].value_counts()

gp
BAHRAIN GP           12
SAUDI ARABIAN GP     12
AUSTRALIAN GP        12
JAPANESE GP          12
CHINESE GP           12
MIAMI GP             12
EMILIA ROMAGNA GP    12
MONACO GP            12
CANADIAN GP          12
SPANISH GP           12
AUSTRIAN GP          12
BRITISH GP           12
HUNGARIAN GP         12
BELGIAN GP           12
DUTCH GP             12
ITALIAN GP           12
SINGAPORE GP         12
UNITED STATES GP     12
MEXICAN GP           12
BRAZILIAN GP          5
LAS VEGAS GP          5
ABU DHABI GP          5
Name: count, dtype: int64

In [63]:
corridas_df['clima'].value_counts()

clima
SECO             140
NUBLADO           47
CHUVA             31
MISTO             21
NAO INFORMADO      4
Name: count, dtype: int64

In [64]:
def title_column(df: pd.DataFrame, title_col: list):
    for col in title_col:
        df[col] = df[col].str.strip().str.title()

title_column(corridas_df, ['pais_gp'])
corridas_df['pais_gp'].value_counts()

pais_gp
Holanda            19
Reino Unido        18
Austrália          16
México             15
Espanha            15
Hungria            14
Áustria            14
Canadá             13
Arábia Saudita     13
Bahrein            12
Itália             12
Singapura          12
Eua                12
Bélgica            11
Brasil             11
Emirados Árabes    10
Mônaco              9
Japão               9
China               8
Name: count, dtype: int64

In [65]:
financeiro_df.head()

    ano    equipe investimento_musd  patrocinio_musd  forca_carro_indice
0  2014  Mercedes            142.45            44.61               93.53
1  2014  Red Bull            284.27           108.17               95.81
2  2014   Ferrari            282.55           130.51               86.15
3  2014   McLaren            260.26           148.08               92.97
4  2014  williams               NaN            84.71               74.47

In [66]:
upper_column(financeiro_df, ['equipe'])
financeiro_df['equipe'].value_counts()

equipe
FERRARI         13
MERCEDES        12
RED BULL        12
MCLAREN         12
WILLIAMS        12
HAAS            11
SAUBER           8
TORO ROSSO       7
FORCE INDIA      5
RENAULT          5
ALFA ROMEO       5
ASTON MARTIN     5
ALPINE           5
ALPHATAURI       4
RACING POINT     3
LOTUS            2
RB               2
MARUSSIA         1
MANOR            1
Name: count, dtype: int64

In [67]:
patrocinadores_df.head()

    ano      equipe patrocinador categoria_patrocinio  valor_estimado_musd
0  2014   MERCEDES      Petronas            logística                27.20
1  2014    Mercedes        Ineos               master                12.10
2  2014    Mercedes   TeamViewer          combustível                52.69
3  2014    Red Bull       Oracle           tecnologia                22.06
4  2014    Red Bull      Mobil 1            logística                23.23

In [68]:
up = ['equipe', 'patrocinador', 'categoria_patrocinio']

upper_column(patrocinadores_df, up)
patrocinadores_df['equipe'].value_counts()

equipe
MERCEDES        36
RED BULL        36
FERRARI         36
MCLAREN         36
WILLIAMS        36
HAAS            30
SAUBER          21
TORO ROSSO      18
FORCE INDIA     15
RENAULT         15
ALFA ROMEO      15
ASTON MARTIN    15
ALPINE          15
ALPHATAURI      12
LOTUS            6
RACING POINT     6
RB               6
MARUSSIA         3
MANOR            3
Name: count, dtype: int64

In [69]:
patrocinadores_df['categoria_patrocinio'].value_counts()

categoria_patrocinio
FINANCEIRO     77
MASTER         74
TECNOLOGIA     71
LOGÍSTICA      70
COMBUSTÍVEL    68
Name: count, dtype: int64

In [70]:
patrocinadores_df['patrocinador'].value_counts()

patrocinador
PIRELLI        16
DELL           14
INEOS          12
TEAMVIEWER     12
ORACLE         12
MOBIL 1        12
BYBIT          12
SHELL          12
SANTANDER      12
HP             12
GOOGLE         12
DURACELL       12
GULF           12
KOMATSU        12
CLARO          12
RED BULL       12
PETRONAS       11
OKX            11
HONDA          10
MONEYGRAM      10
ALPINESTARS    10
CASTROL         9
MICROSOFT       7
STAKE           7
ALFA ROMEO      7
BWT             7
JCB             7
KINGFISHER      5
SAHARA          5
CASIO           5
MAPFRE          5
ORLEN           5
SAUBER          5
SINGHA          5
ARAMCO          5
BP              4
COGNIZANT       4
PDVSA           2
EMC             2
SPORTPESA       2
VISA            2
CASH APP        2
QNET            1
PERTAMINA       1
Name: count, dtype: int64

In [71]:
pitstops_df.head()

,id_corrida,ano,id_piloto,piloto,equipe,numero_pit,tempo_pit_s
0,10001,2014,1,Lewis Hamilton,Mercedes,1,3.238
1,10001,2014,2,Nico Rosberg,Mercedes,1,2.768
2,10001,2014,2,Nico Rosberg,Mercedes,2,3.142
3,10001,2014,2,Nico Rosberg,Mercedes,3,2.913
4,10001,2014,3,Sebastian Vettel,Red Bull,1,2.664

In [72]:
upper_column(pitstops_df, ['equipe'])

pitstops_df['equipe'].value_counts()

equipe
FERRARI         889
MCLAREN         884
RED BULL        871
WILLIAMS        869
MERCEDES        847
HAAS            737
SAUBER          504
TORO ROSSO      385
ASTON MARTIN    381
ALPINE          369
ALFA ROMEO      347
RENAULT         343
FORCE INDIA     335
ALPHATAURI      301
RB              155
LOTUS           141
RACING POINT    137
MARUSSIA         73
MANOR            64
Name: count, dtype: int64

In [73]:
resultados_df.head()

,id_corrida,ano,gp,id_piloto,piloto,equipe,posicao_final,pontos,voltas_completadas,melhor_volta_s,tempo_total_min,podio
0,10001,2014,Bahrain GP,1,Lewis Hamilton,Mercedes,1,25,50,92.446,97.289,Sim
1,10001,2014,Bahrain GP,2,Nico Rosberg,Mercedes,99,0,22,93.164,NaN,Nao
2,10001,2014,Bahrain GP,3,sebastian vettel,Red bull,5,10,45,90.692,102.982,Nao
3,10001,2014,Bahrain GP,4,Daniel Ricciardo,Red bull,10,1,44,86.723,94.113,Nao
4,10001,2014,Bahrain GP,5,Fernando Alonso,Ferrari,4,12,63,92.319,108.053,Nao

In [74]:
title_column(resultados_df, ['piloto'])

resultados_df['piloto'].value_counts()

piloto
Lewis Hamilton        244
Sergio Perez          244
Max Verstappen        226
Carlos Sainz          226
Valtteri Bottas       221
Fernando Alonso       205
Daniel Ricciardo      199
Lance Stroll          190
Nico Hulkenberg       181
Kevin Magnussen       180
Sebastian Vettel      179
Charles Leclerc       169
Esteban Ocon          168
Pierre Gasly          168
Kimi Raikkonen        155
George Russell        150
Lando Norris          149
Romain Grosjean       133
Alexander Albon       127
Daniil Kvyat          114
Yuki Tsunoda          110
Felipe Massa           76
Marcus Ericsson        76
Zhou Guanyu            66
Oscar Piastri          66
Nicholas Latifi        63
Antonio Giovinazzi     60
Nico Rosberg           58
Jenson Button          58
Mick Schumacher        44
Logan Sargeant         44
Esteban Gutierrez      40
Pastor Maldonado       38
Felipe Nasr            38
Jolyon Palmer          38
Stoffel Vandoorne      38
Nikita Mazepin         22
Nyck De Vries          22
Kimi Antonelli         22
Liam Lawson            22
Jack Doohan            22
Gabriel Bortoleto      22
Oliver Bearman         22
Jean-Eric Vergne       19
Adrian Sutil           19
Jules Bianchi          19
Max Chilton            19
Will Stevens           19
Roberto Merhi          19
Pascal Wehrlein        19
Sergey Sirotkin        19
Brendon Hartley        19
Robert Kubica          19
Name: count, dtype: int64

In [75]:
up = ['gp', 'equipe']

upper_column(resultados_df, up)
resultados_df['gp'].value_counts()

gp
HUNGARIAN GP         243
BELGIAN GP           243
DUTCH GP             243
CHINESE GP           242
MIAMI GP             242
CANADIAN GP          242
AUSTRIAN GP          242
BAHRAIN GP           241
AUSTRALIAN GP        241
JAPANESE GP          241
MONACO GP            241
SPANISH GP           241
BRITISH GP           241
UNITED STATES GP     241
MEXICAN GP           241
SAUDI ARABIAN GP     240
EMILIA ROMAGNA GP    240
ITALIAN GP           240
SINGAPORE GP         240
BRAZILIAN GP         100
LAS VEGAS GP         100
ABU DHABI GP         100
Name: count, dtype: int64

In [76]:
resultados_df['equipe'].value_counts()

equipe
MERCEDES        490
FERRARI         490
MCLAREN         489
RED BULL        488
WILLIAMS        487
HAAS            411
SAUBER          279
TORO ROSSO      229
ASTON MARTIN    223
ALPINE          221
ALFA ROMEO      208
FORCE INDIA     191
RENAULT         190
ALPHATAURI      171
RB               88
RACING POINT     78
LOTUS            76
MARUSSIA         38
MANOR            38
Name: count, dtype: int64

#### **Corrija **idade**: remova o texto **' anos'** e converta para número.**

In [77]:
pilotos_df['idade'] = pilotos_df['idade'].str.replace(' anos', '').astype(float)

pilotos_df['idade'].value_counts()

idade
39.0    18
32.0    17
37.0    15
25.0    15
26.0    14
29.0    14
38.0    14
24.0    13
30.0    11
21.0    11
36.0    11
41.0    10
27.0    10
23.0     9
34.0     9
31.0     9
33.0     9
22.0     9
40.0     7
28.0     7
35.0     5
Name: count, dtype: int64

#### **Corrija **investimento_musd**: troque vírgula por ponto e converta para **float**.**

In [78]:
financeiro_df['investimento_musd'] = financeiro_df['investimento_musd'].str.replace(',', '.').astype(float)

financeiro_df.dtypes

ano                     int64
equipe                    str
investimento_musd     float64
patrocinio_musd       float64
forca_carro_indice    float64
dtype: object

#### **Use **fillna()** para preencher clima desconhecido e temperatura ausente.**

In [79]:
corridas_df.head()

   id_corrida   ano  rodada                gp  pais_gp    clima  temperatura_c
0       10001  2014       1        BAHRAIN GP   Canadá  NUBLADO           20.0
1       10002  2014       2  SAUDI ARABIAN GP   México    CHUVA           15.0
2       10003  2014       3     AUSTRALIAN GP  Bélgica    MISTO           27.0
3       10004  2014       4       JAPANESE GP  Holanda     SECO           21.0
4       10005  2014       5        CHINESE GP  Holanda     SECO           31.0

In [80]:
corridas_df['clima'].value_counts()

clima
SECO             140
NUBLADO           47
CHUVA             31
MISTO             21
NAO INFORMADO      4
Name: count, dtype: int64

In [81]:
print(f'Nulos nos climas das corridas: {corridas_df['clima'].isna().sum()}')

Nulos nos climas das corridas: 0

In [82]:
print(f'Nulos nas temperaturas das corridas: {corridas_df['temperatura_c'].isna().sum()}')

Nulos nas temperaturas das corridas: 3

In [83]:
temp_mean = corridas_df['temperatura_c'].mean()
corridas_df['temperatura_c'] = corridas_df['temperatura_c'].fillna(temp_mean.round(2))

print(f'Média das temperaturas: {temp_mean:.2f}')
print(f'Nulos nas temperaturas das corridas: {corridas_df['temperatura_c'].isna().sum()}')

Média das temperaturas: 26.44
Nulos nas temperaturas das corridas: 0

Utilizei a média pois as temperaturas são naturalmente valores com baixa amplitude em suas variações.

#### **Use **dropna()** para remover linhas sem **posicao_final** ou sem **id_piloto**, se existirem.**

In [84]:
corridas_df.isna().sum()

id_corrida       0
ano              0
rodada           0
gp               0
pais_gp          0
clima            0
temperatura_c    0
dtype: int64

In [85]:
pilotos_df.isna().sum()

ano                 0
id_piloto           0
piloto              2
equipe              0
nacionalidade       1
idade               3
experiencia_anos    0
dtype: int64

In [86]:
pitstops_df.isna().sum()

id_corrida      0
ano             0
id_piloto       0
piloto          0
equipe          0
numero_pit      0
tempo_pit_s    87
dtype: int64

In [87]:
resultados_df.isna().sum()

id_corrida              0
ano                     0
gp                      0
id_piloto               0
piloto                  0
equipe                  0
posicao_final           0
pontos                  0
voltas_completadas      0
melhor_volta_s          0
tempo_total_min       374
podio                   0
dtype: int64

Não há colunas identificadoras vazias e nem nulos em posicao_final. Os valores 99 marcam quem não finalizou a corrida e portanto são valores importantes e não devem ser descartados.

#### **Detecte duplicatas em **resultados**, **pitstops** e **financeiro**. Depois remova duplicatas com critério adequado.**

In [88]:
print(f'Linhas duplicadas em Corridas: {corridas_df.duplicated().sum()}')
print(f'Linhas duplicadas em Financeiro: {financeiro_df.duplicated().sum()}')
print(f'Linhas duplicadas em Patrocinadores: {patrocinadores_df.duplicated().sum()}')
print(f'Linhas duplicadas em Pilotos: {pilotos_df.duplicated().sum()}')
print(f'Linhas duplicadas em Pitstops: {pitstops_df.duplicated().sum()}')
print(f'Linhas duplicadas em Resultados: {resultados_df.duplicated().sum()}')

Linhas duplicadas em Corridas: 0
Linhas duplicadas em Financeiro: 5
Linhas duplicadas em Patrocinadores: 0
Linhas duplicadas em Pilotos: 0
Linhas duplicadas em Pitstops: 30
Linhas duplicadas em Resultados: 25

Em relação aos resultados é possível que exista mais de um piloto registrado em uma mesma corrida, mesmo que a linha inteira não esteja duplicada.

In [89]:
dup_pilotos_corrida = resultados_df[resultados_df.duplicated(subset=['id_corrida', 'id_piloto'])]

print(f'Número de pilotos registrados na mesma corrida duas vezes: {len(dup_pilotos_corrida)}')
dup_pilotos_corrida

Número de pilotos registrados na mesma corrida duas vezes: 25

,id_corrida,ano,gp,id_piloto,piloto,equipe,posicao_final,pontos,voltas_completadas,melhor_volta_s,tempo_total_min,podio
4860,10110,2019,DUTCH GP,22,Carlos Sainz,MCLAREN,9,2,49,86.823,102.171,Nao
4861,10168,2022,HUNGARIAN GP,29,Lance Stroll,ASTON MARTIN,15,0,44,99.510,106.325,Nao
4862,10133,2020,MEXICAN GP,29,Lance Stroll,RACING POINT,11,0,40,93.166,106.877,Nao
4863,10106,2019,AUSTRIAN GP,3,Sebastian Vettel,FERRARI,9,2,59,92.886,98.105,Nao
4864,10191,2023,BELGIAN GP,29,Lance Stroll,ASTON MARTIN,99,0,31,88.573,NaN,Nao
4865,10123,2020,CANADIAN GP,36,Lando Norris,MCLAREN,7,6,56,92.850,110.055,Nao
4866,10091,2018,DUTCH GP,21,Max Verstappen,RED BULL,2,18,46,83.718,96.036,Sim
4867,10020,2015,BAHRAIN GP,7,Jenson Button,MCLAREN,99,0,5,87.845,NaN,Nao
4868,10126,2020,BRITISH GP,11,Sergio Perez,RACING POINT,14,0,57,99.197,103.513,Nao
4869,10208,2024,CANADIAN GP,37,George Russell,MERCEDES,12,0,42,103.891,104.544,Nao
4870,10226,2025,CHINESE GP,39,Alexander Albon,WILLIAMS,14,0,64,89.233,100.788,Nao
4871,10205,2024,MIAMI GP,37,George Russell,MERCEDES,2,18,59,87.881,100.620,Sim
4872,10052,2016,BELGIAN GP,3,Sebastian Vettel,FERRARI,6,8,41,91.490,96.748,Nao
4873,10025,2015,MIAMI GP,12,Nico Hulkenberg,FORCE INDIA,10,1,55,97.535,106.305,Nao
4874,10141,2021,MONACO GP,33,Pierre Gasly,ALPHATAURI,19,0,65,95.078,101.595,Nao
4875,10043,2016,CHINESE GP,18,Esteban Gutierrez,HAAS,20,0,70,87.016,115.116,Nao
4876,10099,2019,JAPANESE GP,35,Charles Leclerc,FERRARI,15,0,57,96.516,99.973,Nao
4877,10113,2019,UNITED STATES GP,35,Charles Leclerc,FERRARI,8,4,65,92.201,88.471,Nao
4878,10168,2022,HUNGARIAN GP,30,Esteban Ocon,ALPINE,10,1,58,90.418,96.263,Nao
4879,10015,2014,DUTCH GP,18,Esteban Gutierrez,SAUBER,10,1,71,93.174,99.696,Nao
4880,10188,2023,AUSTRIAN GP,21,Max Verstappen,RED BULL,5,10,71,82.839,104.892,Nao
4881,10146,2021,HUNGARIAN GP,1,Lewis Hamilton,MERCEDES,14,0,68,99.990,96.591,Nao
4882,10052,2016,BELGIAN GP,22,Carlos Sainz,TORO ROSSO,16,0,48,91.453,106.329,Nao
4883,10180,2023,AUSTRALIAN GP,29,Lance Stroll,ASTON MARTIN,8,4,65,91.378,112.983,Nao
4884,10029,2015,SPANISH GP,2,Nico Rosberg,MERCEDES,6,8,51,90.706,95.474,Nao

No caso de pitstops e financeiro apenas linhas completamente iguais serão excluídas, pois o mesmo piloto pode fazer mais de um pitstop na mesma corrida.

In [90]:
pitstops_df.head()

,id_corrida,ano,id_piloto,piloto,equipe,numero_pit,tempo_pit_s
0,10001,2014,1,Lewis Hamilton,MERCEDES,1,3.238
1,10001,2014,2,Nico Rosberg,MERCEDES,1,2.768
2,10001,2014,2,Nico Rosberg,MERCEDES,2,3.142
3,10001,2014,2,Nico Rosberg,MERCEDES,3,2.913
4,10001,2014,3,Sebastian Vettel,RED BULL,1,2.664

In [91]:
financeiro_df.head()

    ano    equipe  investimento_musd  patrocinio_musd  forca_carro_indice
0  2014  MERCEDES             142.45            44.61               93.53
1  2014  RED BULL             284.27           108.17               95.81
2  2014   FERRARI             282.55           130.51               86.15
3  2014   MCLAREN             260.26           148.08               92.97
4  2014  WILLIAMS                NaN            84.71               74.47

In [92]:
financeiro_df.drop_duplicates(inplace=True)
pitstops_df.drop_duplicates(inplace=True)
resultados_df.drop_duplicates(subset=['id_corrida', 'id_piloto'], inplace=True)

In [93]:
print(f'Linhas duplicadas em Corridas: {corridas_df.duplicated().sum()}')
print(f'Linhas duplicadas em Financeiro: {financeiro_df.duplicated().sum()}')
print(f'Linhas duplicadas em Patrocinadores: {patrocinadores_df.duplicated().sum()}')
print(f'Linhas duplicadas em Pilotos: {pilotos_df.duplicated().sum()}')
print(f'Linhas duplicadas em Pitstops: {pitstops_df.duplicated().sum()}')
print(f'Linhas duplicadas em Resultados: {resultados_df.duplicated().sum()}')

Linhas duplicadas em Corridas: 0
Linhas duplicadas em Financeiro: 0
Linhas duplicadas em Patrocinadores: 0
Linhas duplicadas em Pilotos: 0
Linhas duplicadas em Pitstops: 0
Linhas duplicadas em Resultados: 0

# 4 - Integração com concat, merge e join

#### Separe **resultados** em duas partes: até 2019 e de 2020 em diante. Recombine usando **concat()** e valide o tamanho.

In [120]:
res_ate_2019 = resultados_df[resultados_df['ano'] <= 2019]

print(f'Número de resultados totais: {len(resultados_df)}')
print(f'Número de resultados até 2019: {len(res_ate_2019)}')

res_ate_2019.head(7)

Número de resultados totais: 4860
Número de resultados até 2019: 2280

,id_corrida,ano,gp,id_piloto,piloto,equipe,posicao_final,pontos,voltas_completadas,melhor_volta_s,tempo_total_min,podio
0,10001,2014,BAHRAIN GP,1,Lewis Hamilton,MERCEDES,1,25,50,92.446,97.289,Sim
1,10001,2014,BAHRAIN GP,2,Nico Rosberg,MERCEDES,99,0,22,93.164,NaN,Nao
2,10001,2014,BAHRAIN GP,3,Sebastian Vettel,RED BULL,5,10,45,90.692,102.982,Nao
3,10001,2014,BAHRAIN GP,4,Daniel Ricciardo,RED BULL,10,1,44,86.723,94.113,Nao
4,10001,2014,BAHRAIN GP,5,Fernando Alonso,FERRARI,4,12,63,92.319,108.053,Nao
5,10001,2014,BAHRAIN GP,6,Kimi Raikkonen,FERRARI,11,0,63,94.749,109.583,Nao
6,10001,2014,BAHRAIN GP,7,Jenson Button,MCLAREN,3,15,47,89.456,84.603,Sim

In [121]:
res_pos_2020 = resultados_df[resultados_df['ano'] >= 2020]

print(f'Número de resultados a partir de 2020: {len(res_pos_2020)}')
res_pos_2020.head(7)

Número de resultados a partir de 2020: 2580

,id_corrida,ano,gp,id_piloto,piloto,equipe,posicao_final,pontos,voltas_completadas,melhor_volta_s,tempo_total_min,podio
2280,10115,2020,BAHRAIN GP,1,Lewis Hamilton,MERCEDES,1,25,45,87.962,98.998,Sim
2281,10115,2020,BAHRAIN GP,10,Valtteri Bottas,MERCEDES,3,15,48,88.088,95.112,Sim
2282,10115,2020,BAHRAIN GP,21,Max Verstappen,RED BULL,4,12,43,89.108,84.797,Nao
2283,10115,2020,BAHRAIN GP,39,Alexander Albon,RED BULL,5,10,57,90.138,95.284,Nao
2284,10115,2020,BAHRAIN GP,3,Sebastian Vettel,FERRARI,12,0,44,89.064,101.665,Nao
2285,10115,2020,BAHRAIN GP,35,Charles Leclerc,FERRARI,6,8,55,91.171,99.869,Nao
2286,10115,2020,BAHRAIN GP,22,Carlos Sainz,MCLAREN,2,18,69,98.384,95.256,Sim

In [122]:
res_df = pd.concat([res_ate_2019, res_pos_2020])

print(f'Número de elementos após a concatenação: {len(res_df)}')
res_df.head()

Número de elementos após a concatenação: 4860

,id_corrida,ano,gp,id_piloto,piloto,equipe,posicao_final,pontos,voltas_completadas,melhor_volta_s,tempo_total_min,podio
0,10001,2014,BAHRAIN GP,1,Lewis Hamilton,MERCEDES,1,25,50,92.446,97.289,Sim
1,10001,2014,BAHRAIN GP,2,Nico Rosberg,MERCEDES,99,0,22,93.164,NaN,Nao
2,10001,2014,BAHRAIN GP,3,Sebastian Vettel,RED BULL,5,10,45,90.692,102.982,Nao
3,10001,2014,BAHRAIN GP,4,Daniel Ricciardo,RED BULL,10,1,44,86.723,94.113,Nao
4,10001,2014,BAHRAIN GP,5,Fernando Alonso,FERRARI,4,12,63,92.319,108.053,Nao

In [123]:
res_df.tail()

,id_corrida,ano,gp,id_piloto,piloto,equipe,posicao_final,pontos,voltas_completadas,melhor_volta_s,tempo_total_min,podio
4855,10243,2025,ABU DHABI GP,51,Jack Doohan,ALPINE,10,1,44,94.365,100.589,Nao
4856,10243,2025,ABU DHABI GP,12,Nico Hulkenberg,SAUBER,13,0,40,91.400,109.301,Nao
4857,10243,2025,ABU DHABI GP,52,Gabriel Bortoleto,SAUBER,16,0,52,95.364,96.702,Nao
4858,10243,2025,ABU DHABI GP,30,Esteban Ocon,HAAS,99,0,7,98.922,NaN,Nao
4859,10243,2025,ABU DHABI GP,53,Oliver Bearman,HAAS,20,0,48,97.181,110.966,Nao

#### **Faça **merge** entre **resultados** e **corridas** usando **id_corrida**. Use **how='left'**.**

In [124]:
print(f'Número de elementos em Resultados: {len(resultados_df)}')
print(f'Número de elementos em Corridas: {len(corridas_df)}')
print('\nColunas em Resultados:', resultados_df.columns)
print('\nColunas em Corridas:', corridas_df.columns)

Número de elementos em Resultados: 4860
Número de elementos em Corridas: 243

Colunas em Resultados: Index(['id_corrida', 'ano', 'gp', 'id_piloto', 'piloto', 'equipe',
       'posicao_final', 'pontos', 'voltas_completadas', 'melhor_volta_s',
       'tempo_total_min', 'podio'],
      dtype='str')

Colunas em Corridas: Index(['id_corrida', 'ano', 'rodada', 'gp', 'pais_gp', 'clima',
       'temperatura_c'],
      dtype='str')

In [125]:
resultados_df.isna().sum()

id_corrida              0
ano                     0
gp                      0
id_piloto               0
piloto                  0
equipe                  0
posicao_final           0
pontos                  0
voltas_completadas      0
melhor_volta_s          0
tempo_total_min       372
podio                   0
dtype: int64

In [126]:
corridas_df.isna().sum()

id_corrida       0
ano              0
rodada           0
gp               0
pais_gp          0
clima            0
temperatura_c    0
dtype: int64

In [127]:
res_corridas_df = pd.merge(resultados_df, corridas_df, on='id_corrida', how='left')

print(f'Dataset Resultados_Corridas com {res_corridas_df.shape[0]} linhas e {res_corridas_df.shape[1]} colunas')
res_corridas_df.head(7)

Dataset Resultados_Corridas com 4860 linhas e 18 colunas

,id_corrida,ano_x,gp_x,id_piloto,piloto,equipe,posicao_final,pontos,voltas_completadas,melhor_volta_s,tempo_total_min,podio,ano_y,rodada,gp_y,pais_gp,clima,temperatura_c
0,10001,2014,BAHRAIN GP,1,Lewis Hamilton,MERCEDES,1,25,50,92.446,97.289,Sim,2014,1,BAHRAIN GP,Canadá,NUBLADO,20.0
1,10001,2014,BAHRAIN GP,2,Nico Rosberg,MERCEDES,99,0,22,93.164,NaN,Nao,2014,1,BAHRAIN GP,Canadá,NUBLADO,20.0
2,10001,2014,BAHRAIN GP,3,Sebastian Vettel,RED BULL,5,10,45,90.692,102.982,Nao,2014,1,BAHRAIN GP,Canadá,NUBLADO,20.0
3,10001,2014,BAHRAIN GP,4,Daniel Ricciardo,RED BULL,10,1,44,86.723,94.113,Nao,2014,1,BAHRAIN GP,Canadá,NUBLADO,20.0
4,10001,2014,BAHRAIN GP,5,Fernando Alonso,FERRARI,4,12,63,92.319,108.053,Nao,2014,1,BAHRAIN GP,Canadá,NUBLADO,20.0
5,10001,2014,BAHRAIN GP,6,Kimi Raikkonen,FERRARI,11,0,63,94.749,109.583,Nao,2014,1,BAHRAIN GP,Canadá,NUBLADO,20.0
6,10001,2014,BAHRAIN GP,7,Jenson Button,MCLAREN,3,15,47,89.456,84.603,Sim,2014,1,BAHRAIN GP,Canadá,NUBLADO,20.0

#### **Faça **merge** entre resultados e financeiro por **ano** e **equipe**. Teste **inner**, **left**, **right** e **outer**; compare os tamanhos.**

In [128]:
print(f'Número de elementos em Financeiro: {len(financeiro_df)}')
print('\nColunas em Financeiro:', financeiro_df.columns)

financeiro_df.head()

Número de elementos em Financeiro: 120

Colunas em Financeiro: Index(['ano', 'equipe', 'investimento_musd', 'patrocinio_musd',
       'forca_carro_indice'],
      dtype='str')

    ano    equipe  investimento_musd  patrocinio_musd  forca_carro_indice
0  2014  MERCEDES             142.45            44.61               93.53
1  2014  RED BULL             284.27           108.17               95.81
2  2014   FERRARI             282.55           130.51               86.15
3  2014   MCLAREN             260.26           148.08               92.97
4  2014  WILLIAMS                NaN            84.71               74.47

In [129]:
res_financeiro_left_df = pd.merge(resultados_df, financeiro_df, on=['ano', 'equipe'], how='left')

print(f'Número de elementos em Resultados_Financeiro Left Merge: {len(res_financeiro_left_df)}')
res_financeiro_left_df.head(7)

Número de elementos em Resultados_Financeiro Left Merge: 4860

,id_corrida,ano,gp,id_piloto,piloto,equipe,posicao_final,pontos,voltas_completadas,melhor_volta_s,tempo_total_min,podio,investimento_musd,patrocinio_musd,forca_carro_indice
0,10001,2014,BAHRAIN GP,1,Lewis Hamilton,MERCEDES,1,25,50,92.446,97.289,Sim,142.45,44.61,93.53
1,10001,2014,BAHRAIN GP,2,Nico Rosberg,MERCEDES,99,0,22,93.164,NaN,Nao,142.45,44.61,93.53
2,10001,2014,BAHRAIN GP,3,Sebastian Vettel,RED BULL,5,10,45,90.692,102.982,Nao,284.27,108.17,95.81
3,10001,2014,BAHRAIN GP,4,Daniel Ricciardo,RED BULL,10,1,44,86.723,94.113,Nao,284.27,108.17,95.81
4,10001,2014,BAHRAIN GP,5,Fernando Alonso,FERRARI,4,12,63,92.319,108.053,Nao,282.55,130.51,86.15
5,10001,2014,BAHRAIN GP,6,Kimi Raikkonen,FERRARI,11,0,63,94.749,109.583,Nao,282.55,130.51,86.15
6,10001,2014,BAHRAIN GP,7,Jenson Button,MCLAREN,3,15,47,89.456,84.603,Sim,260.26,148.08,92.97

In [130]:
res_financeiro_right_df = pd.merge(resultados_df, financeiro_df, on=['ano', 'equipe'], how='right')

print(f'Número de elementos em Resultados_Financeiro Right Merge: {len(res_financeiro_right_df)}')
res_financeiro_right_df.head(7)

Número de elementos em Resultados_Financeiro Right Merge: 4860

,id_corrida,ano,gp,id_piloto,piloto,equipe,posicao_final,pontos,voltas_completadas,melhor_volta_s,tempo_total_min,podio,investimento_musd,patrocinio_musd,forca_carro_indice
0,10001,2014,BAHRAIN GP,1,Lewis Hamilton,MERCEDES,1,25,50,92.446,97.289,Sim,142.45,44.61,93.53
1,10001,2014,BAHRAIN GP,2,Nico Rosberg,MERCEDES,99,0,22,93.164,NaN,Nao,142.45,44.61,93.53
2,10002,2014,SAUDI ARABIAN GP,1,Lewis Hamilton,MERCEDES,7,6,63,91.431,88.192,Nao,142.45,44.61,93.53
3,10002,2014,SAUDI ARABIAN GP,2,Nico Rosberg,MERCEDES,4,12,63,85.302,102.648,Nao,142.45,44.61,93.53
4,10003,2014,AUSTRALIAN GP,1,Lewis Hamilton,MERCEDES,2,18,56,92.391,100.060,Sim,142.45,44.61,93.53
5,10003,2014,AUSTRALIAN GP,2,Nico Rosberg,MERCEDES,4,12,54,83.883,91.234,Nao,142.45,44.61,93.53
6,10004,2014,JAPANESE GP,1,Lewis Hamilton,MERCEDES,8,4,65,95.074,99.988,Nao,142.45,44.61,93.53

In [131]:
res_financeiro_outer_df = pd.merge(resultados_df, financeiro_df, on=['ano', 'equipe'], how='outer')

print(f'Número de elementos em Resultado_Financeiro Outer Merge: {len(res_financeiro_outer_df)}')
res_financeiro_outer_df.head(7)

Número de elementos em Resultado_Financeiro Outer Merge: 4860

,id_corrida,ano,gp,id_piloto,piloto,equipe,posicao_final,pontos,voltas_completadas,melhor_volta_s,tempo_total_min,podio,investimento_musd,patrocinio_musd,forca_carro_indice
0,10001,2014,BAHRAIN GP,5,Fernando Alonso,FERRARI,4,12,63,92.319,108.053,Nao,282.55,130.51,86.15
1,10001,2014,BAHRAIN GP,6,Kimi Raikkonen,FERRARI,11,0,63,94.749,109.583,Nao,282.55,130.51,86.15
2,10002,2014,SAUDI ARABIAN GP,5,Fernando Alonso,FERRARI,9,2,55,93.090,101.380,Nao,282.55,130.51,86.15
3,10002,2014,SAUDI ARABIAN GP,6,Kimi Raikkonen,FERRARI,2,18,46,91.886,94.685,Sim,282.55,130.51,86.15
4,10003,2014,AUSTRALIAN GP,5,Fernando Alonso,FERRARI,7,6,41,91.916,102.349,Nao,282.55,130.51,86.15
5,10003,2014,AUSTRALIAN GP,6,Kimi Raikkonen,FERRARI,11,0,47,89.439,94.493,Nao,282.55,130.51,86.15
6,10004,2014,JAPANESE GP,5,Fernando Alonso,FERRARI,5,10,58,91.327,93.433,Nao,282.55,130.51,86.15

#### **Explique por que **merge** com patrocinadores pode multiplicar linhas.**

In [132]:
print(f'Número de elementos em Patrocinadores: {len(patrocinadores_df)}')
print('\nColunas de Patrocinadores:', patrocinadores_df.columns)

patrocinadores_df.head()

Número de elementos em Patrocinadores: 360

Colunas de Patrocinadores: Index(['ano', 'equipe', 'patrocinador', 'categoria_patrocinio',
       'valor_estimado_musd'],
      dtype='str')

    ano    equipe patrocinador categoria_patrocinio  valor_estimado_musd
0  2014  MERCEDES     PETRONAS            LOGÍSTICA                27.20
1  2014  MERCEDES        INEOS               MASTER                12.10
2  2014  MERCEDES   TEAMVIEWER          COMBUSTÍVEL                52.69
3  2014  RED BULL       ORACLE           TECNOLOGIA                22.06
4  2014  RED BULL      MOBIL 1            LOGÍSTICA                23.23

In [134]:
teste_merge = pd.merge(financeiro_df, patrocinadores_df, on='ano', how='outer')

print('Número de elementos no Teste Merge entre Financeiro e Patrocinadores:', len(teste_merge))
teste_merge.head()

Número de elementos no Teste Merge entre Financeiro e Patrocinadores: 3600

,ano,equipe_x,investimento_musd,patrocinio_musd,forca_carro_indice,equipe_y,patrocinador,categoria_patrocinio,valor_estimado_musd
0,2014,MERCEDES,142.45,44.61,93.53,MERCEDES,PETRONAS,LOGÍSTICA,27.20
1,2014,MERCEDES,142.45,44.61,93.53,MERCEDES,INEOS,MASTER,12.10
2,2014,MERCEDES,142.45,44.61,93.53,MERCEDES,TEAMVIEWER,COMBUSTÍVEL,52.69
3,2014,MERCEDES,142.45,44.61,93.53,RED BULL,ORACLE,TECNOLOGIA,22.06
4,2014,MERCEDES,142.45,44.61,93.53,RED BULL,MOBIL 1,LOGÍSTICA,23.23

O número de elementos pode explodir porque o dataset de patrocinadores possui diversas linhas com mesmo ano e mesma equipe, já que uma mesma equipe consegue mais de um patrocinador em uma mesma temporada. Assim, várias informações provindas de Financeiro se tornam redundantes já que são anuais.

#### **Agregue patrocinadores por **ano** e **equipe** antes do merge. Depois junte com resultados.**

In [137]:
financ_patrocinadores_df = pd.merge(financeiro_df, patrocinadores_df, on=['ano', 'equipe'], how='inner')

print('Número de elementos em Financeiro_Patrocinadores:', len(financ_patrocinadores_df))
financ_patrocinadores_df.head(7)

Número de elementos em Financeiro_Patrocinadores: 360

,ano,equipe,investimento_musd,patrocinio_musd,forca_carro_indice,patrocinador,categoria_patrocinio,valor_estimado_musd
0,2014,MERCEDES,142.45,44.61,93.53,PETRONAS,LOGÍSTICA,27.20
1,2014,MERCEDES,142.45,44.61,93.53,INEOS,MASTER,12.10
2,2014,MERCEDES,142.45,44.61,93.53,TEAMVIEWER,COMBUSTÍVEL,52.69
3,2014,RED BULL,284.27,108.17,95.81,ORACLE,TECNOLOGIA,22.06
4,2014,RED BULL,284.27,108.17,95.81,MOBIL 1,LOGÍSTICA,23.23
5,2014,RED BULL,284.27,108.17,95.81,BYBIT,FINANCEIRO,6.44
6,2014,FERRARI,282.55,130.51,86.15,SHELL,LOGÍSTICA,36.23

**Use **join()** colocando **ano** e **equipe** como índice em duas bases.**

In [138]:
financ_nidx_df = financeiro_df.set_index(['ano', 'equipe'])

financ_nidx_df.head()

               investimento_musd  patrocinio_musd  forca_carro_indice
ano  equipe
2014 MERCEDES             142.45            44.61               93.53
     RED BULL             284.27           108.17               95.81
     FERRARI              282.55           130.51               86.15
     MCLAREN              260.26           148.08               92.97
     WILLIAMS                NaN            84.71               74.47

In [139]:
patr_nidx_df = patrocinadores_df.set_index(['ano', 'equipe'])

patr_nidx_df.head()

              patrocinador categoria_patrocinio  valor_estimado_musd
ano  equipe
2014 MERCEDES     PETRONAS            LOGÍSTICA                27.20
     MERCEDES        INEOS               MASTER                12.10
     MERCEDES   TEAMVIEWER          COMBUSTÍVEL                52.69
     RED BULL       ORACLE           TECNOLOGIA                22.06
     RED BULL      MOBIL 1            LOGÍSTICA                23.23

In [140]:
fin_pat_idx_df = financ_nidx_df.join(patr_nidx_df)

print(f'Join entre Financeiro e Patrocínio a partir de seus índices com {len(fin_pat_idx_df)} elementos')
fin_pat_idx_df.head(7)

Join entre Financeiro e Patrocínio a partir de seus índices com 360 elementos

               investimento_musd  patrocinio_musd  forca_carro_indice  \
ano  equipe
2014 MERCEDES             142.45            44.61               93.53
     MERCEDES             142.45            44.61               93.53
     MERCEDES             142.45            44.61               93.53
     RED BULL             284.27           108.17               95.81
     RED BULL             284.27           108.17               95.81
     RED BULL             284.27           108.17               95.81
     FERRARI              282.55           130.51               86.15

              patrocinador categoria_patrocinio  valor_estimado_musd
ano  equipe
2014 MERCEDES     PETRONAS            LOGÍSTICA                27.20
     MERCEDES        INEOS               MASTER                12.10
     MERCEDES   TEAMVIEWER          COMBUSTÍVEL                52.69
     RED BULL       ORACLE           TECNOLOGIA                22.06
     RED BULL      MOBIL 1            LOGÍSTICA                23.23
     RED BULL        BYBIT           FINANCEIRO                 6.44
     FERRARI         SHELL            LOGÍSTICA                36.23

# 5 - Groupby e agregações

**Calcule total de pontos por piloto e ano.**

In [99]:
# Escreva sua resposta aqui

**Calcule total de pontos por equipe e ano.**

In [100]:
# Escreva sua resposta aqui

**Calcule média, soma, mínimo e máximo de pontos por equipe.**

In [101]:
# Escreva sua resposta aqui

**Calcule média de pit stop por piloto, equipe e ano.**

In [102]:
# Escreva sua resposta aqui

**Calcule quantidade de pódios por piloto e equipe.**

In [103]:
# Escreva sua resposta aqui

**Calcule correlação simples entre investimento e pontos por equipe/ano. Interprete com cuidado.**

In [104]:
# Escreva sua resposta aqui

# 6 - MultiIndex

**Crie um relatório por **ano**, **equipe** e **piloto**, com soma de pontos, média de posição e quantidade de pódios.**

In [105]:
# Escreva sua resposta aqui

**Transforme esse relatório em MultiIndex com **ano**, **equipe**, **piloto**.**

In [106]:
# Escreva sua resposta aqui

**Ordene o MultiIndex.**

In [107]:
# Escreva sua resposta aqui

**Selecione dados do ano 2024 usando **loc**.**

In [108]:
# Escreva sua resposta aqui

# 7 - Pivot table e melt

**Crie uma **pivot_table** com linhas = **ano**, colunas = **equipe**, valores = pontos totais.**

In [109]:
# Escreva sua resposta aqui

**Crie uma **pivot_table** com **aggfunc=['sum','mean','max']** para pontos por equipe.**

In [110]:
# Escreva sua resposta aqui

**Explique por que a pivot_table anterior gera MultiIndex nas colunas.**

In [111]:
# Escreva sua resposta aqui

**Use **melt()** para transformar o financeiro de formato largo para longo, com métricas de investimento, patrocínio e força do carro.**

In [112]:
# Escreva sua resposta aqui

**Explique a diferença entre tabela larga e tabela longa.**

In [113]:
# Escreva sua resposta aqui

# Desafio final de produção

**Construa um relatório final com: ano, equipe, piloto, pontos totais, média de posição, pódios, média de pit stop, investimento, patrocínio e total estimado de patrocinadores.**

In [114]:
# Escreva sua resposta aqui

**Ordene o relatório por ano, pontos totais e investimento.**

In [115]:
# Escreva sua resposta aqui

**Liste os 10 melhores pilotos por pontuação acumulada em todo o período.**

In [116]:
# Escreva sua resposta aqui

**Liste as 10 equipes com maior investimento acumulado.**

In [117]:
# Escreva sua resposta aqui

**Discuta 5 riscos analíticos desse pipeline.**

In [118]:
# Escreva sua resposta aqui

1 - Faça um resumo executivo da ULTIMA temporada.

2 - Crie 5 insights relevantes encontrados nos dados.

3 - Crie 3 recomendações estratégicas para uma equipe.

4 - Quais dados adicionais você gostaria de ter?

5 - Qual gráfico melhor representaria:
dominância;
eficiência;
evolução;
consistência?