# Avaliação aulas 1 - 7 - Base Histórica Fictícia de Fórmula 1

## Objetivo

Você recebeu uma base histórica fictícia de Fórmula 1 com muitos anos de dados. Os nomes de pilotos, equipes e GPs são reais ou inspirados em nomes reais, mas os resultados, investimentos, patrocínios e métricas operacionais são fictícios.

A missão é transformar dados sujos em um relatório analítico confiável.

## Irão usar os métodos e funções que vimos nas aulas até então:

- **head()**, **tail()**, **info()**, **describe()**, **shape**, **columns**, **dtypes**, **isnull()**
- seleção de colunas, linhas, **loc**, **iloc**
- filtros, ordenação, criação/atualização de colunas, renomeação
- **isnull().sum()**, **dropna()**, **fillna()**, **duplicated()**, **drop_duplicates()**
- **astype()**, **replace()**, **str.lower()**, **str.strip()**, **str.upper()**
- **concat()**, **merge()**, **join()**
- **groupby** e agregações
- **MultiIndex**
- **pivot_table()** e **melt()**

---

In [1]:
import pandas as pd
import numpy as np

In [2]:
corridas_df = pd.read_csv('./data/f1/corridas.csv')
financeiro_df = pd.read_csv('./data/f1/financeiro.csv')
patrocinadores_df = pd.read_csv('./data/f1/patrocinadores.csv')
pilotos_df = pd.read_csv('./data/f1/pilotos.csv')
pitstops_df = pd.read_csv('./data/f1/pitstops.csv')
resultados_df = pd.read_csv('./data/f1/resultados.csv')

# **1 - Inspeção inicial**

### head() e tail()

**Use **head()** e **tail()** em todas as bases. O que você percebe sobre a estrutura geral?**

In [3]:
corridas_df.head()

   id_corrida   ano  rodada                gp  pais_gp    clima  temperatura_c
0       10001  2014       1       BAHRAIN GP    Canadá  nublado           20.0
1       10002  2014       2  Saudi Arabian GP   México    chuva           15.0
2       10003  2014       3     Australian GP  Bélgica    misto           27.0
3       10004  2014       4       Japanese GP  Holanda    SECO            21.0
4       10005  2014       5        Chinese GP  Holanda     seco           31.0

In [4]:
corridas_df.tail()

,id_corrida,ano,rodada,gp,pais_gp,clima,temperatura_c
238,10239,2025,18,United States GP,Hungria,nublado,19.0
239,10240,2025,19,Mexican GP,Áustria,chuva,36.0
240,10241,2025,20,Brazilian GP,Singapura,misto,28.0
241,10242,2025,21,Las Vegas GP,Bélgica,nublado,24.0
242,10243,2025,22,Abu Dhabi GP,Espanha,seco,19.0

A coluna **corridas** possui uma coluna de identificação que pode resultar em possíveis inconsistências no momento de união com outras bases que necessitem destas. Também há inconsistência no título dos GPs e na descrição do clima. Não está explícito em relação ao país, mas é possível que haja problemas.

In [5]:
financeiro_df.head()

,ano,equipe,investimento_desenvolvimento_m USD,verba_patrocinadores_m USD,forca_carro_indice
0,2014,Mercedes,142.45,44.61,93.53
1,2014,Red Bull,284.27,108.17,95.81
2,2014,Ferrari,282.55,130.51,86.15
3,2014,McLaren,260.26,148.08,92.97
4,2014,williams,NaN,84.71,74.47

In [6]:
financeiro_df.tail()

,ano,equipe,investimento_desenvolvimento_m USD,verba_patrocinadores_m USD,forca_carro_indice
120,2016,Toro Rosso,172.36,89.53,61.28
121,2020,Racing Point,212.7,128.22,75.83
122,2024,sauber,183.16,81.54,62.50
123,2019,Ferrari,257.66,92.06,84.61
124,2020,Haas,177.67,123.79,63.44

Possíveis nomes problemáticos nas equipes e também título de colunas com nomes problemáticos (investimento_desenvolvimento_m USD e verba_patrocinadores_m USD)

In [7]:
patrocinadores_df.head()

    ano      equipe patrocinador categoria_patrocinio  valor_estimado_m USD
0  2014   MERCEDES      Petronas            logística                 27.20
1  2014    Mercedes        Ineos               master                 12.10
2  2014    Mercedes   TeamViewer          combustível                 52.69
3  2014    Red Bull       Oracle           tecnologia                 22.06
4  2014    Red Bull      Mobil 1            logística                 23.23

In [8]:
patrocinadores_df.tail()

      ano  equipe patrocinador categoria_patrocinio  valor_estimado_m USD
355  2025  Sauber   Alfa Romeo               master                 35.33
356  2025  Sauber        Claro          combustível                 43.20
357  2025    Haas    MoneyGram          combustível                 49.95
358  2025    Haas  Alpinestars          combustível                 25.01
359  2025    Haas      Pirelli          combustível                 12.63

Novamente, títulos de colunas com formato problemático e nomes inconsistentes para equipe explicitamente.

In [9]:
pilotos_df.head()

,ano,id_piloto,piloto,equipe,nacionalidade,idade,experiencia_anos
0,2014,1,Lewis Hamilton,Mercedes,Itália,37,3
1,2014,2,Nico Rosberg,Mercedes,Itália,39,6
2,2014,3,Sebastian Vettel,Red Bull,Espanha,30,6
3,2014,4,Daniel Ricciardo,red bull,Austrália,26,0
4,2014,5,fernando alonso,Ferrari,Brasil,37,0

In [10]:
pilotos_df.tail()

,ano,id_piloto,piloto,equipe,nacionalidade,idade,experiencia_anos
235,2025,51,Jack Doohan,Alpine,China,24,11
236,2025,12,Nico Hulkenberg,Sauber,China,27,15
237,2025,52,Gabriel Bortoleto,Sauber,FRANÇA,22,17
238,2025,30,Esteban Ocon,Haas,Alemanha,29,14
239,2025,53,OLIVER BEARMAN,Haas,Mônaco,34,16

Nomes inconsistentes para pilotos, nacionalidades e equipes.

In [11]:
pitstops_df.head()

,id_corrida,ano,id_piloto,piloto,equipe,numero_pit,tempo_pit_s
0,10001,2014,1,Lewis Hamilton,Mercedes,1,3.238
1,10001,2014,2,Nico Rosberg,Mercedes,1,2.768
2,10001,2014,2,Nico Rosberg,Mercedes,2,3.142
3,10001,2014,2,Nico Rosberg,Mercedes,3,2.913
4,10001,2014,3,Sebastian Vettel,Red Bull,1,2.664

In [12]:
pitstops_df.tail()

,id_corrida,ano,id_piloto,piloto,equipe,numero_pit,tempo_pit_s
8627,10049,2016,2,Nico Rosberg,Mercedes,2,2.497
8628,10158,2022,22,Carlos Sainz,Ferrari,2,2.691
8629,10179,2023,10,Valtteri Bottas,Alfa Romeo,1,3.185
8630,10230,2025,21,Max Verstappen,Red Bull,1,2.557
8631,10209,2024,12,Nico Hulkenberg,Haas,1,3.401

Os métodos head e tail não foram o suficiente para detectar inconsistências.

In [13]:
resultados_df.head()

,id_corrida,ano,gp,id_piloto,piloto,equipe,posicao_final,pontos,voltas_completadas,melhor_volta_s,tempo_total_min
0,10001,2014,Bahrain GP,1,Lewis Hamilton,Mercedes,1,25,50,92.446,97.289
1,10001,2014,Bahrain GP,2,Nico Rosberg,Mercedes,DNF,0,22,93.164,NaN
2,10001,2014,Bahrain GP,3,sebastian vettel,Red Bull,5,10,45,90.692,102.982
3,10001,2014,Bahrain GP,4,Daniel Ricciardo,Red Bull,10,1,44,86.723,94.113
4,10001,2014,Bahrain GP,5,Fernando Alonso,Ferrari,4,12,63,92.319,108.053

In [14]:
resultados_df.tail()

,id_corrida,ano,gp,id_piloto,piloto,equipe,posicao_final,pontos,voltas_completadas,melhor_volta_s,tempo_total_min
4880,10188,2023,Austrian GP,21,Max Verstappen,Red Bull,5,10,71,82.839,104.892
4881,10146,2021,Hungarian GP,1,Lewis Hamilton,MERCEDES,14,0,68,99.990,96.591
4882,10052,2016,Belgian GP,22,Carlos Sainz,Toro Rosso,16,0,48,91.453,106.329
4883,10180,2023,australian gp,29,Lance Stroll,ASTON MARTIN,8,4,65,91.378,112.983
4884,10029,2015,Spanish GP,2,Nico Rosberg,Mercedes,6,8,51,90.706,95.474

Nomes inconsistentes de equipes, pilotos e GPs

### info()

**Use **info()** em todas as bases. Liste colunas com tipos problemáticos.**

In [15]:
corridas_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_corrida     243 non-null    int64
 1   ano            243 non-null    int64
 2   rodada         243 non-null    int64
 3   gp             243 non-null    str
 4   pais_gp        243 non-null    str
 5   clima          243 non-null    str
 6   temperatura_c  240 non-null    float64
dtypes: float64(1), int64(3), str(3)
memory usage: 19.3 KB

In [16]:
financeiro_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 5 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ano                                 125 non-null    int64
 1   equipe                              125 non-null    str
 2   investimento_desenvolvimento_m USD  124 non-null    str
 3   verba_patrocinadores_m USD          125 non-null    float64
 4   forca_carro_indice                  125 non-null    float64
dtypes: float64(2), int64(1), str(2)
memory usage: 6.7 KB

**investimento_desenvolvimento_m USD** possui tipo problemático (str e deveria ser float64)

In [17]:
patrocinadores_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ano                   360 non-null    int64
 1   equipe                360 non-null    str
 2   patrocinador          360 non-null    str
 3   categoria_patrocinio  360 non-null    str
 4   valor_estimado_m USD  360 non-null    float64
dtypes: float64(1), int64(1), str(3)
memory usage: 22.5 KB

In [18]:
pilotos_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ano               240 non-null    int64
 1   id_piloto         240 non-null    int64
 2   piloto            240 non-null    str
 3   equipe            240 non-null    str
 4   nacionalidade     240 non-null    str
 5   idade             237 non-null    str
 6   experiencia_anos  240 non-null    int64
dtypes: int64(3), str(4)
memory usage: 20.7 KB

A coluna **idade** está problemática (como str quando deveria ser float64)

In [19]:
pitstops_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8632 entries, 0 to 8631
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_corrida   8632 non-null   int64
 1   ano          8632 non-null   int64
 2   id_piloto    8632 non-null   int64
 3   piloto       8632 non-null   str
 4   equipe       8632 non-null   str
 5   numero_pit   8632 non-null   int64
 6   tempo_pit_s  8545 non-null   float64
dtypes: float64(1), int64(4), str(2)
memory usage: 652.9 KB

In [20]:
resultados_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4885 entries, 0 to 4884
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_corrida          4885 non-null   int64
 1   ano                 4885 non-null   int64
 2   gp                  4885 non-null   str
 3   id_piloto           4885 non-null   int64
 4   piloto              4885 non-null   str
 5   equipe              4885 non-null   str
 6   posicao_final       4885 non-null   str
 7   pontos              4885 non-null   int64
 8   voltas_completadas  4885 non-null   int64
 9   melhor_volta_s      4885 non-null   float64
 10  tempo_total_min     4511 non-null   float64
dtypes: float64(2), int64(5), str(4)
memory usage: 586.3 KB

A coluna **posicao_final** possui valor problemático (str quando deveria ser int64)

### shape, columns e dtypes

**Use **shape**, **columns** e **dtypes** em **resultados**, **financeiro** e **pitstops**.**

In [21]:
print(f'Corridas: {corridas_df.shape[0]} linhas e {corridas_df.shape[1]} colunas')
print(f'Colunas de Corridas: {corridas_df.columns}')
corridas_df.dtypes

Corridas: 243 linhas e 7 colunas
Colunas de Corridas: Index(['id_corrida', 'ano', 'rodada', 'gp', 'pais_gp', 'clima',
       'temperatura_c'],
      dtype='str')

id_corrida         int64
ano                int64
rodada             int64
gp                   str
pais_gp              str
clima                str
temperatura_c    float64
dtype: object

In [22]:
print(f'Financeiro: {financeiro_df.shape[0]} linhas e {corridas_df.shape[1]} colunas')
print(f'Colunas de Financeiro: {financeiro_df.columns}')
financeiro_df.dtypes

Financeiro: 125 linhas e 7 colunas
Colunas de Financeiro: Index(['ano', 'equipe', 'investimento_desenvolvimento_m USD',
       'verba_patrocinadores_m USD', 'forca_carro_indice'],
      dtype='str')

ano                                     int64
equipe                                    str
investimento_desenvolvimento_m USD        str
verba_patrocinadores_m USD            float64
forca_carro_indice                    float64
dtype: object

In [23]:
print(f'Patrocinadores: {patrocinadores_df.shape[0]} linhas e {patrocinadores_df.shape[1]} colunas')
print(f'Colunas de Patrocinadores: {patrocinadores_df.columns}')
patrocinadores_df.dtypes

Patrocinadores: 360 linhas e 5 colunas
Colunas de Patrocinadores: Index(['ano', 'equipe', 'patrocinador', 'categoria_patrocinio',
       'valor_estimado_m USD'],
      dtype='str')

ano                       int64
equipe                      str
patrocinador                str
categoria_patrocinio        str
valor_estimado_m USD    float64
dtype: object

In [24]:
print(f'Pilotos: {pilotos_df.shape[0]} linhas e {pilotos_df.shape[1]} colunas')
print(f'Colunas de Pilotos: {pilotos_df.columns}')
pilotos_df.dtypes

Pilotos: 240 linhas e 7 colunas
Colunas de Pilotos: Index(['ano', 'id_piloto', 'piloto', 'equipe', 'nacionalidade', 'idade',
       'experiencia_anos'],
      dtype='str')

ano                 int64
id_piloto           int64
piloto                str
equipe                str
nacionalidade         str
idade                 str
experiencia_anos    int64
dtype: object

In [25]:
print(f'Pitstops: {pilotos_df.shape[0]} linhas e {pitstops_df.shape[1]} colunas')
print(f'Colunas de Pitstops: {pitstops_df.columns}')
pitstops_df.dtypes

Pitstops: 240 linhas e 7 colunas
Colunas de Pitstops: Index(['id_corrida', 'ano', 'id_piloto', 'piloto', 'equipe', 'numero_pit',
       'tempo_pit_s'],
      dtype='str')

id_corrida       int64
ano              int64
id_piloto        int64
piloto             str
equipe             str
numero_pit       int64
tempo_pit_s    float64
dtype: object

In [26]:
print(f'Resultados: {resultados_df.shape[0]} linhas e {resultados_df.shape[1]} colunas')
print(f'Colunas dos Resultados: {resultados_df.columns}')
resultados_df.dtypes

Resultados: 4885 linhas e 11 colunas
Colunas dos Resultados: Index(['id_corrida', 'ano', 'gp', 'id_piloto', 'piloto', 'equipe',
       'posicao_final', 'pontos', 'voltas_completadas', 'melhor_volta_s',
       'tempo_total_min'],
      dtype='str')

id_corrida              int64
ano                     int64
gp                        str
id_piloto               int64
piloto                    str
equipe                    str
posicao_final             str
pontos                  int64
voltas_completadas      int64
melhor_volta_s        float64
tempo_total_min       float64
dtype: object

### describe()

In [27]:
resultados_df.describe()

,id_corrida,ano,id_piloto,pontos,voltas_completadas,melhor_volta_s,tempo_total_min
count,4885.000000,4885.000000,4885.000000,4885.000000,4885.000000,4885.000000,4511.000000
mean,10121.981167,2019.715251,20.993859,4.815763,53.405527,91.695960,100.762848
std,70.122232,3.465192,14.449663,7.069362,12.320784,4.452067,6.857793
min,10001.000000,2014.000000,1.000000,0.000000,1.000000,76.115000,77.106000
25%,10061.000000,2017.000000,8.000000,0.000000,46.000000,88.690000,96.135000
50%,10122.000000,2020.000000,21.000000,0.000000,54.000000,91.670000,100.893000
75%,10183.000000,2023.000000,34.000000,8.000000,63.000000,94.679000,105.370000
max,10243.000000,2025.000000,53.000000,25.000000,71.000000,109.703000,124.307000

In [28]:
financeiro_df.describe()

              ano  verba_patrocinadores_m USD  forca_carro_indice
count   125.00000                  125.000000           125.00000
mean   2019.51200                  111.648720            76.97824
std       3.43515                   34.203022            12.31183
min    2014.00000                   31.140000            45.83000
25%    2017.00000                   87.180000            67.09000
50%    2020.00000                  109.030000            75.83000
75%    2022.00000                  132.090000            86.10000
max    2025.00000                  203.360000           100.07000

In [29]:
pitstops_df.describe()

         id_corrida          ano    id_piloto   numero_pit  tempo_pit_s
count   8632.000000  8632.000000  8632.000000  8632.000000  8545.000000
mean   10121.898285  2019.711770    21.085148     1.556302     2.765839
std       70.376404     3.477336    14.504940     0.722276     0.553352
min    10001.000000  2014.000000     1.000000     1.000000     0.409000
25%    10061.000000  2017.000000     8.000000     1.000000     2.393000
50%    10122.000000  2020.000000    21.000000     1.000000     2.770000
75%    10183.000000  2023.000000    35.000000     2.000000     3.139000
max    10243.000000  2025.000000    53.000000     4.000000     4.796000

### nulos

**Use **isnull()** e **isnull().sum()** em todas as bases. Explique por que isso ainda não detecta todos os problemas.**

In [30]:
corridas_df.isnull().sum()

id_corrida       0
ano              0
rodada           0
gp               0
pais_gp          0
clima            0
temperatura_c    3
dtype: int64

In [31]:
financeiro_df.isnull().sum()

ano                                   0
equipe                                0
investimento_desenvolvimento_m USD    1
verba_patrocinadores_m USD            0
forca_carro_indice                    0
dtype: int64

In [32]:
patrocinadores_df.isnull().sum()

ano                     0
equipe                  0
patrocinador            0
categoria_patrocinio    0
valor_estimado_m USD    0
dtype: int64

In [33]:
pilotos_df.isnull().sum()

ano                 0
id_piloto           0
piloto              0
equipe              0
nacionalidade       0
idade               3
experiencia_anos    0
dtype: int64

In [34]:
pitstops_df.isnull().sum()

id_corrida      0
ano             0
id_piloto       0
piloto          0
equipe          0
numero_pit      0
tempo_pit_s    87
dtype: int64

In [35]:
resultados_df.isnull().sum()

id_corrida              0
ano                     0
gp                      0
id_piloto               0
piloto                  0
equipe                  0
posicao_final           0
pontos                  0
voltas_completadas      0
melhor_volta_s          0
tempo_total_min       374
dtype: int64

A detecção de nulos não é capaz de ver valores em string vazios ou representação de strings vazias (como '-').

# 2 - Seleções, filtros e ordenação

**Selecione em **resultados** apenas: **ano**, **gp**, **piloto**, **equipe**, **posicao_final**, **pontos**.**

In [36]:
resultados_df[['ano', 'gp', 'piloto', 'equipe', 'posicao_final', 'pontos']].head(7)

    ano            gp            piloto     equipe posicao_final  pontos
0  2014    Bahrain GP    Lewis Hamilton   Mercedes             1      25
1  2014    Bahrain GP      Nico Rosberg   Mercedes           DNF       0
2  2014    Bahrain GP  sebastian vettel   Red Bull             5      10
3  2014    Bahrain GP  Daniel Ricciardo   Red Bull            10       1
4  2014    Bahrain GP   Fernando Alonso    Ferrari             4      12
5  2014    bahrain gp    Kimi Raikkonen   ferrari             11       0
6  2014   BAHRAIN GP      Jenson Button    McLaren             3      15

**Selecione linhas 10 até 30 e colunas **piloto**, **equipe**, **pontos** usando **loc**.**

In [37]:
resultados_df.loc[10 : 30, ['piloto', 'equipe', 'pontos']]

                piloto       equipe  pontos
10        Sergio Perez  Force India       0
11     Nico Hulkenberg  Force India       8
12    Jean-Eric Vergne   Toro Rosso       0
13        Daniil Kvyat   Toro Rosso       0
14    ROMAIN GROSJEAN         Lotus       0
15    Pastor Maldonado        Lotus       2
16        Adrian Sutil       Sauber       0
17   Esteban Gutierrez       Sauber       0
18      jules bianchi      Marussia       0
19         Max Chilton     Marussia       0
20      Lewis Hamilton     Mercedes       6
21        Nico Rosberg     Mercedes      12
22   sebastian vettel     RED BULL       10
23    daniel ricciardo     Red Bull      25
24     Fernando Alonso     FERRARI        2
25      Kimi Raikkonen      Ferrari      18
26      JENSON BUTTON       McLaren      15
27     Kevin Magnussen     MCLAREN        8
28        Felipe Massa     williams       1
29     Valtteri Bottas     Williams       0
30        Sergio Perez  Force India       0

**Selecione as primeiras 20 linhas e as 6 primeiras colunas usando **iloc**.**

In [38]:
resultados_df.iloc[ :20, :6]

    id_corrida   ano            gp  id_piloto             piloto       equipe
0        10001  2014    Bahrain GP          1     Lewis Hamilton     Mercedes
1        10001  2014    Bahrain GP          2       Nico Rosberg     Mercedes
2        10001  2014    Bahrain GP          3   sebastian vettel     Red Bull
3        10001  2014    Bahrain GP          4   Daniel Ricciardo     Red Bull
4        10001  2014    Bahrain GP          5    Fernando Alonso      Ferrari
5        10001  2014    bahrain gp          6     Kimi Raikkonen     ferrari
6        10001  2014   BAHRAIN GP           7      Jenson Button      McLaren
7        10001  2014    Bahrain GP          8    Kevin Magnussen      McLaren
8        10001  2014   BAHRAIN GP           9      FELIPE MASSA      Williams
9        10001  2014    Bahrain GP         10    Valtteri Bottas     Williams
10       10001  2014    Bahrain GP         11       Sergio Perez  Force India
11       10001  2014    Bahrain GP         12    Nico Hulkenberg  Force India
12       10001  2014    bahrain gp         13   Jean-Eric Vergne   Toro Rosso
13       10001  2014    Bahrain GP         14       Daniil Kvyat   Toro Rosso
14       10001  2014   bahrain gp          15   ROMAIN GROSJEAN         Lotus
15       10001  2014    Bahrain GP         16   Pastor Maldonado        Lotus
16       10001  2014    Bahrain GP         17       Adrian Sutil       Sauber
17       10001  2014    Bahrain GP         18  Esteban Gutierrez       Sauber
18       10001  2014    Bahrain GP         19     jules bianchi      Marussia
19       10001  2014    Bahrain GP         20        Max Chilton     Marussia

**Filtre resultados de **Ferrari** ou **Mercedes** com **pontos >= 15**. Atenção ao veneno textual.**

In [39]:
resultados_df['equipe'] = resultados_df['equipe'].str.strip().str.capitalize()

In [40]:
resultados_df['equipe'].value_counts()

equipe
Mercedes        490
Ferrari         490
Mclaren         489
Red bull        488
Williams        487
Haas            411
Sauber          279
Toro rosso      229
Aston martin    223
Alpine          221
Alfa romeo      208
Force india     191
Renault         190
Alphatauri      171
Rb               88
Racing point     78
Lotus            76
Marussia         38
Manor            38
Name: count, dtype: int64

In [41]:
filter = ((resultados_df['equipe'] == 'Ferrari') | (resultados_df['equipe'] == 'Mercedes')) & (resultados_df['pontos'] >= 15)

resultados_df[filter].head(7)

,id_corrida,ano,gp,id_piloto,piloto,equipe,posicao_final,pontos,voltas_completadas,melhor_volta_s,tempo_total_min
0,10001,2014,Bahrain GP,1,Lewis Hamilton,Mercedes,1,25,50,92.446,97.289
25,10002,2014,Saudi Arabian GP,6,Kimi Raikkonen,Ferrari,2,18,46,91.886,94.685
40,10003,2014,Australian GP,1,Lewis Hamilton,Mercedes,2,18,56,92.391,100.060
80,10005,2014,Chinese GP,1,Lewis Hamilton,Mercedes,3,15,52,86.453,87.737
160,10009,2014,Canadian GP,1,Lewis Hamilton,Mercedes,2,18,70,93.234,90.451
164,10009,2014,Canadian GP,5,Fernando Alonso,Ferrari,1,25,60,93.415,103.784
200,10011,2014,Austrian GP,1,Lewis Hamilton,Mercedes,2,18,43,85.374,85.442

**Ordene os resultados por **ano** crescente e **pontos** decrescente.**

In [42]:
res_ano_asc = resultados_df['ano'].sort_values().index

resultados_df.loc[res_ano_asc]

,id_corrida,ano,gp,id_piloto,piloto,equipe,posicao_final,pontos,voltas_completadas,melhor_volta_s,tempo_total_min
52,10003,2014,AUSTRALIAN GP,13,Jean-Eric Vergne,Toro rosso,15,0,52,94.798,96.328
75,10004,2014,Japanese GP,16,Pastor Maldonado,Lotus,17,0,43,94.888,93.175
74,10004,2014,Japanese GP,15,Romain Grosjean,Lotus,DNF,0,36,97.062,NaN
73,10004,2014,Japanese GP,14,Daniil Kvyat,Toro rosso,14,0,57,93.107,105.586
72,10004,2014,Japanese GP,13,Jean-Eric Vergne,Toro rosso,13,0,69,88.240,100.352
...,...,...,...,...,...,...,...,...,...,...,...
4823,10242,2025,Las Vegas GP,11,Sergio Perez,Red bull,13,0,52,100.084,107.394
4420,10222,2025,Bahrain GP,37,George Russell,Mercedes,3,15,54,93.522,106.926
4854,10243,2025,Abu Dhabi GP,33,Pierre Gasly,Alpine,11,0,59,93.107,102.136
4853,10243,2025,Abu Dhabi GP,50,Liam Lawson,Rb,17,0,46,91.097,102.285
4859,10243,2025,Abu Dhabi GP,53,Oliver Bearman,Haas,20,0,48,97.181,110.966

In [43]:
res_ano_desc = resultados_df['ano'].sort_values(ascending=False).index

resultados_df.loc[res_ano_desc]

,id_corrida,ano,gp,id_piloto,piloto,equipe,posicao_final,pontos,voltas_completadas,melhor_volta_s,tempo_total_min
4834,10242,2025,LAS VEGAS GP,33,Pierre Gasly,Alpine,10,1,58,100.711,96.752
4859,10243,2025,Abu Dhabi GP,53,Oliver Bearman,Haas,20,0,48,97.181,110.966
4858,10243,2025,Abu Dhabi GP,30,esteban ocon,Haas,DNF,0,7,98.922,NaN
4426,10222,2025,Bahrain GP,36,Lando Norris,Mclaren,5,10,69,88.887,101.372
4427,10222,2025,Bahrain GP,46,OSCAR PIASTRI,Mclaren,1,25,70,92.321,85.716
...,...,...,...,...,...,...,...,...,...,...,...
63,10004,2014,Japanese GP,4,Daniel Ricciardo,Red bull,1,25,49,87.970,93.557
62,10004,2014,Japanese GP,3,Sebastian Vettel,Red bull,2,18,65,89.696,101.178
22,10002,2014,saudi arabian gp,3,sebastian vettel,Red bull,5,10,56,88.605,94.234
21,10002,2014,Saudi Arabian GP,2,Nico Rosberg,Mercedes,4,12,63,85.302,102.648
20,10002,2014,Saudi Arabian GP,1,Lewis Hamilton,Mercedes,7,6,63,91.431,88.192

**Crie uma coluna **podio** em **resultados**, indicando **Sim** quando a posição final for 1, 2 ou 3.**

In [44]:
resultados_df['posicao_final'].value_counts()

posicao_final
DNF    280
9      237
2      236
5      235
6      235
11     234
3      234
7      234
8      233
4      231
14     231
10     230
13     230
12     230
1      229
16     229
18     227
20     225
15     224
17     221
19     220
Name: count, dtype: int64

In [45]:
resultados_df['podio'] = 'Nao'

dnf = resultados_df['posicao_final'] == 'DNF'
resultados_df.loc[dnf, ['posicao_final']] = '99'

resultados_df[dnf]

,id_corrida,ano,gp,id_piloto,piloto,equipe,posicao_final,pontos,voltas_completadas,melhor_volta_s,tempo_total_min,podio
1,10001,2014,Bahrain GP,2,Nico Rosberg,Mercedes,99,0,22,93.164,NaN,Nao
12,10001,2014,bahrain gp,13,Jean-Eric Vergne,Toro rosso,99,0,37,94.676,NaN,Nao
30,10002,2014,Saudi Arabian GP,11,Sergio Perez,Force india,99,0,15,93.694,NaN,Nao
48,10003,2014,Australian GP,9,Felipe Massa,Williams,99,0,21,96.773,NaN,Nao
74,10004,2014,Japanese GP,15,Romain Grosjean,Lotus,99,0,36,97.062,NaN,Nao
...,...,...,...,...,...,...,...,...,...,...,...,...
4802,10241,2025,brazilian gp,21,MAX VERSTAPPEN,Red bull,99,0,4,98.558,NaN,Nao
4839,10242,2025,Las Vegas GP,53,Oliver Bearman,Haas,99,0,16,95.607,NaN,Nao
4858,10243,2025,Abu Dhabi GP,30,esteban ocon,Haas,99,0,7,98.922,NaN,Nao
4864,10191,2023,Belgian GP,29,Lance Stroll,Aston martin,99,0,31,88.573,NaN,Nao
4867,10020,2015,Bahrain GP,7,Jenson Button,Mclaren,99,0,5,87.845,NaN,Nao

In [46]:
resultados_df['posicao_final'] = resultados_df['posicao_final'].astype(int)

podio = resultados_df['posicao_final'] <= 3
resultados_df[podio].head()

,id_corrida,ano,gp,id_piloto,piloto,equipe,posicao_final,pontos,voltas_completadas,melhor_volta_s,tempo_total_min,podio
0,10001,2014,Bahrain GP,1,Lewis Hamilton,Mercedes,1,25,50,92.446,97.289,Nao
6,10001,2014,BAHRAIN GP,7,Jenson Button,Mclaren,3,15,47,89.456,84.603,Nao
7,10001,2014,Bahrain GP,8,Kevin Magnussen,Mclaren,2,18,47,89.499,86.733,Nao
23,10002,2014,Saudi Arabian GP,4,daniel ricciardo,Red bull,1,25,62,87.266,94.133,Nao
25,10002,2014,Saudi Arabian GP,6,Kimi Raikkonen,Ferrari,2,18,46,91.886,94.685,Nao

In [82]:
resultados_df.loc[podio, 'podio'] = 'Sim'

resultados_df[podio].head()

,id_corrida,ano,gp,id_piloto,piloto,equipe,posicao_final,pontos,voltas_completadas,melhor_volta_s,tempo_total_min,podio
0,10001,2014,Bahrain GP,1,Lewis Hamilton,Mercedes,1,25,50,92.446,97.289,Sim
6,10001,2014,BAHRAIN GP,7,Jenson Button,Mclaren,3,15,47,89.456,84.603,Sim
7,10001,2014,Bahrain GP,8,Kevin Magnussen,Mclaren,2,18,47,89.499,86.733,Sim
23,10002,2014,Saudi Arabian GP,4,daniel ricciardo,Red bull,1,25,62,87.266,94.133,Sim
25,10002,2014,Saudi Arabian GP,6,Kimi Raikkonen,Ferrari,2,18,46,91.886,94.685,Sim

**Renomeie colunas financeiras para nomes mais fáceis: **investimento_desenvolvimento_m USD** → **investimento_musd**; **verba_patrocinadores_m USD** → **patrocinio_musd**.**

In [88]:
new_columns = {}
for col in financeiro_df.columns.values:
    new_columns[col] = col

new_columns

{'ano': 'ano',
 'equipe': 'equipe',
 'investimento_desenvolvimento_m USD': 'investimento_desenvolvimento_m USD',
 'verba_patrocinadores_m USD': 'verba_patrocinadores_m USD',
 'forca_carro_indice': 'forca_carro_indice'}

In [89]:
new_columns['investimento_desenvolvimento_m USD'] = 'investimento_musd'
new_columns['verba_patrocinadores_m USD'] = 'patrocinio_musd'

new_columns

{'ano': 'ano',
 'equipe': 'equipe',
 'investimento_desenvolvimento_m USD': 'investimento_musd',
 'verba_patrocinadores_m USD': 'patrocinio_musd',
 'forca_carro_indice': 'forca_carro_indice'}

In [ ]:
financeiro_df.rename(columns=new_columns, inplace=True)
financeiro_df.head()

# 3 - Limpeza

**Substitua falsos nulos (**N/A**, espaço vazio e **nao informado**) por **np.nan** em todas as bases.**

In [48]:
# Escreva sua resposta aqui

**Aplique **str.strip()** e **str.upper()** nas chaves textuais importantes: **piloto**, **equipe**, **gp**, **clima**, **patrocinador**.**

In [49]:
# Escreva sua resposta aqui

**Corrija **idade**: remova o texto **' anos'** e converta para número.**

In [50]:
# Escreva sua resposta aqui

**Corrija **investimento_musd**: troque vírgula por ponto e converta para **float**.**

In [51]:
# Escreva sua resposta aqui

**Use **fillna()** para preencher clima desconhecido e temperatura ausente.**

In [52]:
# Escreva sua resposta aqui

**Use **dropna()** para remover linhas sem **posicao_final** ou sem **id_piloto**, se existirem.**

In [53]:
# Escreva sua resposta aqui

**Detecte duplicatas em **resultados**, **pitstops** e **financeiro**. Depois remova duplicatas com critério adequado.**

In [54]:
# Escreva sua resposta aqui

**Explique por que remover duplicata pela linha inteira nem sempre é suficiente.**

In [55]:
# Escreva sua resposta aqui

# 4 - Integração com concat, merge e join

Separe **resultados** em duas partes: até 2019 e de 2020 em diante. Recombine usando **concat()** e valide o tamanho.

In [56]:
# Escreva sua resposta aqui

**Faça **merge** entre **resultados** e **corridas** usando **id_corrida**. Use **how='left'**.**

In [57]:
# Escreva sua resposta aqui

**Faça **merge** entre resultados e financeiro por **ano** e **equipe**. Teste **inner**, **left**, **right** e **outer**; compare os tamanhos.**

In [58]:
# Escreva sua resposta aqui

**Explique por que **merge** com patrocinadores pode multiplicar linhas.**

In [59]:
# Escreva sua resposta aqui

**Agregue patrocinadores por **ano** e **equipe** antes do merge. Depois junte com resultados.**

In [60]:
# Escreva sua resposta aqui

**Use **join()** colocando **ano** e **equipe** como índice em duas bases.**

In [61]:
# Escreva sua resposta aqui

# 5 - Groupby e agregações

**Calcule total de pontos por piloto e ano.**

In [62]:
# Escreva sua resposta aqui

**Calcule total de pontos por equipe e ano.**

In [63]:
# Escreva sua resposta aqui

**Calcule média, soma, mínimo e máximo de pontos por equipe.**

In [64]:
# Escreva sua resposta aqui

**Calcule média de pit stop por piloto, equipe e ano.**

In [65]:
# Escreva sua resposta aqui

**Calcule quantidade de pódios por piloto e equipe.**

In [66]:
# Escreva sua resposta aqui

**Calcule correlação simples entre investimento e pontos por equipe/ano. Interprete com cuidado.**

In [67]:
# Escreva sua resposta aqui

# 6 - MultiIndex

**Crie um relatório por **ano**, **equipe** e **piloto**, com soma de pontos, média de posição e quantidade de pódios.**

In [68]:
# Escreva sua resposta aqui

**Transforme esse relatório em MultiIndex com **ano**, **equipe**, **piloto**.**

In [69]:
# Escreva sua resposta aqui

**Ordene o MultiIndex.**

In [70]:
# Escreva sua resposta aqui

**Selecione dados do ano 2024 usando **loc**.**

In [71]:
# Escreva sua resposta aqui

# 7 - Pivot table e melt

**Crie uma **pivot_table** com linhas = **ano**, colunas = **equipe**, valores = pontos totais.**

In [72]:
# Escreva sua resposta aqui

**Crie uma **pivot_table** com **aggfunc=['sum','mean','max']** para pontos por equipe.**

In [73]:
# Escreva sua resposta aqui

**Explique por que a pivot_table anterior gera MultiIndex nas colunas.**

In [74]:
# Escreva sua resposta aqui

**Use **melt()** para transformar o financeiro de formato largo para longo, com métricas de investimento, patrocínio e força do carro.**

In [75]:
# Escreva sua resposta aqui

**Explique a diferença entre tabela larga e tabela longa.**

In [76]:
# Escreva sua resposta aqui

# Desafio final de produção

**Construa um relatório final com: ano, equipe, piloto, pontos totais, média de posição, pódios, média de pit stop, investimento, patrocínio e total estimado de patrocinadores.**

In [77]:
# Escreva sua resposta aqui

**Ordene o relatório por ano, pontos totais e investimento.**

In [78]:
# Escreva sua resposta aqui

**Liste os 10 melhores pilotos por pontuação acumulada em todo o período.**

In [79]:
# Escreva sua resposta aqui

**Liste as 10 equipes com maior investimento acumulado.**

In [80]:
# Escreva sua resposta aqui

**Discuta 5 riscos analíticos desse pipeline.**

In [81]:
# Escreva sua resposta aqui

1 - Faça um resumo executivo da ULTIMA temporada.

2 - Crie 5 insights relevantes encontrados nos dados.

3 - Crie 3 recomendações estratégicas para uma equipe.

4 - Quais dados adicionais você gostaria de ter?

5 - Qual gráfico melhor representaria:
dominância;
eficiência;
evolução;
consistência?