## Contexto

Você foi contratado como analista de dados de um e-commerce. A diretoria trouxe algumas perguntas:

> "Estamos vendendo bem? Quais clientes são mais importantes? Quais categorias dão mais receita? Estamos perdendo pedidos por problemas de pagamento?"

O problema: os dados vieram sujos, inconsistentes, espalhados em várias tabelas e agora em volume maior, com aproximadamente 5.000 registros em cada base principal.

---

## Objetivos técnicos

Neste case, você deverá aplicar:

- **head()**, **tail()**, **info()**, **describe()**, **shape**, **columns**, **dtypes**
- **isnull()**, **isnull().sum()**
- seleção de colunas
- seleção de linhas
- **.loc[]**
- **.iloc[]**
- filtros com condições
- ordenação
- criação e atualização de colunas
- renomeação de colunas
- **dropna()**, **fillna()**
- **duplicated()**, **drop_duplicates()**
- **astype()**, **replace()**
- **.str.lower()**, **.str.strip()**, **.str.upper()**
- **concat()**, **merge()**, **join()**
- **groupby()** e funções de agregação

---

## Entregável final

Ao final, você deverá produzir um pequeno relatório executivo respondendo:

1. Qual foi o faturamento total?
2. Qual cidade gerou mais receita?
3. Qual categoria teve maior faturamento?
4. Qual segmento de cliente compra mais?
5. Qual cliente mais gastou?
6. Qual percentual dos pedidos está pendente ou cancelado?
7. Existe perda de receita por pagamentos não aprovados?
8. Quais pedidos ficaram sem informação de pagamento?
9. Qual ticket médio por cidade?
10. Que recomendações de negócio você faria?
11. Notebook com as implementações e respostas para as perguntas acima e no final.

## 1. Criação dos dataframes.

In [1]:
import pandas as pd
import numpy as np

clientes_df = pd.read_csv('./data/e_commerce/clientes.csv')
pagamentos_df = pd.read_csv('./data/e_commerce/pagamentos.csv')
pedidos_df = pd.read_csv('./data/e_commerce/pedidos.csv')
lote_2_df = pd.read_csv('./data/e_commerce/pedidos_lote2.csv')

## 2. Exploração inicial

Use os métodos abaixo nas três bases:

- **head()**
- **tail()**
- **info()**
- **describe()**
- **shape**
- **columns**
- **dtypes**
- **isnull()**
- **isnull().sum()**

### Perguntas

1. Quantas linhas e colunas existem em CADA base?
2. Quais colunas possuem valores nulos?
3. Quais colunas estão com tipo de dado inadequado?
4. Existem inconsistências textuais?
5. Existem possíveis chaves sem correspondência entre as tabelas?

#### Dataset Clientes

In [2]:
print(f'A base clientes possui {clientes_df.shape[0]} linhas e {clientes_df.shape[1]} colunas')

print('\nColunas com valores nulos:')
clientes_df.isnull().sum()

A base clientes possui 5000 linhas e 6 colunas

Colunas com valores nulos:

Unnamed: 0      0
cliente_id      0
nome            0
cidade        577
segmento      485
idade         510
dtype: int64

In [3]:
clientes_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  5000 non-null   int64
 1   cliente_id  5000 non-null   int64
 2   nome        5000 non-null   str
 3   cidade      4423 non-null   str
 4   segmento    4515 non-null   str
 5   idade       4490 non-null   float64
dtypes: float64(1), int64(2), str(3)
memory usage: 373.4 KB

In [4]:
clientes_df.head()

   Unnamed: 0  cliente_id         nome          cidade segmento  idade
0           0           1   Cliente_1        São Paulo      NaN   35.0
1           1           2   Cliente_2              NaN  Regular   30.0
2           2           3   Cliente_3           Recife     Novo   30.0
3           3           4   Cliente_4   Rio de Janeiro     Novo   30.0
4           4           5   Cliente_5        Fortaleza  Regular   30.0

In [5]:
clientes_df.tail()

      Unnamed: 0  cliente_id            nome     cidade segmento  idade
4995        4995        1804   Cliente_1804   São Paulo  Regular   22.0
4996        4996         721    Cliente_721         NaN  Regular   30.0
4997        4997         427    Cliente_427   São Paulo      NaN   22.0
4998        4998        3334   Cliente_3334   Fortaleza     Novo   18.0
4999        4999         394    Cliente_394      Recife     Novo   45.0

In [6]:
clientes_df.drop('Unnamed: 0', axis='columns', inplace=True)

In [7]:
clientes_df.describe()

        cliente_id        idade
count  5000.000000  4490.000000
mean   2489.280600    29.955011
std    1437.621535     8.302572
min       1.000000    18.000000
25%    1242.750000    22.000000
50%    2488.500000    30.000000
75%    3732.250000    35.000000
max    4980.000000    45.000000

In [8]:
clientes_df.columns

Index(['cliente_id', 'nome', 'cidade', 'segmento', 'idade'], dtype='str')

In [9]:
clientes_df.dtypes

cliente_id      int64
nome              str
cidade            str
segmento          str
idade         float64
dtype: object

Aparentemente, nenhuma colunas com tipo de valor inconsistente na base de dados de clientes. Também não parece haver inconsistência nos tipos de dados das colunas dos pedidos e do segundo lote.

#### Dataset Pedidos e Pedidos Lote 2

In [10]:
print(f'Dataset pedidos possui {pedidos_df.shape[0]} linhas e {pedidos_df.shape[1]} colunas')
print(f'Lote 2 dos pedidos possui {lote_2_df.shape[0]} linhas e {lote_2_df.shape[1]} colunas')

print('\nPedidos com valores nulos:')
pedidos_df.isnull().sum()

Dataset pedidos possui 5000 linhas e 6 colunas
Lote 2 dos pedidos possui 500 linhas e 6 colunas

Pedidos com valores nulos:

Unnamed: 0      0
pedido_id       0
cliente_id      0
categoria       0
valor         252
quantidade      0
dtype: int64

In [11]:
print('Lote 2 com valores nulos:')
lote_2_df.isnull().sum()

Lote 2 com valores nulos:

Unnamed: 0     0
pedido_id      0
cliente_id     0
categoria      0
valor         23
quantidade     0
dtype: int64

In [12]:
pedidos_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  5000 non-null   int64
 1   pedido_id   5000 non-null   int64
 2   cliente_id  5000 non-null   int64
 3   categoria   5000 non-null   str
 4   valor       4748 non-null   float64
 5   quantidade  5000 non-null   int64
dtypes: float64(1), int64(4), str(1)
memory usage: 276.5 KB

In [13]:
lote_2_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  500 non-null    int64
 1   pedido_id   500 non-null    int64
 2   cliente_id  500 non-null    int64
 3   categoria   500 non-null    str
 4   valor       477 non-null    float64
 5   quantidade  500 non-null    int64
dtypes: float64(1), int64(4), str(1)
memory usage: 27.8 KB

In [14]:
pedidos_df.head()

   Unnamed: 0  pedido_id  cliente_id     categoria  valor  quantidade
0           0     100001        1523  eletronicos   600.0           3
1           1     100002        1335   Eletrônicos   80.0           7
2           2     100003        5391          Casa  600.0           4
3           3     100004        2624     Alimentos  400.0           3
4           4     100005         239        Roupas  250.0           3

In [15]:
lote_2_df.head()

   Unnamed: 0  pedido_id  cliente_id    categoria  valor  quantidade
0           0     105001        4503  Eletrônicos   80.0           6
1           1     105002        1383         Casa  600.0           2
2           2     105003        4982         Casa   80.0           1
3           3     105004        4969    Alimentos   80.0           5
4           4     105005        5086       Roupas  250.0           1

In [16]:
pedidos_df.tail()

      Unnamed: 0  pedido_id  cliente_id    categoria  valor  quantidade
4995        4995     104996        1811  Eletrônicos  400.0           2
4996        4996     104997        3202       Roupas  600.0           7
4997        4997     104998         753  Eletrônicos  120.0           1
4998        4998     104999        2473       Roupas  600.0           3
4999        4999     105000        5033  Eletrônicos  250.0           6

In [17]:
lote_2_df.tail()

     Unnamed: 0  pedido_id  cliente_id    categoria  valor  quantidade
495         495     105496        2661  Eletrônicos  250.0           2
496         496     105497        2263  Eletrônicos  600.0           4
497         497     105498        4358    Alimentos  600.0           3
498         498     105499         764         Casa  400.0           1
499         499     105500        2368    Alimentos   80.0           6

In [18]:
pedidos_df.drop('Unnamed: 0', axis='columns', inplace=True)
lote_2_df.drop('Unnamed: 0', axis='columns', inplace=True)

In [19]:
pedidos_df.describe()

           pedido_id  cliente_id        valor   quantidade
count    5000.000000   5000.0000  4748.000000  5000.000000
mean   102500.500000   2723.5960   322.900168     4.028600
std      1443.520003   1574.4692   239.252208     2.011912
min    100001.000000      1.0000    80.000000     1.000000
25%    101250.750000   1375.7500   120.000000     2.000000
50%    102500.500000   2751.5000   250.000000     4.000000
75%    103750.250000   4044.2500   400.000000     6.000000
max    105000.000000   5480.0000   900.000000     7.000000

In [20]:
lote_2_df.describe()

           pedido_id   cliente_id       valor  quantidade
count     500.000000   500.000000  477.000000  500.000000
mean   105250.500000  2775.960000  315.974843    3.956000
std       144.481833  1495.864807  233.783602    2.086809
min    105001.000000     4.000000   80.000000    1.000000
25%    105125.750000  1614.000000  120.000000    2.000000
50%    105250.500000  2687.000000  250.000000    4.000000
75%    105375.250000  3973.000000  400.000000    6.000000
max    105500.000000  5438.000000  900.000000    7.000000

In [21]:
print('Colunas de pedidos:')
print(pedidos_df.columns)
print('\nColunas do lote 2 de pedidos:')
print(lote_2_df.columns)

Colunas de pedidos:
Index(['pedido_id', 'cliente_id', 'categoria', 'valor', 'quantidade'], dtype='str')

Colunas do lote 2 de pedidos:
Index(['pedido_id', 'cliente_id', 'categoria', 'valor', 'quantidade'], dtype='str')

In [22]:
print('Tipos das colunas de pedidos:')
print(pedidos_df.dtypes)
print('\nTipos das colunas do segundo lote:')
print(lote_2_df.dtypes)

Tipos das colunas de pedidos:
pedido_id       int64
cliente_id      int64
categoria         str
valor         float64
quantidade      int64
dtype: object

Tipos das colunas do segundo lote:
pedido_id       int64
cliente_id      int64
categoria         str
valor         float64
quantidade      int64
dtype: object

Pode haver inconsistências entre os ids de clientes na tabela de clientes e id de clientes nas tabelas de pedidos.

#### Dataset Pagamentos

In [23]:
print(f'Dataset de pagamentos possui {pagamentos_df.shape[0]} linhas e {pagamentos_df.shape[1]} colunas')

print('\nValores nulos em pagamentos:')
pagamentos_df.isnull().sum()

Dataset de pagamentos possui 5000 linhas e 4 colunas

Valores nulos em pagamentos:

Unnamed: 0            0
pedido_id             0
forma_pagamento     544
status_pagamento      0
dtype: int64

In [24]:
pagamentos_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        5000 non-null   int64
 1   pedido_id         5000 non-null   int64
 2   forma_pagamento   4456 non-null   str
 3   status_pagamento  5000 non-null   str
dtypes: int64(2), str(2)
memory usage: 208.0 KB

In [25]:
pagamentos_df.head()

   Unnamed: 0  pedido_id forma_pagamento status_pagamento
0           0     101269          Debito        Cancelado
1           1     104267             PIX             Pago
2           2     105746         Crédito             Pago
3           3     104817            pix          Pendente
4           4     103043          Debito             Pago

In [26]:
pagamentos_df.tail()

      Unnamed: 0  pedido_id forma_pagamento status_pagamento
4995        4995     101307             NaN             Pago
4996        4996     105333             NaN             Pago
4997        4997     101688          Debito             Pago
4998        4998     105798         Crédito        Cancelado
4999        4999     103984             PIX             Pago

In [27]:
pagamentos_df.drop('Unnamed: 0', axis='columns', inplace=True)

In [28]:
pagamentos_df.describe()

           pedido_id
count    5000.000000
mean   102992.939200
std      1750.051069
min    100001.000000
25%    101469.750000
50%    103013.000000
75%    104505.000000
max    106000.000000

In [29]:
pagamentos_df.columns

Index(['pedido_id', 'forma_pagamento', 'status_pagamento'], dtype='str')

In [30]:
pagamentos_df.dtypes

pedido_id           int64
forma_pagamento       str
status_pagamento      str
dtype: object

Também não parece haver inconsistência nos tipos de dados das counas de Pagamentos

## 3. Limpeza dos dados

### 3.1 Limpeza de strings

Corrija espaços extras e padronize textos.

Sugestões:

- **nome**: remover espaços
- **cidade**: remover espaços
- **segmento**: remover espaços e padronizar
- **categoria**: remover espaços, padronizar minúsculas e corrigir grafias
- **forma_pagamento**: remover espaços e padronizar
- **status_pagamento**: remover espaços e padronizar

#### Clientes

In [31]:
clientes_df.columns

Index(['cliente_id', 'nome', 'cidade', 'segmento', 'idade'], dtype='str')

In [32]:
clientes_df.replace(r'^/s*$', np.nan, regex=True, inplace=True).isna().sum()

cliente_id      0
nome            0
cidade        577
segmento      485
idade         510
dtype: int64

In [33]:
clientes_df.shape

(5000, 5)

In [34]:
clientes_df['nome'].str.strip().str.capitalize().value_counts()

nome
Cliente_394     2
Cliente_427     2
Cliente_721     2
Cliente_735     2
Cliente_1000    2
               ..
Cliente_4976    1
Cliente_4977    1
Cliente_4978    1
Cliente_4979    1
Cliente_4980    1
Name: count, Length: 4980, dtype: int64

In [35]:
clientes_df['nome'] = clientes_df['nome'].str.strip().str.capitalize()

In [36]:
clientes_df['cidade'].value_counts()

cidade
São Paulo         1280
Fortaleza         1226
Rio de Janeiro    1025
Recife             892
Name: count, dtype: int64

In [37]:
clientes_df['cidade'] = clientes_df['cidade'].str.strip()

clientes_df['cidade'].value_counts()

cidade
São Paulo         1280
Fortaleza         1226
Rio de Janeiro    1025
Recife             892
Name: count, dtype: int64

In [38]:
clientes_df['segmento'].value_counts()

segmento
Regular      2198
Novo         1177
Premium       905
 premium      235
Name: count, dtype: int64

In [39]:
clientes_df['segmento'].str.strip().str.capitalize().value_counts()

segmento
Regular    2198
Novo       1177
Premium    1140
Name: count, dtype: int64

In [40]:
clientes_df['segmento'] = clientes_df['segmento'].str.strip().str.capitalize()

#### Pedidos

In [41]:
pedidos_df.columns

Index(['pedido_id', 'cliente_id', 'categoria', 'valor', 'quantidade'], dtype='str')

In [42]:
pedidos_df['categoria'].value_counts()

categoria
Alimentos       1301
Eletrônicos     1196
 Roupas         1152
Casa             917
eletronicos      434
Name: count, dtype: int64

In [43]:
pedidos_df['categoria'].str.strip().str.replace('eletronicos', 'Eletrônicos').value_counts()

categoria
Eletrônicos    1630
Alimentos      1301
Roupas         1152
Casa            917
Name: count, dtype: int64

In [44]:
pedidos_df['categoria'] = pedidos_df['categoria'].str.strip().str.replace('eletronicos', 'Eletrônicos')

In [45]:
lote_2_df['categoria'].value_counts()

categoria
Alimentos       143
Eletrônicos     122
 Roupas         109
Casa             90
eletronicos      36
Name: count, dtype: int64

In [46]:
lote_2_df['categoria'] = lote_2_df['categoria'].str.strip().str.replace('eletronicos', 'Eletrônicos')

#### Pagamentos

In [47]:
pagamentos_df.columns

Index(['pedido_id', 'forma_pagamento', 'status_pagamento'], dtype='str')

In [48]:
pagamentos_df['forma_pagamento'].value_counts()

forma_pagamento
Crédito    1508
PIX        1424
Debito     1141
 pix        383
Name: count, dtype: int64

In [49]:
pagamentos_df['forma_pagamento'].str.strip().str.lower().value_counts()

forma_pagamento
pix        1807
crédito    1508
debito     1141
Name: count, dtype: int64

In [50]:
pagamentos_df['forma_pagamento'] = pagamentos_df['forma_pagamento'].str.strip().str.lower()

In [51]:
pagamentos_df['status_pagamento'].value_counts()

status_pagamento
Pago           3478
Pendente        819
Cancelado       505
 cancelado      198
Name: count, dtype: int64

In [52]:
pagamentos_df['status_pagamento'].str.strip().str.capitalize().value_counts()

status_pagamento
Pago         3478
Pendente      819
Cancelado     703
Name: count, dtype: int64

In [53]:
pagamentos_df['status_pagamento'] = pagamentos_df['status_pagamento'].str.strip().str.capitalize()

### 3.2 Correção de valores com **replace()**

Padronize:

- **"eletronicos"** para **"eletrônicos"**
- **"debito"** para **"débito"**
- **"pix"** para **"PIX"**
- status de pagamento em formato consistente
- segmento em formato consistente

In [54]:
clientes_df['cidade'].value_counts()

cidade
São Paulo         1280
Fortaleza         1226
Rio de Janeiro    1025
Recife             892
Name: count, dtype: int64

In [55]:
clientes_df['segmento'].value_counts()

segmento
Regular    2198
Novo       1177
Premium    1140
Name: count, dtype: int64

In [56]:
pedidos_df['categoria'].value_counts()

categoria
Eletrônicos    1630
Alimentos      1301
Roupas         1152
Casa            917
Name: count, dtype: int64

In [57]:
lote_2_df['categoria'].value_counts()

categoria
Eletrônicos    158
Alimentos      143
Roupas         109
Casa            90
Name: count, dtype: int64

In [58]:
pagamentos_df['forma_pagamento'].value_counts()

forma_pagamento
pix        1807
crédito    1508
debito     1141
Name: count, dtype: int64

In [59]:
pagamentos_df['forma_pagamento'].str.replace({'pix': 'PIX', 'debito': 'débito'}).value_counts()

forma_pagamento
PIX        1807
crédito    1508
débito     1141
Name: count, dtype: int64

In [60]:
pagamentos_df['status_pagamento'].value_counts()

status_pagamento
Pago         3478
Pendente      819
Cancelado     703
Name: count, dtype: int64

### 3.3 Tratamento de nulos

Trate os nulos conforme a regra de negócio:

- **cidade**: preencher com **"Desconhecido"**
- **segmento**: preencher com **"Não informado"**
- **idade**: preencher com mediana
- **valor**: preencher com média

Depois, confira novamente com **isnull().sum()**.

In [61]:
clientes_df.isnull().sum()

cliente_id      0
nome            0
cidade        577
segmento      485
idade         510
dtype: int64

In [62]:
cidade_nan = clientes_df['cidade'].isna()

print(f'Número de elementos nulos em cidade nos clientes: {len(clientes_df[cidade_nan])}')
clientes_df[cidade_nan].head()

Número de elementos nulos em cidade nos clientes: 577

    cliente_id        nome cidade segmento  idade
1            2   Cliente_2    NaN  Regular   30.0
11          12  Cliente_12    NaN  Regular    NaN
33          34  Cliente_34    NaN     Novo   45.0
34          35  Cliente_35    NaN  Regular   22.0
43          44  Cliente_44    NaN     Novo   35.0

In [63]:
clientes_df.loc[cidade_nan, 'cidade'] = 'Desconhecido'

clientes_df[cidade_nan].head()

    cliente_id        nome        cidade segmento  idade
1            2   Cliente_2  Desconhecido  Regular   30.0
11          12  Cliente_12  Desconhecido  Regular    NaN
33          34  Cliente_34  Desconhecido     Novo   45.0
34          35  Cliente_35  Desconhecido  Regular   22.0
43          44  Cliente_44  Desconhecido     Novo   35.0

In [64]:
segmento_nan = clientes_df['segmento'].isna()

print(f'Número de elementos nulos em segmento do cliente: {len(clientes_df[segmento_nan])}')
clientes_df[segmento_nan].head()

Número de elementos nulos em segmento do cliente: 485

    cliente_id        nome     cidade segmento  idade
0            1   Cliente_1  São Paulo      NaN   35.0
10          11  Cliente_11  Fortaleza      NaN   18.0
42          43  Cliente_43  Fortaleza      NaN   22.0
44          45  Cliente_45  São Paulo      NaN   30.0
57          58  Cliente_58  Fortaleza      NaN   22.0

In [65]:
clientes_df.loc[segmento_nan, 'segmento'] = 'Não informado'

clientes_df[segmento_nan].head()

    cliente_id        nome     cidade       segmento  idade
0            1   Cliente_1  São Paulo  Não informado   35.0
10          11  Cliente_11  Fortaleza  Não informado   18.0
42          43  Cliente_43  Fortaleza  Não informado   22.0
44          45  Cliente_45  São Paulo  Não informado   30.0
57          58  Cliente_58  Fortaleza  Não informado   22.0

In [66]:
idades_nan = clientes_df['idade'].isna()

print(f'Mediana da idade dos clientes: {clientes_df['idade'].median():.2f}; Número de valores nulos: {len(clientes_df[idades_nan])}')
clientes_df[idades_nan].head()

Mediana da idade dos clientes: 30.00; Número de valores nulos: 510

    cliente_id        nome        cidade segmento  idade
11          12  Cliente_12  Desconhecido  Regular    NaN
12          13  Cliente_13        Recife  Regular    NaN
18          19  Cliente_19     São Paulo     Novo    NaN
23          24  Cliente_24     São Paulo  Regular    NaN
37          38  Cliente_38     Fortaleza  Regular    NaN

In [67]:
clientes_df.loc[idades_nan, 'idade'] = clientes_df['idade'].median()

clientes_df[idades_nan].head()

    cliente_id        nome        cidade segmento  idade
11          12  Cliente_12  Desconhecido  Regular   30.0
12          13  Cliente_13        Recife  Regular   30.0
18          19  Cliente_19     São Paulo     Novo   30.0
23          24  Cliente_24     São Paulo  Regular   30.0
37          38  Cliente_38     Fortaleza  Regular   30.0

In [68]:
clientes_df.isnull().sum()

cliente_id    0
nome          0
cidade        0
segmento      0
idade         0
dtype: int64

In [69]:
valor_nan = pedidos_df['valor'].isna()

print(f'Média dos valores dos pedidos: {pedidos_df['valor'].mean().round(2)}; Número de nulos: {len(pedidos_df[valor_nan])}')
pedidos_df[valor_nan].head()

Média dos valores dos pedidos: 322.9; Número de nulos: 252

    pedido_id  cliente_id    categoria  valor  quantidade
10     100011        2430    Alimentos    NaN           3
20     100021        4959       Roupas    NaN           7
67     100068        3847  Eletrônicos    NaN           3
68     100069        4168  Eletrônicos    NaN           7
70     100071        2521  Eletrônicos    NaN           2

In [70]:
pedidos_df.loc[valor_nan, 'valor'] = pedidos_df['valor'].mean().round(2)

pedidos_df[valor_nan].head()

    pedido_id  cliente_id    categoria  valor  quantidade
10     100011        2430    Alimentos  322.9           3
20     100021        4959       Roupas  322.9           7
67     100068        3847  Eletrônicos  322.9           3
68     100069        4168  Eletrônicos  322.9           7
70     100071        2521  Eletrônicos  322.9           2

In [71]:
lote2_valor_nan = lote_2_df['valor'].isna()
lote_2_df.loc[lote2_valor_nan, 'valor'] = lote_2_df['valor'].mean().round(2)

lote_2_df[lote2_valor_nan].head()

     pedido_id  cliente_id    categoria   valor  quantidade
74      105075        3782       Roupas  315.97           4
79      105080         594       Roupas  315.97           6
96      105097        1598  Eletrônicos  315.97           6
102     105103        4076       Roupas  315.97           4
103     105104           4    Alimentos  315.97           2

In [72]:
pedidos_df.isnull().sum()

pedido_id     0
cliente_id    0
categoria     0
valor         0
quantidade    0
dtype: int64

In [73]:
lote_2_df.isnull().sum()

pedido_id     0
cliente_id    0
categoria     0
valor         0
quantidade    0
dtype: int64

In [74]:
pagamentos_df.isnull().sum()

pedido_id             0
forma_pagamento     544
status_pagamento      0
dtype: int64

In [75]:
forma_nan = pagamentos_df['forma_pagamento'].isna()

print(f'Número de formas de pagamentos nulos no Dataset: {len(pagamentos_df[forma_nan])}')
pagamentos_df[forma_nan].head()

Número de formas de pagamentos nulos no Dataset: 544

    pedido_id forma_pagamento status_pagamento
23     101896             NaN             Pago
33     100510             NaN             Pago
35     104637             NaN             Pago
47     103460             NaN             Pago
58     102459             NaN             Pago

In [76]:
pagamentos_df.loc[forma_nan, 'forma_pagamento'] = 'Desconhecido'

pagamentos_df[forma_nan].head()

    pedido_id forma_pagamento status_pagamento
23     101896    Desconhecido             Pago
33     100510    Desconhecido             Pago
35     104637    Desconhecido             Pago
47     103460    Desconhecido             Pago
58     102459    Desconhecido             Pago

### 3.4 Conversão de tipos com **astype()**

Converta:

- **idade** para inteiro
- **valor** para float
- **quantidade** para inteiro, se necessário

In [77]:
clientes_df.dtypes

cliente_id      int64
nome              str
cidade            str
segmento          str
idade         float64
dtype: object

In [78]:
clientes_df['idade'] = clientes_df['idade'].astype(int)

clientes_df['idade'].dtype

dtype('int64')

In [79]:
pagamentos_df.dtypes

pedido_id           int64
forma_pagamento       str
status_pagamento      str
dtype: object

In [80]:
pedidos_df.dtypes

pedido_id       int64
cliente_id      int64
categoria         str
valor         float64
quantidade      int64
dtype: object

In [81]:
lote_2_df.dtypes

pedido_id       int64
cliente_id      int64
categoria         str
valor         float64
quantidade      int64
dtype: object

### 3.5 Duplicados

Verifique se há existência de duplicados nos datasets, se houver, realize a remoção.

In [82]:
clientes_df.duplicated().value_counts()

False    4980
True       20
Name: count, dtype: int64

In [83]:
pagamentos_df.duplicated().value_counts()

False    4711
True      289
Name: count, dtype: int64

In [84]:
pedidos_df.duplicated().value_counts()

False    5000
Name: count, dtype: int64

In [85]:
lote_2_df.duplicated().value_counts()

False    500
Name: count, dtype: int64

In [86]:
clientes_df.drop_duplicates(inplace=True)
pagamentos_df.drop_duplicates(inplace=True)

In [87]:
clientes_df.duplicated().value_counts()

False    4980
Name: count, dtype: int64

In [88]:
pagamentos_df.duplicated().value_counts()

False    4711
Name: count, dtype: int64

## 4. Seleção, filtros e ordenação

### 4.1 Seleção de colunas

Selecione apenas:

- **cliente_id**
- **nome**
- **cidade**
- **segmento**

In [89]:
clientes_df[['cliente_id', 'nome', 'cidade', 'segmento']].head(10)

   cliente_id        nome          cidade       segmento
0           1   Cliente_1       São Paulo  Não informado
1           2   Cliente_2    Desconhecido        Regular
2           3   Cliente_3          Recife           Novo
3           4   Cliente_4  Rio de Janeiro           Novo
4           5   Cliente_5       Fortaleza        Regular
5           6   Cliente_6       Fortaleza        Premium
6           7   Cliente_7       Fortaleza           Novo
7           8   Cliente_8          Recife           Novo
8           9   Cliente_9  Rio de Janeiro           Novo
9          10  Cliente_10          Recife           Novo

### 4.2 Seleção de linhas com condição

Selecione clientes:

- da cidade de Fortaleza
- com idade maior que 25

In [90]:
fortaleza_mq25 = (clientes_df['cidade'] == 'Fortaleza') & (clientes_df['idade'] > 25)

clientes_df[fortaleza_mq25].head(10)

    cliente_id        nome     cidade segmento  idade
4            5   Cliente_5  Fortaleza  Regular     30
5            6   Cliente_6  Fortaleza  Premium     30
6            7   Cliente_7  Fortaleza     Novo     35
14          15  Cliente_15  Fortaleza  Premium     30
21          22  Cliente_22  Fortaleza  Regular     35
26          27  Cliente_27  Fortaleza     Novo     30
29          30  Cliente_30  Fortaleza  Regular     45
31          32  Cliente_32  Fortaleza     Novo     30
32          33  Cliente_33  Fortaleza  Regular     30
37          38  Cliente_38  Fortaleza  Regular     30

### 4.3 Seleção com **.loc[]**

Usando **.loc[]**, selecione linhas e colunas pelo rótulo.

Exemplo do objetivo:

- clientes de São Paulo
- colunas **nome**, **cidade**, **segmento**

In [91]:
clientes_sp = clientes_df['cidade'] == 'São Paulo'

clientes_df.loc[clientes_sp, ['nome', 'cidade', 'segmento']].head()

          nome     cidade       segmento
0    Cliente_1  São Paulo  Não informado
16  Cliente_17  São Paulo        Premium
18  Cliente_19  São Paulo           Novo
19  Cliente_20  São Paulo        Regular
22  Cliente_23  São Paulo        Premium

### 4.4 Seleção com **.iloc[]**

Usando **.iloc[]**, selecione:

- linhas de 5 a 10
- as três primeiras colunas

In [92]:
clientes_df.iloc[5 : 10, :3]

   cliente_id        nome          cidade
5           6   Cliente_6       Fortaleza
6           7   Cliente_7       Fortaleza
7           8   Cliente_8          Recife
8           9   Cliente_9  Rio de Janeiro
9          10  Cliente_10          Recife

### 4.5 Ordenação

Ordene os pedidos pelo maior valor primeiro.

In [93]:
pedidos_ord = pedidos_df['valor'].sort_values(ascending=False)

pedidos_ord.head()

3369    900.0
3373    900.0
37      900.0
1912    900.0
3337    900.0
Name: valor, dtype: float64

In [94]:
pedidos_df.loc[pedidos_ord.index]

      pedido_id  cliente_id    categoria  valor  quantidade
3369     103370        2397         Casa  900.0           7
3373     103374        2563       Roupas  900.0           1
37       100038        4523  Eletrônicos  900.0           7
1912     101913        3282  Eletrônicos  900.0           7
3337     103338        1725       Roupas  900.0           6
...         ...         ...          ...    ...         ...
1593     101594        4938       Roupas   80.0           7
25       100026        1404  Eletrônicos   80.0           7
1962     101963        1798    Alimentos   80.0           7
1961     101962        2175  Eletrônicos   80.0           5
1957     101958         548    Alimentos   80.0           7

[5000 rows x 5 columns]

## 5. Criação e atualização de colunas

### 5.1 Criar **valor_total**

**Onde:** valor_total = valor * quantidade

In [115]:
pedidos_df['valor_total'] = pedidos_df['valor'] * pedidos_df['quantidade']

pedidos_df[['valor', 'quantidade', 'valor_total']].head()

   valor  quantidade  valor_total
0  600.0           3       1800.0
1   80.0           7        560.0
2  600.0           4       2400.0
3  400.0           3       1200.0
4  250.0           3        750.0

In [116]:
lote_2_df['valor_total'] = lote_2_df['valor'] * lote_2_df['quantidade']

lote_2_df[['valor', 'quantidade', 'valor_total']].head()

   valor  quantidade  valor_total
0   80.0           6        480.0
1  600.0           2       1200.0
2   80.0           1         80.0
3   80.0           5        400.0
4  250.0           1        250.0

### 5.2 Criar faixa de pedido

Crie uma coluna chamada **faixa_pedido**:

- **"alto valor"** se **valor_total >= 1500**
- **"baixo/médio valor"** caso contrário

In [117]:
pedidos_df['faixa_pedido'] = 'alto valor'

baixo_valor = pedidos_df['valor_total'] < 1500
pedidos_df[baixo_valor].head()

,pedido_id,cliente_id,categoria,valor,quantidade,valor_total,faixa_pedido
1,100002,1335,Eletrônicos,80.0,7,560.0,alto valor
3,100004,2624,Alimentos,400.0,3,1200.0,alto valor
4,100005,239,Roupas,250.0,3,750.0,alto valor
6,100007,5140,Roupas,250.0,3,750.0,alto valor
7,100008,3648,Casa,80.0,4,320.0,alto valor

In [118]:
pedidos_df.loc[baixo_valor, 'faixa_pedido'] = 'baixo/médio valor'

pedidos_df[baixo_valor].head()

,pedido_id,cliente_id,categoria,valor,quantidade,valor_total,faixa_pedido
1,100002,1335,Eletrônicos,80.0,7,560.0,baixo/médio valor
3,100004,2624,Alimentos,400.0,3,1200.0,baixo/médio valor
4,100005,239,Roupas,250.0,3,750.0,baixo/médio valor
6,100007,5140,Roupas,250.0,3,750.0,baixo/médio valor
7,100008,3648,Casa,80.0,4,320.0,baixo/médio valor

In [119]:
lote_2_df['faixa_pedido'] = 'alto valor'
baixo_valor_l2 = lote_2_df['valor_total'] < 1500
lote_2_df.loc[baixo_valor_l2, 'faixa_pedido'] = 'baixo/médio valor'

lote_2_df[baixo_valor_l2].head()

,pedido_id,cliente_id,categoria,valor,quantidade,valor_total,faixa_pedido
0,105001,4503,Eletrônicos,80.0,6,480.0,baixo/médio valor
1,105002,1383,Casa,600.0,2,1200.0,baixo/médio valor
2,105003,4982,Casa,80.0,1,80.0,baixo/médio valor
3,105004,4969,Alimentos,80.0,5,400.0,baixo/médio valor
4,105005,5086,Roupas,250.0,1,250.0,baixo/médio valor

### 5.3 Renomear colunas

Renomeie as colunas para um padrão:

- minúsculas
- sem espaços
- se já estiverem nesse padrão, apenas confirme

In [97]:
#Implementação

## 6. Integração dos dados

### 6.1 Concat

Concatene **pedidos** com **pedidos_lote_2**.

Depois confira:

- quantidade de linhas antes
- quantidade de linhas depois

In [98]:
#Implementação

### 6.2 Merge clientes + pedidos

Faça um **merge** entre pedidos e clientes usando **cliente_id**.

Use **how="left"** para preservar todos os pedidos.

Pergunta de negócio:

> Existem pedidos de clientes que não estão cadastrados?

In [99]:
#Implementação

### 6.3 Merge com pagamentos

Faça um **merge** da base consolidada com pagamentos usando **pedido_id**.

Use **how="left"**.

Pergunta de negócio:

> Existem pedidos sem pagamento registrado?

In [100]:
#Implementação

### 6.4 Join

Crie uma versão de **clientes** com **cliente_id** como índice e uma versão de **pedidos** com **cliente_id** como índice.

Depois faça um **join**.

Pergunta:

> Qual é a diferença prática entre esse **join** e o **merge** anterior?

In [101]:
#Implementação

## 7. Análise de negócio com **groupby**

Use a base consolidada para responder as perguntas.

### 7.1 Faturamento total

In [102]:
#Implementação

### 7.2 Faturamento por cidade

In [103]:
#Implementação

### 7.3 Faturamento por categoria

In [104]:
#Implementação

### 7.4 Faturamento por segmento

In [105]:
#Implementação

### 7.5 Ticket médio por cidade

In [106]:
#Implementação

### 7.6 Cliente que mais gastou

In [107]:
#Implementação

### 7.7 Pedidos por status de pagamento

In [108]:
#Implementação

### 7.8 Receita por status de pagamento

In [109]:
#Implementação

### 7.9 Receita problemática

Considere receita problemática como pedidos com status:

- pendente
- cancelado

Calcule:

- receita problemática
- percentual da receita problemática em relação ao total

In [110]:
# Calcule a receita problemática aqui

## 8. A categoria que mais vende também é a categoria com mais pedidos?

Crie uma tabela por categoria com:

- faturamento
- quantidade de pedidos
- ticket médio

In [111]:
#Implementação

### 8.2 Alguma cidade tem muitos pedidos, mas baixo faturamento?

Crie uma tabela por cidade com:

- faturamento
- quantidade de pedidos
- ticket médio

In [112]:
#Implementação

### 8.3 Existe segmento com alto faturamento, mas muitos pagamentos problemáticos?

Crie uma coluna booleana **pagamento_problematico**.

Depois agrupe por segmento.

In [113]:
#Implementação

## 9. Relatório

Escreva abaixo suas conclusões.

###Estrutura sugerida

1. Resumo geral
2. Riscos encontrados
4. Recomendações de negócio

In [114]:
# Escreva seu relatório em markdown ou como string aqui