## Contexto

Você foi contratado como analista de dados de um e-commerce. A diretoria trouxe algumas perguntas:

> "Estamos vendendo bem? Quais clientes são mais importantes? Quais categorias dão mais receita? Estamos perdendo pedidos por problemas de pagamento?"

O problema: os dados vieram sujos, inconsistentes, espalhados em várias tabelas e agora em volume maior, com aproximadamente 5.000 registros em cada base principal.

---

## Objetivos técnicos

Neste case, você deverá aplicar:

- **head()**, **tail()**, **info()**, **describe()**, **shape**, **columns**, **dtypes**
- **isnull()**, **isnull().sum()**
- seleção de colunas
- seleção de linhas
- **.loc[]**
- **.iloc[]**
- filtros com condições
- ordenação
- criação e atualização de colunas
- renomeação de colunas
- **dropna()**, **fillna()**
- **duplicated()**, **drop_duplicates()**
- **astype()**, **replace()**
- **.str.lower()**, **.str.strip()**, **.str.upper()**
- **concat()**, **merge()**, **join()**
- **groupby()** e funções de agregação

---

## Entregável final

Ao final, você deverá produzir um pequeno relatório executivo respondendo:

1. Qual foi o faturamento total?
2. Qual cidade gerou mais receita?
3. Qual categoria teve maior faturamento?
4. Qual segmento de cliente compra mais?
5. Qual cliente mais gastou?
6. Qual percentual dos pedidos está pendente ou cancelado?
7. Existe perda de receita por pagamentos não aprovados?
8. Quais pedidos ficaram sem informação de pagamento?
9. Qual ticket médio por cidade?
10. Que recomendações de negócio você faria?
11. Notebook com as implementações e respostas para as perguntas acima e no final.

## 1. Criação dos dataframes.

In [1]:
import pandas as pd

clientes_df = pd.read_csv('./data/e_commerce/clientes.csv')
pagamentos_df = pd.read_csv('./data/e_commerce/pagamentos.csv')
pedidos_df = pd.read_csv('./data/e_commerce/pedidos.csv')
lote_2_df = pd.read_csv('./data/e_commerce/pedidos_lote2.csv')

## 2. Exploração inicial

Use os métodos abaixo nas três bases:

- **head()**
- **tail()**
- **info()**
- **describe()**
- **shape**
- **columns**
- **dtypes**
- **isnull()**
- **isnull().sum()**

### Perguntas

1. Quantas linhas e colunas existem em CADA base?
2. Quais colunas possuem valores nulos?
3. Quais colunas estão com tipo de dado inadequado?
4. Existem inconsistências textuais?
5. Existem possíveis chaves sem correspondência entre as tabelas?

#### Dataset Clientes

In [3]:
print(f'A base clientes possui {clientes_df.shape[0]} linhas e {clientes_df.shape[1]} colunas')

print('\nColunas com valores nulos:')
clientes_df.isnull().sum()

A base clientes possui 5000 linhas e 6 colunas

Colunas com valores nulos:

Unnamed: 0      0
cliente_id      0
nome            0
cidade        577
segmento      485
idade         510
dtype: int64

In [4]:
clientes_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  5000 non-null   int64
 1   cliente_id  5000 non-null   int64
 2   nome        5000 non-null   str
 3   cidade      4423 non-null   str
 4   segmento    4515 non-null   str
 5   idade       4490 non-null   float64
dtypes: float64(1), int64(2), str(3)
memory usage: 373.4 KB

In [5]:
clientes_df.head()

   Unnamed: 0  cliente_id         nome          cidade segmento  idade
0           0           1   Cliente_1        São Paulo      NaN   35.0
1           1           2   Cliente_2              NaN  Regular   30.0
2           2           3   Cliente_3           Recife     Novo   30.0
3           3           4   Cliente_4   Rio de Janeiro     Novo   30.0
4           4           5   Cliente_5        Fortaleza  Regular   30.0

In [6]:
clientes_df.tail()

      Unnamed: 0  cliente_id            nome     cidade segmento  idade
4995        4995        1804   Cliente_1804   São Paulo  Regular   22.0
4996        4996         721    Cliente_721         NaN  Regular   30.0
4997        4997         427    Cliente_427   São Paulo      NaN   22.0
4998        4998        3334   Cliente_3334   Fortaleza     Novo   18.0
4999        4999         394    Cliente_394      Recife     Novo   45.0

In [8]:
clientes_df.drop('Unnamed: 0', axis='columns', inplace=True)

In [9]:
clientes_df.describe()

        cliente_id        idade
count  5000.000000  4490.000000
mean   2489.280600    29.955011
std    1437.621535     8.302572
min       1.000000    18.000000
25%    1242.750000    22.000000
50%    2488.500000    30.000000
75%    3732.250000    35.000000
max    4980.000000    45.000000

In [12]:
clientes_df.columns

Index(['cliente_id', 'nome', 'cidade', 'segmento', 'idade'], dtype='str')

In [13]:
clientes_df.dtypes

cliente_id      int64
nome              str
cidade            str
segmento          str
idade         float64
dtype: object

Aparentemente, nenhuma colunas com tipo de valor inconsistente na base de dados de clientes. Também não parece haver inconsistência nos tipos de dados das colunas dos pedidos e do segundo lote.

#### Dataset Pedidos e Pedidos Lote 2

In [14]:
print(f'Dataset pedidos possui {pedidos_df.shape[0]} linhas e {pedidos_df.shape[1]} colunas')
print(f'Lote 2 dos pedidos possui {lote_2_df.shape[0]} linhas e {lote_2_df.shape[1]} colunas')

print('\nPedidos com valores nulos:')
pedidos_df.isnull().sum()

Dataset pedidos possui 5000 linhas e 6 colunas
Lote 2 dos pedidos possui 500 linhas e 6 colunas

Pedidos com valores nulos:

Unnamed: 0      0
pedido_id       0
cliente_id      0
categoria       0
valor         252
quantidade      0
dtype: int64

In [15]:
print('Lote 2 com valores nulos:')
lote_2_df.isnull().sum()

Lote 2 com valores nulos:

Unnamed: 0     0
pedido_id      0
cliente_id     0
categoria      0
valor         23
quantidade     0
dtype: int64

In [16]:
pedidos_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  5000 non-null   int64
 1   pedido_id   5000 non-null   int64
 2   cliente_id  5000 non-null   int64
 3   categoria   5000 non-null   str
 4   valor       4748 non-null   float64
 5   quantidade  5000 non-null   int64
dtypes: float64(1), int64(4), str(1)
memory usage: 276.5 KB

In [17]:
lote_2_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  500 non-null    int64
 1   pedido_id   500 non-null    int64
 2   cliente_id  500 non-null    int64
 3   categoria   500 non-null    str
 4   valor       477 non-null    float64
 5   quantidade  500 non-null    int64
dtypes: float64(1), int64(4), str(1)
memory usage: 27.8 KB

In [18]:
pedidos_df.head()

   Unnamed: 0  pedido_id  cliente_id     categoria  valor  quantidade
0           0     100001        1523  eletronicos   600.0           3
1           1     100002        1335   Eletrônicos   80.0           7
2           2     100003        5391          Casa  600.0           4
3           3     100004        2624     Alimentos  400.0           3
4           4     100005         239        Roupas  250.0           3

In [19]:
lote_2_df.head()

   Unnamed: 0  pedido_id  cliente_id    categoria  valor  quantidade
0           0     105001        4503  Eletrônicos   80.0           6
1           1     105002        1383         Casa  600.0           2
2           2     105003        4982         Casa   80.0           1
3           3     105004        4969    Alimentos   80.0           5
4           4     105005        5086       Roupas  250.0           1

In [20]:
pedidos_df.tail()

      Unnamed: 0  pedido_id  cliente_id    categoria  valor  quantidade
4995        4995     104996        1811  Eletrônicos  400.0           2
4996        4996     104997        3202       Roupas  600.0           7
4997        4997     104998         753  Eletrônicos  120.0           1
4998        4998     104999        2473       Roupas  600.0           3
4999        4999     105000        5033  Eletrônicos  250.0           6

In [21]:
lote_2_df.tail()

     Unnamed: 0  pedido_id  cliente_id    categoria  valor  quantidade
495         495     105496        2661  Eletrônicos  250.0           2
496         496     105497        2263  Eletrônicos  600.0           4
497         497     105498        4358    Alimentos  600.0           3
498         498     105499         764         Casa  400.0           1
499         499     105500        2368    Alimentos   80.0           6

In [22]:
pedidos_df.drop('Unnamed: 0', axis='columns', inplace=True)
lote_2_df.drop('Unnamed: 0', axis='columns', inplace=True)

In [23]:
pedidos_df.describe()

           pedido_id  cliente_id        valor   quantidade
count    5000.000000   5000.0000  4748.000000  5000.000000
mean   102500.500000   2723.5960   322.900168     4.028600
std      1443.520003   1574.4692   239.252208     2.011912
min    100001.000000      1.0000    80.000000     1.000000
25%    101250.750000   1375.7500   120.000000     2.000000
50%    102500.500000   2751.5000   250.000000     4.000000
75%    103750.250000   4044.2500   400.000000     6.000000
max    105000.000000   5480.0000   900.000000     7.000000

In [24]:
lote_2_df.describe()

           pedido_id   cliente_id       valor  quantidade
count     500.000000   500.000000  477.000000  500.000000
mean   105250.500000  2775.960000  315.974843    3.956000
std       144.481833  1495.864807  233.783602    2.086809
min    105001.000000     4.000000   80.000000    1.000000
25%    105125.750000  1614.000000  120.000000    2.000000
50%    105250.500000  2687.000000  250.000000    4.000000
75%    105375.250000  3973.000000  400.000000    6.000000
max    105500.000000  5438.000000  900.000000    7.000000

In [25]:
print('Colunas de pedidos:')
print(pedidos_df.columns)
print('\nColunas do lote 2 de pedidos:')
print(lote_2_df.columns)

Colunas de pedidos:
Index(['pedido_id', 'cliente_id', 'categoria', 'valor', 'quantidade'], dtype='str')

Colunas do lote 2 de pedidos:
Index(['pedido_id', 'cliente_id', 'categoria', 'valor', 'quantidade'], dtype='str')

In [27]:
print('Tipos das colunas de pedidos:')
print(pedidos_df.dtypes)
print('\nTipos das colunas do segundo lote:')
print(lote_2_df.dtypes)

Tipos das colunas de pedidos:
pedido_id       int64
cliente_id      int64
categoria         str
valor         float64
quantidade      int64
dtype: object

Tipos das colunas do segundo lote:
pedido_id       int64
cliente_id      int64
categoria         str
valor         float64
quantidade      int64
dtype: object

Pode haver inconsistências entre os ids de clientes na tabela de clientes e id de clientes nas tabelas de pedidos.

#### Dataset Pagamentos

In [28]:
print(f'Dataset de pagamentos possui {pagamentos_df.shape[0]} linhas e {pagamentos_df.shape[1]} colunas')

print('\nValores nulos em pagamentos:')
pagamentos_df.isnull().sum()

Dataset de pagamentos possui 5000 linhas e 4 colunas

Valores nulos em pagamentos:

Unnamed: 0            0
pedido_id             0
forma_pagamento     544
status_pagamento      0
dtype: int64

In [29]:
pagamentos_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        5000 non-null   int64
 1   pedido_id         5000 non-null   int64
 2   forma_pagamento   4456 non-null   str
 3   status_pagamento  5000 non-null   str
dtypes: int64(2), str(2)
memory usage: 208.0 KB

In [30]:
pagamentos_df.head()

   Unnamed: 0  pedido_id forma_pagamento status_pagamento
0           0     101269          Debito        Cancelado
1           1     104267             PIX             Pago
2           2     105746         Crédito             Pago
3           3     104817            pix          Pendente
4           4     103043          Debito             Pago

In [31]:
pagamentos_df.tail()

      Unnamed: 0  pedido_id forma_pagamento status_pagamento
4995        4995     101307             NaN             Pago
4996        4996     105333             NaN             Pago
4997        4997     101688          Debito             Pago
4998        4998     105798         Crédito        Cancelado
4999        4999     103984             PIX             Pago

In [32]:
pagamentos_df.drop('Unnamed: 0', axis='columns', inplace=True)

In [33]:
pagamentos_df.describe()

           pedido_id
count    5000.000000
mean   102992.939200
std      1750.051069
min    100001.000000
25%    101469.750000
50%    103013.000000
75%    104505.000000
max    106000.000000

In [34]:
pagamentos_df.columns

Index(['pedido_id', 'forma_pagamento', 'status_pagamento'], dtype='str')

In [35]:
pagamentos_df.dtypes

pedido_id           int64
forma_pagamento       str
status_pagamento      str
dtype: object

Também não parece haver inconsistência nos tipos de dados das counas de Pagamentos

## 3. Limpeza dos dados

### 3.1 Limpeza de strings

Corrija espaços extras e padronize textos.

Sugestões:

- **nome**: remover espaços
- **cidade**: remover espaços
- **segmento**: remover espaços e padronizar
- **categoria**: remover espaços, padronizar minúsculas e corrigir grafias
- **forma_pagamento**: remover espaços e padronizar
- **status_pagamento**: remover espaços e padronizar

In [ ]:
#Implementação

### 3.2 Correção de valores com **replace()**

Padronize:

- **"eletronicos"** para **"eletrônicos"**
- **"debito"** para **"débito"**
- **"pix"** para **"PIX"**
- status de pagamento em formato consistente
- segmento em formato consistente

In [ ]:
#Implementação

### 3.3 Tratamento de nulos

Trate os nulos conforme a regra de negócio:

- **cidade**: preencher com **"Desconhecido"**
- **segmento**: preencher com **"Não informado"**
- **idade**: preencher com mediana
- **valor**: preencher com média

Depois, confira novamente com **isnull().sum()**.

In [ ]:
#Implementação

### 3.4 Conversão de tipos com **astype()**

Converta:

- **idade** para inteiro
- **valor** para float
- **quantidade** para inteiro, se necessário

In [ ]:
#Implementação

### 3.5 Duplicados

Verifique se há existência de duplicados nos datasets, se houver, realize a remoção.

In [ ]:
#Implementação

## 4. Seleção, filtros e ordenação

### 4.1 Seleção de colunas

Selecione apenas:

- **cliente_id**
- **nome**
- **cidade**
- **segmento**

In [ ]:
#Implementação

### 4.2 Seleção de linhas com condição

Selecione clientes:

- da cidade de Fortaleza
- com idade maior que 25

In [ ]:
#Implementação

### 4.3 Seleção com **.loc[]**

Usando **.loc[]**, selecione linhas e colunas pelo rótulo.

Exemplo do objetivo:

- clientes de São Paulo
- colunas **nome**, **cidade**, **segmento**

In [ ]:
#Implementação

### 4.4 Seleção com **.iloc[]**

Usando **.iloc[]**, selecione:

- linhas de 5 a 10
- as três primeiras colunas

In [ ]:
#Implementação

### 4.5 Ordenação

Ordene os pedidos pelo maior valor primeiro.

In [ ]:
#Implementação

## 5. Criação e atualização de colunas

### 5.1 Criar **valor_total**

**Onde:** valor_total = valor * quantidade

In [ ]:
#Implementação

### 5.2 Criar faixa de pedido

Crie uma coluna chamada **faixa_pedido**:

- **"alto valor"** se **valor_total >= 1500**
- **"baixo/médio valor"** caso contrário

In [ ]:
#Implementação

### 5.3 Renomear colunas

Renomeie as colunas para um padrão:

- minúsculas
- sem espaços
- se já estiverem nesse padrão, apenas confirme

In [ ]:
#Implementação

## 6. Integração dos dados

### 6.1 Concat

Concatene **pedidos** com **pedidos_lote_2**.

Depois confira:

- quantidade de linhas antes
- quantidade de linhas depois

In [ ]:
#Implementação

### 6.2 Merge clientes + pedidos

Faça um **merge** entre pedidos e clientes usando **cliente_id**.

Use **how="left"** para preservar todos os pedidos.

Pergunta de negócio:

> Existem pedidos de clientes que não estão cadastrados?

In [ ]:
#Implementação

### 6.3 Merge com pagamentos

Faça um **merge** da base consolidada com pagamentos usando **pedido_id**.

Use **how="left"**.

Pergunta de negócio:

> Existem pedidos sem pagamento registrado?

In [ ]:
#Implementação

### 6.4 Join

Crie uma versão de **clientes** com **cliente_id** como índice e uma versão de **pedidos** com **cliente_id** como índice.

Depois faça um **join**.

Pergunta:

> Qual é a diferença prática entre esse **join** e o **merge** anterior?

In [ ]:
#Implementação

## 7. Análise de negócio com **groupby**

Use a base consolidada para responder as perguntas.

### 7.1 Faturamento total

In [ ]:
#Implementação

### 7.2 Faturamento por cidade

In [ ]:
#Implementação

### 7.3 Faturamento por categoria

In [ ]:
#Implementação

### 7.4 Faturamento por segmento

In [ ]:
#Implementação

### 7.5 Ticket médio por cidade

In [ ]:
#Implementação

### 7.6 Cliente que mais gastou

In [ ]:
#Implementação

### 7.7 Pedidos por status de pagamento

In [ ]:
#Implementação

### 7.8 Receita por status de pagamento

In [ ]:
#Implementação

### 7.9 Receita problemática

Considere receita problemática como pedidos com status:

- pendente
- cancelado

Calcule:

- receita problemática
- percentual da receita problemática em relação ao total

In [ ]:
# Calcule a receita problemática aqui

##8. A categoria que mais vende também é a categoria com mais pedidos?

Crie uma tabela por categoria com:

- faturamento
- quantidade de pedidos
- ticket médio

In [ ]:
#Implementação

### 8.2 Alguma cidade tem muitos pedidos, mas baixo faturamento?

Crie uma tabela por cidade com:

- faturamento
- quantidade de pedidos
- ticket médio

In [ ]:
#Implementação

### 8.3 Existe segmento com alto faturamento, mas muitos pagamentos problemáticos?

Crie uma coluna booleana **pagamento_problematico**.

Depois agrupe por segmento.

In [ ]:
#Implementação

## 9. Relatório

Escreva abaixo suas conclusões.

###Estrutura sugerida

1. Resumo geral
2. Riscos encontrados
4. Recomendações de negócio

In [ ]:
# Escreva seu relatório em markdown ou como string aqui